import type { BlogPost } from '@/types';
import { seedImages } from './images';

export const seedBlog: BlogPost[] = [
  {
    id: 'b-1',
    slug: 'how-to-apply-to-turkish-universities',
    title: {
      en: 'How to Apply to Turkish Universities: A Step-by-Step Guide',
      tr: 'Türk Üniversitelerine Nasıl Başvurulur: Adım Adım Rehber',
      az: 'Türk Universitetlərinə Necə Müraciət Etmək Olar: Addım-addım Bələdçi',
      ru: 'Как поступить в турецкие университеты: пошаговое руководство',
    },
    excerpt: {
      en: 'From choosing a program to getting your acceptance letter — everything you need to know about the application process.',
      tr: 'Program seçmekten kabul mektubunu almak kadar — başvuru süreci hakkında bilmeniz gereken her şey.',
      az: 'Proqram seçməkdən qəbul məktubu almağa qədər — müraciət prosesi haqqında bilməli olduğunuz hər şey.',
      ru: 'От выбора программы до получения письма о зачислении — всё о процессе подачи заявки.',
    },
    content: {
      en: 'Applying to a Turkish university is straightforward if you follow the steps carefully. First, shortlist programs that match your goals and budget. Second, prepare your documents: passport, diploma, transcript, language certificate and motivational letter. Third, submit applications — many universities accept online applications year-round. Fourth, after acceptance, apply for a student visa and arrange accommodation. Finally, arrive and convert your visa to a residence permit within a month.',
      tr: 'Türk üniversitesine başvurmak adımları dikkatlice izlerseniz kolaydır. Önce hedeflerinize ve bütçenize uygun programları kısa listeye alın. İkinci olarak belgelerinizi hazırlayın: pasaport, diploma, transkript, dil sertifikası ve motivasyon mektubu. Üçüncü olarak başvurularınızı gönderin — birçok üniversite yıl boyunca çevrimiçi başvuru kabul eder. Dördüncü olarak kabul sonrası öğrenci vizesi için başvurun ve konaklama ayarlayın. Son olarak varın ve bir ay içinde vizenizi ikamet iznine dönüştürün.',
      az: 'Türk universitetinə müraciət addımlarını diqqətlə izləsəniz asandır. Əvvəlcə məqsədlərinizə və büdcənizə uyğun proqramları qısa siyahıya alın. İkincisi, sənədlərinizi hazırlayın: pasport, diplom, transkript, dil sertifikatı və motivasiya məktubu. Üçüncüsü, müraciətlərinizi göndərin — bir çox universitet il boyu onlayn müraciət qəbul edir. Dördüncüsü, qəbuldan sonra tələbə vizası üçün müraciət edin və qalma yeri təşkil edin. Son olaraq gəlin və bir ay ərzində vizanızı yaşayış icazəsinə çevirin.',
      ru: 'Поступить в турецкий университет несложно, если следовать шагам. Сначала составьте список программ по целям и бюджету. Затем подготовьте документы: паспорт, диплом, выписку, сертификат о языке и мотивационное письмо. После отправьте заявки — многие вузы принимают онлайн круглый год. После зачисления оформите студенческую визу и жильё. По приезде в течение месяца поменяйте визу на вид на жительство.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-06-15',
    coverImage: seedImages.students,
    category: { en: 'Guides', tr: 'Rehberler', az: 'Bələdçilər', ru: 'Руководства' },
    readingMinutes: 6,
  },
  {
    id: 'b-2',
    slug: 'cost-of-living-in-istanbul-for-students',
    title: {
      en: 'Cost of Living in Istanbul for Students in 2026',
      tr: '2026\'da Öğrenciler için İstanbul Yaşam Maliyeti',
      az: '2026-cı ildə Tələbələr üçün İstanbul Yaşayış Xərcləri',
      ru: 'Стоимость жизни в Стамбуле для студентов в 2026 году',
    },
    excerpt: {
      en: 'Rent, food, transport and fun — a realistic monthly budget breakdown for student life in Istanbul.',
      tr: 'Kira, yemek, ulaşım ve eğlence — İstanbul öğrenci hayatı için gerçekçi bir aylık bütçe dökümü.',
      az: 'İcarə, yemək, nəqliyyat və əyləncə — İstanbul tələbə həyatı üçün realistik aylıq büdcə dökümü.',
      ru: 'Аренда, еда, транспорт и развлечения — реалистичная разбивка ежемесячного бюджета студента в Стамбуле.',
    },
    content: {
      en: 'Istanbul offers a vibrant student life at a reasonable cost. A shared flat runs about USD 200–350 per month; a university dorm is cheaper at USD 150–250. Groceries cost around USD 120–180, and a student transport pass is about USD 20 monthly. Eating out is affordable: a hearty meal is USD 3–6. Overall, plan for USD 400–600 per month including everything.',
      tr: 'İstanbul makul maliyetle canlı bir öğrenci hayatı sunar. Paylaşımlı daire ayda 200–350 USD; üniversite yurdu 150–250 USD ile daha ucuzdur. Market harcamaları 120–180 USD, öğrenci ulaşım kartı aylık 20 USD civarıdır. Dışarıda yemek ucuzdur: doyurucu bir öğün 3–6 USD. Genel olarak her şey dahil ayda 400–600 USD planlayın.',
      az: 'İstanbul məqbul qiymətə canlı tələbə həyatı təklif edir. Paylaşılan mənzil ayda 200–350 ABŞ dolları; universitet yataqxanası 150–250 ABŞ dolları ilə daha ucuzdur. Market xərcləri 120–180 ABŞ dolları, tələbə nəqliyyat kartı ayda 20 ABŞ dollarıdır. Bayırda yemək ucuzdur: doyüşlu yemək 3–6 ABŞ dolları. Ümumilikdə hər şey daxil ayda 400–600 ABŞ dolları planlayın.',
      ru: 'Стамбул предлагает насыщенную студенческую жизнь по разумной цене. Комната — 200–350 USD в месяц; общежитие дешевле — 150–250 USD. Продукты — 120–180 USD, студенческий проездной — около 20 USD. Поесть вне дома недорого: 3–6 USD. В целом закладывайте 400–600 USD в месяц.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-07-02',
    coverImage: seedImages.istanbul,
    category: { en: 'Student Life', tr: 'Öğrenci Hayatı', az: 'Tələbə Həyatı', ru: 'Студенческая жизнь' },
    readingMinutes: 5,
  },
  {
    id: 'b-3',
    slug: 'turkiye-burslari-scholarship-guide',
    title: {
      en: 'Türkiye Bursları: The Complete Government Scholarship Guide',
      tr: 'Türkiye Bursları: Kapsamlı Devlet Burs Rehberi',
      az: 'Türkiye Bursları: Tam Dövlət Təqaüd Bələdçisi',
      ru: 'Türkiye Bursları: полное руководство по государственной стипендии',
    },
    excerpt: {
      en: 'Full tuition, accommodation, stipend and health insurance — here is how to win the most coveted scholarship in Turkey.',
      tr: 'Tam ücret, konaklama, burs ve sağlık sigortası — Türkiye\'nin en çok istenen bursunu kazanma rehberi.',
      az: 'Tam tədris haqqı, qalma yeri, təqaüd və sığorta — Türkiyənin ən arzu olunan təqaüdünü qazanmaq üçün bələdçi.',
      ru: 'Полное обучение, проживание, стипендия и страховка — как выиграть самую желанную стипендию Турции.',
    },
    content: {
      en: 'Türkiye Bursları is a competitive government scholarship covering 100% of tuition, monthly stipend, accommodation, health insurance and a Turkish language course. Applications open once a year, usually January–February. Selection is based on academic merit, extracurricular achievements and a letter of intent. Prepare early: gather translated and notarised documents and craft a compelling personal statement highlighting your goals.',
      tr: 'Türkiye Bursları, ücretin %100\'ünü, aylık bursu, konaklamayı, sağlık sigortasını ve Türkçe dil kursunu kapsayan rekabetçi bir devlet bursudur. Başvurular yılda bir kez, genellikle Ocak–Şubat açılır. Seçim akademik başarı, sosyal etkinlikler ve niyet mektubuna dayanır. Erken hazırlanın: çevrilmiş ve onaylı belgeleri toplayın ve hedeflerinizi vurgulayan etkileyici bir kişisel beyan yazın.',
      az: 'Türkiye Bursları tədris haqqının 100%-ni, aylıq təqaüdü, qalma yerini, sığortanı və türkçə dil kursunu əhatə edən rəqabətli dövlət təqaüdüdür. Müraciətlər ildə bir dəfə, adətən Yanvar–Fevralda açılır. Seçim akademik nailiyyət, fəaliyyətlər və niyyət məktubu əsasındadır. Vaxtında hazırlaşın: tərcümə və təsdiq edilmiş sənədləri toplayın və məqsədlərinizi vurğulayan təsirli şəxsi bəyanat yazın.',
      ru: 'Türkiye Bursları — конкурентная государственная стипендия: 100% обучения, ежемесячная выплата, проживание, страховка и курс турецкого. Заявки открывают раз в год, обычно январь–февраль. Отбор — по успеваемости, внеучебным достижениям и письму о намерениях. Готовьтесь заранее: соберите переведённые и заверенные документы и напишите убедительное личное заявление.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-05-20',
    coverImage: seedImages.graduation,
    category: { en: 'Scholarships', tr: 'Burslar', az: 'Təqaüdlər', ru: 'Стипендии' },
    readingMinutes: 7,
  },
  {
    id: 'b-4',
    slug: 'study-journalism-in-turkey',
    title: {
      en: 'Study Journalism in Turkey: Academic Structure, Strategic Planning',
      tr: 'Türkiye\'de Gazetecilik Eğitimi: Akademik Yapı, Stratejik Planlama',
      az: 'Türkiyədə Jurnalistika Təhsili: Akademik Struktur, Strateji Planlama',
      ru: 'Журналистика в Турции: академическая структура, стратегическое планирование',
    },
    excerpt: {
      en: 'Understand the academic structure and strategic planning for studying journalism in Turkey.',
      tr: 'Türkiye\'de gazetecilik eğitimi için akademik yapıyı ve stratejik planlamayı keşfedin.',
      az: 'Türkiyədə jurnalistika təhsili üçün akademik struktur və strateji planlamanı anlayın.',
      ru: 'Академическая структура и стратегическое планирование для изучения журналистики в Турции.',
    },
    content: {
      en: 'Journalism trains you to gather, verify and tell stories that shape public understanding. Turkish programs blend reporting, media ethics, digital production and communication theory across four-year undergraduate degrees. Istanbul, home to major news agencies and broadcasters, offers unmatched internship and networking opportunities. Graduates pursue careers in print, television, digital media, corporate communications and public relations.',
      tr: 'Gazetecilik, kamuoyunu şekillendiren hikayeleri toplama, doğrulama ve anlatma becerisini kazandırır. Türk programları habercilik, medya etiği, dijital üretim ve iletişim teorisini dört yıllık lisans derecelerinde birleştirir. Büyük haber ajanslarına ve yayıncılara ev sahipliği yapan İstanbul, eşsiz staj ve ağ kurma fırsatları sunar. Mezunlar basın, televizyon, dijital medya, kurumsal iletişim ve halkla ilişkilerde kariyer yapar.',
      az: 'Jurnalistika ictimaiyyətin anlayışını formalaşdıran hekayələri toplamaq, yoxlamaq və çatdırmaq bacarığını aşılayır. Türk proqramları xəbərçilik, media etikası, rəqəmsal istehsal və kommunikasiya nəzəriyyəsini dört illik bakalavr dərəcələrində birləşdirir. Əsas xəbər agentliklərinə və yayımçılara ev sahibliyi edən İstanbul, bənzərsiz təcrübə və şəbəkə imkanları təklif edir. Məzunlar mətbuat, televiziya, rəqəmsal media, korporativ kommunikasiya və ictimaiyyətlə əlaqə sahələrində karyera qururlar.',
      ru: 'Журналистика учит собирать, проверять и рассказывать истории, формирующие общественное мнение. Турецкие программы объединяют репортаж, медиаэтику, цифровое производство и теорию коммуникации в четырёхлетних степенях. Стамбул, где расположены крупнейшие агентства и вещатели, даёт уникальные возможности для стажировок и связей. Выпускники работают в печати, на ТВ, в цифровых медиа, корпоративных коммуникациях и PR.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-03-26',
    coverImage: seedImages.arts,
    category: {
      en: 'Communication',
      tr: 'İletişim',
      az: 'Kommunikasiya',
      ru: 'Коммуникации',
    },
    readingMinutes: 6,
  },
  {
    id: 'b-5',
    slug: 'study-mathematics-in-turkey',
    title: {
      en: 'Study Mathematics in Turkey: Education System, Programs',
      tr: 'Türkiye\'de Matematik Eğitimi: Eğitim Sistemi, Programlar',
      az: 'Türkiyədə Riyaziyyat Təhsili: Təhsil Sistemi, Proqramlar',
      ru: 'Математика в Турции: система образования, программы',
    },
    excerpt: {
      en: 'An overview of the education system and mathematics programs offered across Turkey.',
      tr: 'Türkiye genelinde sunulan eğitim sistemi ve matematik programlarına genel bir bakış.',
      az: 'Türkiyə boyu təklif olunan təhsil sistemi və riyaziyyat proqramlarına ümumi baxış.',
      ru: 'Обзор системы образования и математических программ в Турции.',
    },
    content: {
      en: 'Mathematics underpins data science, finance, engineering and cryptography, making it one of the most versatile degrees. Turkish universities such as METU, Boğaziçi and Bilkent offer rigorous undergraduate and graduate programs in pure and applied mathematics. Students develop analytical thinking through courses in algebra, analysis, topology and statistics. Graduates move into research, technology, banking, actuarial science and teaching.',
      tr: 'Matematik; veri bilimi, finans, mühendislik ve kriptografinin temelini oluşturur ve en esnek derecelerden biridir. ODTÜ, Boğaziçi ve Bilkent gibi Türk üniversiteleri saf ve uygulamalı matematikte titiz lisans ve lisansüstü programlar sunar. Öğrenciler cebir, analiz, topoloji ve istatistik dersleriyle analitik düşünme becerisi kazanır. Mezunlar araştırma, teknoloji, bankacılık, aktüerya bilimi ve öğretmenlikte iş bulur.',
      az: 'Riyaziyyat data elminin, maliyyənin, mühəndisliyin və kriptoqrafiyanın əsasını təşkil edir və ən çox yönlü dərəcələrdən biridir. ODTÜ, Boğaziçi və Bilkent kimi türk universitetləri saf və tətbiqi riyaziyyatda ciddi bakalavr və magistr proqramları təklif edir. Tələbələr cəbr, analiz, topologiya və statistika dərsləri ilə analitik düşünmə bacarığı inkişaf etdirir. Məzunlar tədqiqat, texnologiya, bankçılıq, aktüer elmi və müəllimlik sahələrində iş tapırlar.',
      ru: 'Математика лежит в основе data science, финансов, инженерии и криптографии — одна из самых универсальных степеней. Турецкие вузы — ODTÜ, Boğaziçi, Bilkent — предлагают строгие программы чистой и прикладной математики. Студенты развивают аналитическое мышление через алгебру, анализ, топологию и статистику. Выпускники работают в науке, технологиях, банках, актуарной сфере и преподавании.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-03-18',
    coverImage: seedImages.computer,
    category: {
      en: 'Natural Sciences',
      tr: 'Doğa Bilimleri',
      az: 'Təbiət Elmləri',
      ru: 'Естественные науки',
    },
    readingMinutes: 5,
  },
  {
    id: 'b-6',
    slug: 'study-marketing-in-turkey',
    title: {
      en: 'Study Marketing in Turkey: Career Opportunities, Programs',
      tr: 'Türkiye\'de Pazarlama Eğitimi: Kariyer Fırsatları, Programlar',
      az: 'Türkiyədə Marketinq Təhsili: Karyera İmkanları, Proqramlar',
      ru: 'Маркетинг в Турции: карьерные возможности, программы',
    },
    excerpt: {
      en: 'Explore marketing career opportunities and the programs that prepare you for them.',
      tr: 'Pazarlama kariyer fırsatlarını ve sizi onlara hazırlayan programları keşfedin.',
      az: 'Marketinq karyera imkanlarını və sizi onlara hazırlayan proqramları kəşf edin.',
      ru: 'Карьерные возможности в маркетинге и программы, которые к ним готовят.',
    },
    content: {
      en: 'Marketing connects products with people through research, branding, digital strategy and consumer psychology. Turkish business schools offer modern programs in marketing, e-commerce and analytics, often taught in English. Turkey\'s fast-growing economy and booming digital sector create rich opportunities for internships and hands-on projects. Graduates become brand managers, digital marketers, market researchers and entrepreneurs.',
      tr: 'Pazarlama; araştırma, markalaşma, dijital strateji ve tüketici psikolojisiyle ürünleri insanlarla buluşturur. Türk işletme okulları genellikle İngilizce olarak pazarlama, e-ticaret ve analitikte modern programlar sunar. Hızla büyüyen ekonomisi ve gelişen dijital sektörü, staj ve uygulamalı projeler için zengin fırsatlar yaratır. Mezunlar marka müdürü, dijital pazarlamacı, pazar araştırmacısı ve girişimci olur.',
      az: 'Marketinq araşdırma, brendinq, rəqəmsal strategiya və istehlakçı psixologiyası ilə məhsulları insanlarla birləşdirir. Türk biznes məktəbləri adətən ingilis dilində marketinq, e-ticarət və analitikada müasir proqramlar təklif edir. Sürətlə böyüyən iqtisadiyyatı və inkişaf edən rəqəmsal sektoru təcrübə və praktiki layihələr üçün zəngin imkanlar yaradır. Məzunlar brend meneceri, rəqəmsal marketoloq, bazar tədqiqatçısı və sahibkar olurlar.',
      ru: 'Маркетинг соединяет продукты и людей через исследования, брендинг, цифровую стратегию и психологию потребителя. Турецкие бизнес-школы предлагают современные программы на английском языке. Быстрорастущая экономика и цифровой сектор создают много возможностей для стажировок и проектов. Выпускники становятся бренд-менеджерами, digital-маркетологами, исследователями рынка и предпринимателями.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-03-17',
    coverImage: seedImages.business,
    category: {
      en: 'Business',
      tr: 'İşletme',
      az: 'Biznes',
      ru: 'Бизнес',
    },
    readingMinutes: 5,
  },
  {
    id: 'b-7',
    slug: 'study-political-science-in-turkey',
    title: {
      en: 'Study Political Science in Turkey: Programs, Universities',
      tr: 'Türkiye\'de Siyaset Bilimi Eğitimi: Programlar, Üniversiteler',
      az: 'Türkiyədə Siyasət Elmi Təhsili: Proqramlar, Universitetlər',
      ru: 'Политология в Турции: программы, университеты',
    },
    excerpt: {
      en: 'A guide to political science programs and leading universities in Turkey.',
      tr: 'Türkiye\'deki siyaset bilimi programlarına ve önde gelen üniversitelere bir rehber.',
      az: 'Türkiyədəki siyasət elmi proqramlarına və aparıcı universitetlərə bələdçi.',
      ru: 'Гид по программам политологии и ведущим университетам Турции.',
    },
    content: {
      en: 'Political science examines power, governance, international relations and public policy. Turkish universities offer strong programs that benefit from the country\'s unique geopolitical position between Europe, the Middle East and Asia. Coursework covers political theory, comparative politics, diplomacy and research methods. Graduates pursue careers in diplomacy, public administration, NGOs, journalism and academia.',
      tr: 'Siyaset bilimi; güç, yönetişim, uluslararası ilişkiler ve kamu politikasını inceler. Türk üniversiteleri, ülkenin Avrupa, Orta Doğu ve Asya arasındaki benzersiz jeopolitik konumundan yararlanan güçlü programlar sunar. Dersler siyaset teorisi, karşılaştırmalı siyaset, diplomasi ve araştırma yöntemlerini kapsar. Mezunlar diplomasi, kamu yönetimi, sivil toplum, gazetecilik ve akademi alanlarında kariyer yapar.',
      az: 'Siyasət elmi gücü, idarəetməni, beynəlxalq münasibətləri və ictimai siyasəti araşdırır. Türk universitetləri ölkənin Avropa, Yaxın Şərq və Asiya arasındakı unikal geosiyasi mövqeyindən faydalanan güclü proqramlar təklif edir. Dərslər siyasət nəzəriyyəsi, müqayisəli siyasət, diplomatiya və tədqiqat metodlarını əhatə edir. Məzunlar diplomatiya, dövlət idarəetməsi, QHT, jurnalistika və akademiya sahələrində karyera qururlar.',
      ru: 'Политология изучает власть, управление, международные отношения и государственную политику. Турецкие университеты предлагают сильные программы, выигрывающие от геополитического положения между Европой, Ближним Востоком и Азией. Курсы охватывают политическую теорию, сравнительную политику, дипломатию и методы исследования. Выпускники работают в дипломатии, госуправлении, НПО, журналистике и науке.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-03-17',
    coverImage: seedImages.law,
    category: {
      en: 'Social Sciences',
      tr: 'Sosyal Bilimler',
      az: 'Sosial Elmlər',
      ru: 'Общественные науки',
    },
    readingMinutes: 6,
  },
  {
    id: 'b-8',
    slug: 'mechatronics-engineering-in-turkey',
    title: {
      en: 'Mechatronics Engineering in Turkey: Universities, Admission and Study Guide',
      tr: 'Türkiye\'de Mekatronik Mühendisliği: Üniversiteler, Kabul ve Eğitim Rehberi',
      az: 'Türkiyədə Mexatronika Mühəndisliyi: Universitetlər, Qəbul və Təhsil Bələdçisi',
      ru: 'Мехатроника в Турции: университеты, поступление и руководство по обучению',
    },
    excerpt: {
      en: 'Everything on universities, admission requirements and how to study mechatronics engineering in Turkey.',
      tr: 'Türkiye\'de mekatronik mühendisliği okumak için üniversiteler, kabul koşulları ve her şey.',
      az: 'Türkiyədə mexatronika mühəndisliyi oxumaq üçün universitetlər, qəbul tələbləri və hər şey.',
      ru: 'Всё об университетах, требованиях к поступлению и обучении мехатронике в Турции.',
    },
    content: {
      en: 'Mechatronics engineering integrates mechanical, electrical and computer engineering with robotics and control systems. Turkey\'s strong manufacturing base, especially in automotive and automation, makes it an ideal place to study this fast-growing field. Programs combine theory with hands-on lab work, mechatronic design and programming. Graduates work in robotics, automation, automotive, aerospace and smart manufacturing.',
      tr: 'Mekatronik mühendisliği; mekanik, elektrik ve bilgisayar mühendisliğini robotik ve kontrol sistemleriyle birleştirir. Özellikle otomotiv ve otomasyonda güçlü üretim tabanı, Türkiye\'yi bu hızla büyüyen alanı çalışmak için ideal kılar. Programlar teoriyi laboratuvar çalışması, mekatronik tasarım ve programlamayla birleştirir. Mezunlar robotik, otomasyon, otomotiv, havacılık ve akıllı üretimde çalışır.',
      az: 'Mexatronika mühəndisliyi mexaniki, elektrik və kompüter mühəndisliyini robotika və idarəetmə sistemləri ilə birləşdirir. Xüsusilə avtomobil və avtomatikada güclü istehsal bazası Türkiyəni bu sürətlə böyüyən sahəni öyrənmək üçün ideal edir. Proqramlar nəzəriyyəni laboratoriya işi, mexatronika dizaynı və proqramlaşdırma ilə birləşdirir. Məzunlar robotika, avtomatika, avtomobil, aviasiya və ağıllı istehsalda işləyirlər.',
      ru: 'Мехатроника объединяет механику, электронику и программирование с робототехникой и системами управления. Сильная производственная база Турции, особенно в автопроме и автоматизации, делает страну идеальной для этой сферы. Программы сочетают теорию с лабораторной работой и проектированием. Выпускники работают в робототехнике, автоматизации, автопроме, авиации и умном производстве.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-03-16',
    coverImage: seedImages.engineering,
    category: {
      en: 'Engineering',
      tr: 'Mühendislik',
      az: 'Mühəndislik',
      ru: 'Инженерия',
    },
    readingMinutes: 7,
  },
  {
    id: 'b-9',
    slug: 'chemical-engineering-in-turkey',
    title: {
      en: 'Chemical Engineering in Turkey: Chemical Studies, Turkey',
      tr: 'Türkiye\'de Kimya Mühendisliği: Kimya Çalışmaları, Türkiye',
      az: 'Türkiyədə Kimya Mühəndisliyi: Kimya Tədqiqatları, Türkiyə',
      ru: 'Химическая инженерия в Турции: химические исследования, Турция',
    },
    excerpt: {
      en: 'A guide to chemical engineering studies and leading universities in Turkey.',
      tr: 'Türkiye\'de kimya mühendisliği çalışmalarına ve önde gelen üniversitelere bir rehber.',
      az: 'Türkiyədə kimya mühəndisliyi tədqiqatlarına və aparıcı universitetlərə bələdçi.',
      ru: 'Гид по изучению химической инженерии и ведущим университетам Турции.',
    },
    content: {
      en: 'Chemical engineering transforms raw materials into useful products through processes in energy, materials, food and pharmaceuticals. Turkish universities offer programs with strong ties to the country\'s large chemical and manufacturing industries. Students learn thermodynamics, reaction engineering, process design and safety. Graduates pursue roles in petrochemicals, energy, pharma, food processing and environmental engineering.',
      tr: 'Kimya mühendisliği; enerji, malzemeler, gıda ve ilaç alanlarındaki süreçlerle ham maddeleri faydalı ürünlere dönüştürür. Türk üniversiteleri, ülkenin büyük kimya ve imalat sanayisiyle güçlü bağları olan programlar sunar. Öğrenciler termodinamik, reaksiyon mühendisliği, proses tasarımı ve güvenlik öğrenir. Mezunlar petrokimya, enerji, ilaç, gıda işleme ve çevre mühendisliğinde görev alır.',
      az: 'Kimya mühəndisliyi enerji, materiallar, ərzaq və dərman sahələrindəki proseslərlə xammalı faydalı məhsullara çevirir. Türk universitetləri ölkənin böyük kimya və istehsal sənayesi ilə güclü əlaqələri olan proqramlar təklif edir. Tələbələr termodinamika, reaksiya mühəndisliyi, proses dizaynı və təhlükəsizlik öyrənirlər. Məzunlar neft-kimya, enerji, dərman, ərzaq emalı və ekologiya mühəndisliyində işləyirlər.',
      ru: 'Химическая инженерия превращает сырьё в полезные продукты в сферах энергии, материалов, пищи и фармацевтики. Турецкие университеты предлагают программы, тесно связанные с крупной химической промышленностью страны. Студенты изучают термодинамику, реакционную инженерию, проектирование процессов и безопасность. Выпускники работают в нефтехимии, энергетике, фармации, пищевой промышленности и экологии.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-03-16',
    coverImage: seedImages.engineering,
    category: {
      en: 'Engineering',
      tr: 'Mühendislik',
      az: 'Mühəndislik',
      ru: 'Инженерия',
    },
    readingMinutes: 5,
  },
  {
    id: 'b-10',
    slug: 'automotive-engineering-in-turkey',
    title: {
      en: 'Automotive Engineering in Turkey: Automotive Studies, Turkey',
      tr: 'Türkiye\'de Otomotiv Mühendisliği: Otomotiv Çalışmaları, Türkiye',
      az: 'Türkiyədə Avtomobil Mühəndisliyi: Avtomobil Tədqiqatları, Türkiyə',
      ru: 'Автомобильная инженерия в Турции: автотранспортные исследования, Турция',
    },
    excerpt: {
      en: 'A guide to automotive engineering studies and programs available in Turkey.',
      tr: 'Türkiye\'de otomotiv mühendisliği çalışmalarına ve mevcut programlara bir rehber.',
      az: 'Türkiyədə avtomobil mühəndisliyi tədqiqatlarına və mövcud proqramlara bələdçi.',
      ru: 'Гид по изучению автомобильной инженерии и программам в Турции.',
    },
    content: {
      en: 'Automotive engineering covers vehicle design, manufacturing, propulsion systems and the rapidly growing electric vehicle sector. Turkey is one of Europe\'s largest automotive producers, hosting plants for Ford, Toyota, Tofaş and the domestic brand TOGG. Programs blend mechanical engineering with electronics, control systems and sustainable mobility. Graduates find roles in design, manufacturing, R&D and electric vehicle development.',
      tr: 'Otomotiv mühendisliği; araç tasarımı, üretim, tahrik sistemleri ve hızla büyüyen elektrikli araç sektörünü kapsar. Türkiye; Ford, Toyota, Tofaş ve yerli marka TOGG\'nun tesislerine ev sahipliği yapan Avrupa\'nın en büyük otomotiv üreticilerinden biridir. Programlar mekanik mühendisliği elektronik, kontrol sistemleri ve sürdürülebilir mobiliteyle birleştirir. Mezunlar tasarım, üretim, Ar-Ge ve elektrikli araç geliştirmede görev alır.',
      az: 'Avtomobil mühəndisliyi nəqliyyat vasitəsi dizaynı, istehsal, hərəkətverici sistemlər və sürətlə böyüyən elektrikli nəqliyyat vasitəsi sektorunu əhatə edir. Türkiyə Ford, Toyota, Tofaş və yerli marka TOGG-un təsislərinə ev sahibliyi edən Avropanın ən böyük avtomobil istehsalçılarından biridir. Proqramlar mexaniki mühəndisliyi elektronika, idarəetmə sistemləri və davamlı mobilliklə birləşdirir. Məzunlar dizayn, istehsal, AR və elektrikli nəqliyyat vasitəsi inkişafında iş tapırlar.',
      ru: 'Автомобильная инженерия охватывает проектирование, производство, двигатели и быстрорастущий сектор электромобилей. Турция — один из крупнейших автопроизводителей Европы, здесь заводы Ford, Toyota, Tofaş и местный бренд TOGG. Программы сочетают механику с электроникой, системами управления и устойчивой мобильностью. Выпускники работают в дизайне, производстве, НИОКР и разработке электромобилей.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-03-16',
    coverImage: seedImages.engineering,
    category: {
      en: 'Engineering',
      tr: 'Mühendislik',
      az: 'Mühəndislik',
      ru: 'Инженерия',
    },
    readingMinutes: 6,
  },
  {
    id: 'b-11',
    slug: 'dental-prosthetics-education-in-turkey',
    title: {
      en: 'Dental Prosthetics Education in Turkey: Training Structure; Career Options',
      tr: 'Türkiye\'de Diş Protezi Eğitimi: Eğitim Yapısı; Kariyer Seçenekleri',
      az: 'Türkiyədə Diş Protezi Təhsili: Təlim Strukturu; Karyera Seçimləri',
      ru: 'Образование в области зубного протезирования в Турции: структура обучения; карьерные варианты',
    },
    excerpt: {
      en: 'An overview of dental prosthetics training structure and the career options it opens up.',
      tr: 'Diş protezi eğitim yapısına ve açtığı kariyer seçeneklerine genel bir bakış.',
      az: 'Diş protezi təlim strukturuna və açdığı karyera seçimlərinə ümumi baxış.',
      ru: 'Структура обучения зубному протезированию и открываемые карьерные варианты.',
    },
    content: {
      en: 'Dental prosthetics trains technicians to design and fabricate crowns, bridges, dentures and implant-supported restorations. Turkish vocational schools and universities offer two-year associate and four-year undergraduate programs with extensive laboratory practice. The country\'s booming dental tourism industry increases demand for skilled technicians. Graduates work in dental laboratories, clinics, hospitals or open their own labs.',
      tr: 'Diş protezi eğitimi; teknisyenlere kuron, köprü, protez ve implant destekli restorasyonları tasarlamayı ve üretmeyi öğretir. Türk meslek okulları ve üniversiteleri kapsamlı laboratuvar uygulamalı iki yıllık önlisans ve dört yıllık lisans programları sunar. Ülkenin büyüyen diş turizmi sektörü, nitelikli teknisyenlere talebi artırır. Mezunlar diş laboratuvarlarında, kliniklerde, hastanelerde çalışır veya kendi laboratuvarlarını açar.',
      az: 'Diş protezi təhsili texniklərə korona, körpü, protez və implant dəstəkli restorasiyaları dizayn etməyi və istehsal etməyi öyrədir. Türk peşə məktəbləri və universitetləri geniş laboratoriya təcrübəli iki illik texniki və dört illik bakalavr proqramları təklif edir. Ölkənin böyüyən diş turizmi sektoru bacarıqlı texniklərə tələbi artırır. Məzunlar diş laboratoriyalarında, klinikalarda, xəstəxanalarda işləyir və ya öz laboratoriyalarını açırlar.',
      ru: 'Зубное протезирование обучает техников создавать коронки, мосты, протезы и имплантные реставрации. Турецкие колледжи и университеты предлагают двух- и четырёхлетние программы с обширной лабораторной практикой. Растущий стоматологический туризм увеличивает спрос на квалифицированных техников. Выпускники работают в зуботехнических лабораториях, клиниках, больницах или открывают свои лаборатории.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-03-16',
    coverImage: seedImages.dentistry,
    category: {
      en: 'Dentistry',
      tr: 'Diş Hekimliği',
      az: 'Stomatologiya',
      ru: 'Стоматология',
    },
    readingMinutes: 4,
  },
  {
    id: 'b-12',
    slug: 'masters-in-civil-engineering-in-turkey',
    title: {
      en: 'Master\'s in Civil Engineering in Turkey: Engineering Masters, Civil Studies',
      tr: 'Türkiye\'de İnşaat Mühendisliği Yüksek Lisans: Mühendislik Yüksek Lisansı, İnşaat Çalışmaları',
      az: 'Türkiyədə Mülki Mühəndislik Magistraturası: Mühəndislik Magistrı, Mülki Tədqiqatlar',
      ru: 'Магистратура по гражданской инженерии в Турции: инженерная магистратура, гражданское строительство',
    },
    excerpt: {
      en: 'A guide to engineering master\'s programs and civil engineering studies in Turkey.',
      tr: 'Türkiye\'de mühendislik yüksek lisans programlarına ve inşaat çalışmalarına bir rehber.',
      az: 'Türkiyədə mühəndislik magistr proqramlarına və mülki tədqiqatlara bələdçi.',
      ru: 'Гид по инженерным магистратурам и гражданскому строительству в Турции.',
    },
    content: {
      en: 'A master\'s in civil engineering deepens expertise in structural, geotechnical, transportation and construction management. Turkey\'s massive infrastructure sector and seismic engineering challenges create exceptional learning and research opportunities. Graduate programs combine advanced coursework with thesis research and industry collaboration. Graduates advance as structural engineers, project managers, consultants and academics.',
      tr: 'İnşaat mühendisliği yüksek lisansı; yapısal, geoteknik, ulaşım ve inşaat yönetimi alanlarında uzmanlığı derinleştirir. Türkiye\'nin dev altyapı sektörü ve sismik mühendislik zorlukları olağanüstü öğrenim ve araştırma fırsatları yaratır. Lisansüstü programlar ileri dersleri tez araştırması ve sanayi işbirliğiyle birleştirir. Mezunlar yapı mühendisi, proje yöneticisi, danışman ve akademisyen olarak ilerler.',
      az: 'Mülki mühəndislik magistraturası struktur, geotexniki, nəqliyyat və tikinti idarəetməsi sahələrində ekspertizanı dərinləşdirir. Türkiyənin nəhəng infrastruktur sektoru və seysmik mühəndislik çağırışları müstəsna öyrənmə və tədqiqat imkanları yaradır. Magistr proqramları qabaqcıl dərsləri tezis tədqiqatı və sənaye əməkdaşlığı ilə birləşdirir. Məzunlar struktur mühəndisi, layihə meneceri, məsləhətçi və akademik kimi inkişaf edirlər.',
      ru: 'Магистратура по гражданской инженерии углубляет знания в строительных, геотехнических, транспортных конструкциях и управлении стройкой. Огромный инфраструктурный сектор и сейсмические задачи Турции создают исключительные возможности. Программы сочетают продвинутые курсы с научной работой и сотрудничеством с индустрией. Выпускники работают инженерами-конструкторами, руководителями проектов, консультантами и преподавателями.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-03-14',
    coverImage: seedImages.architecture,
    category: {
      en: 'Engineering',
      tr: 'Mühendislik',
      az: 'Mühəndislik',
      ru: 'Инженерия',
    },
    readingMinutes: 6,
  },
  {
    id: 'b-13',
    slug: 'study-international-trade-in-turkey',
    title: {
      en: 'Study International Trade in Turkey: Programs, Opportunities',
      tr: 'Türkiye\'de Uluslararası Ticaret Eğitimi: Programlar, Fırsatlar',
      az: 'Türkiyədə Beynəlxalq Ticarət Təhsili: Proqramlar, İmkanlar',
      ru: 'Международная торговля в Турции: программы, возможности',
    },
    excerpt: {
      en: 'Discover international trade programs and the opportunities they create in Turkey.',
      tr: 'Uluslararası ticaret programlarını ve Türkiye\'de yarattıkları fırsatları keşfedin.',
      az: 'Beynəlxalq ticarət proqramlarını və Türkiyədə yaratdıqları imkanları kəşf edin.',
      ru: 'Программы международной торговли и возможности, которые они создают в Турции.',
    },
    content: {
      en: 'International trade covers import-export operations, logistics, customs, finance and global supply chain management. Turkey\'s strategic location between Europe, Asia and the Middle East makes it a natural trade hub and living classroom. Programs blend economics, business law, logistics and foreign languages with practical case studies. Graduates work as trade specialists, logistics managers, customs brokers and export executives.',
      tr: 'Uluslararası ticaret; ithalat-ihracat operasyonlarını, lojistiği, gümrüğü, finansı ve küresel tedarik zinciri yönetimini kapsar. Türkiye\'nin Avrupa, Asya ve Orta Doğu arasındaki stratejik konumu, onu doğal bir ticaret merkezi ve yaşayan bir sınıf yapar. Programlar ekonomiyi, iş hukukunu, lojistiği ve yabancı dilleri pratik vakalarla birleştirir. Mezunlar ticaret uzmanı, lojistik müdürü, gümrük müşaviri ve ihracat yöneticisi olarak çalışır.',
      az: 'Beynəlxalq ticarət idxal-ihracat əməliyyatlarını, logistanı, gömrüyü, maliyyəni və qlobal təchizat zənciri idarəetməsini əhatə edir. Türkiyənin Avropa, Asiya və Yaxın Şərq arasındakı strateji mövqeyi onu təbii ticarət mərkəzi və canlı sinif edir. Proqramlar iqtisadiyyatı, biznes hüququnu, logistanı və xarici dilləri praktiki nümunələrlə birləşdirir. Məzunlar ticarət mütəxəssisi, logistika meneceri, gömrük məsləhətçisi və ixracat icraçısı kimi işləyirlər.',
      ru: 'Международная торговля охватывает импорт-экспорт, логистику, таможню, финансы и управление глобальными цепочками поставок. Стратегическое положение Турции между Европой, Азией и Ближним Востоком делает её торговым хабом и живой аудиторией. Программы сочетают экономику, бизнес-право, логистику и иностранные языки с практическими кейсами. Выпускники работают специалистами по торговле, логистами, таможенными брокерами и руководителями экспорта.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-03-16',
    coverImage: seedImages.business,
    category: {
      en: 'Business',
      tr: 'İşletme',
      az: 'Biznes',
      ru: 'Бизнес',
    },
    readingMinutes: 5,
  },
  {
    id: 'b-14',
    slug: 'masters-in-biomedical-engineering-in-turkey',
    title: {
      en: 'Master\'s in Biomedical Engineering in Turkey: Programs, Universities',
      tr: 'Türkiye\'de Biyomedikal Mühendisliği Yüksek Lisans: Programlar, Üniversiteler',
      az: 'Türkiyədə Biotibbi Mühəndislik Magistraturası: Proqramlar, Universitetlər',
      ru: 'Магистратура по биомедицинской инженерии в Турции: программы, университеты',
    },
    excerpt: {
      en: 'A guide to biomedical engineering master\'s programs and universities in Turkey.',
      tr: 'Türkiye\'de biyomedikal mühendisliği yüksek lisans programlarına ve üniversitelere bir rehber.',
      az: 'Türkiyədə biotibbi mühəndislik magistr proqramlarına və universitetlərə bələdçi.',
      ru: 'Гид по магистратурам биомедицинской инженерии и университетам Турции.',
    },
    content: {
      en: 'Biomedical engineering applies engineering principles to medicine, creating medical devices, imaging systems and biomaterials. Turkey\'s growing healthcare sector and medical technology industry offer strong research environments for graduate students. Master\'s programs cover medical imaging, biomechanics, tissue engineering and instrumentation with lab-based research. Graduates work in MedTech companies, hospitals, research institutes and regulatory agencies.',
      tr: 'Biyomedikal mühendisliği; mühendislik ilkelerini tıbba uygulayarak tıbbi cihazlar, görüntüleme sistemleri ve biyomalzemeler yaratır. Türkiye\'nin büyüyen sağlık sektörü ve medikal teknoloji sanayisi, lisansüstü öğrenciler için güçlü araştırma ortamları sunar. Yüksek lisans programları tıbbi görüntüleme, biyomekanik, doku mühendisliği ve enstrümantasyonu laboratuvar tabanlı araştırmayla kapsar. Mezunlar medikal teknoloji şirketlerinde, hastanelerde, araştırma enstitülerinde ve düzenleyici kurumlarda çalışır.',
      az: 'Biotibbi mühəndislik mühəndislik prinsiplərini təbabətə tətbiq edərək tibbi cihazlar, görüntüləmə sistemləri və biomateriallar yaradır. Türkiyənin böyüyən səhiyyə sektoru və tibbi texnologiya sənayesi magistr tələbələri üçün güclü tədqiqat mühitləri təklif edir. Magistr proqramları tibbi görüntüləmə, biotexanika, toxuma mühəndisliyi və cihazqurmaya laboratoriya əsaslı tədqiqatla birlikdə əhatə edir. Məzunlar tibbi texnologiya şirkətlərində, xəstəxanalarda, tədqiqat institutlarında və tənzimləyici qurumlarda işləyirlər.',
      ru: 'Биомедицинская инженерия применяет инженерные принципы в медицине, создавая медицинские приборы, системы визуализации и биоматериалы. Растущий сектор здравоохранения и медтехники Турции даёт сильную среду для исследований. Магистратура охватывает визуализацию, биомеханику, тканевую инженерию и приборостроение с лабораторной работой. Выпускники работают в компаниях медтехники, больницах, НИИ и регулирующих органах.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-03-13',
    coverImage: seedImages.medicine,
    category: {
      en: 'Engineering',
      tr: 'Mühendislik',
      az: 'Mühəndislik',
      ru: 'Инженерия',
    },
    readingMinutes: 7,
  },
  {
    id: 'b-15',
    slug: 'masters-of-business-administration-in-turkey',
    title: {
      en: 'Master\'s of Business Administration in Turkey: Universities, Program Types',
      tr: 'Türkiye\'de İşletme Yönetimi Yüksek Lisansı (MBA): Üniversiteler, Program Türleri',
      az: 'Türkiyədə Biznes İdarəetmə Magistraturası (MBA): Universitetlər, Proqram Növləri',
      ru: 'Магистратура MBA в Турции: университеты, типы программ',
    },
    excerpt: {
      en: 'An overview of MBA universities and the program types available in Turkey.',
      tr: 'MBA üniversitelerine ve Türkiye\'de mevcut program türlerine genel bir bakış.',
      az: 'MBA universitetlərinə və Türkiyədə mövcud proqram növlərinə ümumi baxış.',
      ru: 'Обзор университетов MBA и типов программ в Турции.',
    },
    content: {
      en: 'An MBA builds leadership, strategy, finance and management skills for ambitious professionals and entrepreneurs. Turkish universities offer full-time, part-time, executive and online MBAs, many taught fully in English. Programs combine case studies, projects and networking with Turkey\'s dynamic business community. Graduates advance to executive roles, consulting, finance or launch their own ventures.',
      tr: 'MBA; hırslı profesyoneller ve girişimciler için liderlik, strateji, finans ve yönetim becerileri oluşturur. Türk üniversiteleri tam zamanlı, yarı zamanlı, yönetici ve çevrimiçi MBA\'ler sunar; birçoğu tamamen İngilizcedir. Programlar vaka çalışmaları, projeler ve Türkiye\'nin dinamik iş topluluğuyla ağ kurmayı birleştirir. Mezunlar yönetici pozisyonlara, danışmanlığa, finans alanına ilerler veya kendi işlerini kurar.',
      az: 'MBA iddialı peşəkarlar və sahibkarlar üçün liderlik, strategiya, maliyyə və idarəetmə bacarıqları qurur. Türk universitetləri tam ştat, yarım ştat, icraçı və onlayn MBA-lar təklif edir; bir çoxu tamamilə ingilis dilindədir. Proqramlar hal tədqiqatlarını, layihələri və Türkiyənin dinamik biznes icması ilə şəbəkə qurmanı birləşdirir. Məzunlar icraçı rollara, məsləhətçiliyə, maliyyə sahəsinə irəliləyir və ya öz bizneslərini qururlar.',
      ru: 'MBA развивает лидерство, стратегию, финансы и управление для амбициозных специалистов и предпринимателей. Турецкие университеты предлагают очные, заочные, executive и онлайн-программы, многие — на английском. Программы сочетают кейсы, проекты и нетворкинг с турецким бизнес-сообществом. Выпускники занимают руководящие посты, работают в консалтинге, финансах или открывают своё дело.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-03-13',
    coverImage: seedImages.business,
    category: {
      en: 'Business',
      tr: 'İşletme',
      az: 'Biznes',
      ru: 'Бизнес',
    },
    readingMinutes: 6,
  },
  {
    id: 'b-16',
    slug: 'masters-in-pharmacy-in-turkey',
    title: {
      en: 'Master\'s in Pharmacy in Turkey: Pharmacy Programs, Turkey',
      tr: 'Türkiye\'de Eczacılık Yüksek Lisans: Eczacılık Programları, Türkiye',
      az: 'Türkiyədə Əczaçılıq Magistraturası: Əczaçılıq Proqramları, Türkiyə',
      ru: 'Магистратура по фармации в Турции: фармакологические программы, Турция',
    },
    excerpt: {
      en: 'A guide to pharmacy master\'s programs and study options in Turkey.',
      tr: 'Eczacılık yüksek lisans programlarına ve Türkiye\'deki eğitim seçeneklerine bir rehber.',
      az: 'Əczaçılıq magistr proqramlarına və Türkiyədəki təhsil seçimlərinə bələdçi.',
      ru: 'Гид по магистратурам фармации и вариантам обучения в Турции.',
    },
    content: {
      en: 'A master\'s in pharmacy advances knowledge in pharmaceutics, pharmacology, clinical pharmacy and drug development. Turkey has a strong pharmaceutical industry and growing research output, making it an attractive destination for graduate study. Programs combine advanced coursework with laboratory research and clinical practice. Graduates work in pharma R&D, hospitals, regulatory affairs, academia and the biotechnology sector.',
      tr: 'Eczacılık yüksek lisansı; farmasötik, farmakoloji, klinik eczacılık ve ilaç geliştirme alanlarında bilgiyi ilerletir. Türkiye, güçlü bir farmasötik sanayisine ve büyüyen araştırma çıktısına sahiptir ve bu da onu lisansüstü eğitim için çekici kılar. Programlar ileri dersleri laboratuvar araştırması ve klinik uygulamayla birleştirir. Mezunlar ilaç Ar-Ge\'sinde, hastanelerde, düzenleyici işlerde, akademide ve biyoteknoloji sektöründe çalışır.',
      az: 'Əczaçılıq magistraturası farmasevtika, farmakologiya, kliniki əczaçılıq və dərman inkişafı sahələrində bilikləri irəliyə aparır. Türkiyə güclü əczaçılıq sənayesinə və böyüyən tədqiqat məhsuldarlığına malikdir və bu onu magistr təhsili üçün cəzbedici edir. Proqramlar qabaqcıl dərsləri laboratoriya tədqiqatı və kliniki təcrübə ilə birləşdirir. Məzunlar dərman AR, xəstəxanalarda, tənzimləyici işlərdə, akademiyada və biotexnologiya sektorunda işləyirlər.',
      ru: 'Магистратура по фармации углубляет знания в фармацевтике, фармакологии, клинической фармации и разработке лекарств. В Турции сильная фармпромышленность и растущая научная продуктивность. Программы сочетают продвинутые курсы с лабораторными исследованиями и клинической практикой. Выпускники работают в фарм НИОКР, больницах, регуляторных органах, науке и биотехе.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-03-13',
    coverImage: seedImages.medicine,
    category: {
      en: 'Health Sciences',
      tr: 'Sağlık Bilimleri',
      az: 'Sağlamlıq Elmləri',
      ru: 'Медицинские науки',
    },
    readingMinutes: 5,
  },
  {
    id: 'b-17',
    slug: 'study-history-in-turkey',
    title: {
      en: 'Study History in Turkey: Offering Programs, Career Opportunities',
      tr: 'Türkiye\'de Tarih Eğitimi: Sunulan Programlar, Kariyer Fırsatları',
      az: 'Türkiyədə Tarix Təhsili: Təklif Olunan Proqramlar, Karyera İmkanları',
      ru: 'История в Турции: программы, карьерные возможности',
    },
    excerpt: {
      en: 'Explore history programs on offer and the career opportunities they lead to.',
      tr: 'Sunulan tarih programlarını ve ulaştıkları kariyer fırsatlarını keşfedin.',
      az: 'Təklif olunan tarix proqramlarını və onların apardığı karyera imkanlarını kəşf edin.',
      ru: 'Программы истории и карьерные возможности, к которым они ведут.',
    },
    content: {
      en: 'Studying history in Turkey means learning among the living legacy of Byzantine, Ottoman, Seljuk and ancient Anatolian civilizations. Universities in Istanbul, Ankara and Izmir offer rich archives, museums and archaeological sites for hands-on research. Programs cover Turkish, Islamic, European and world history with strong training in historical methods. Graduates pursue careers in academia, museums, archives, heritage management, publishing and teaching.',
      tr: 'Türkiye\'de tarih eğitimi; Bizans, Osmanlı, Selçuklu ve antik Anadolu medeniyetlerinin yaşayan mirası arasında öğrenmek demektir. İstanbul, Ankara ve İzmir\'deki üniversiteler uygulamalı araştırma için zengin arşivler, müzeler ve arkeolojik alanlar sunar. Programlar Türk, İslam, Avrupa ve dünya tarihini tarihsel yöntemler eğitimiyle kapsar. Mezunlar akademi, müzeler, arşivler, miras yönetimi, yayıncılık ve öğretmenlikte kariyer yapar.',
      az: 'Türkiyədə tarix təhsili Bizans, Osmanlı, Səlcuqlu və qədim Anadolu sivilizasiyalarının yaşayan irsi arasında öyrənmək deməkdir. İstanbul, Ankara və İzmirdəki universitetlər praktiki tədqiqat üçün zəngin arxivlər, muzeylər və arxeoloji sahələr təklif edir. Proqramlar türk, islam, avropa və dünya tarixini tarixi metodlar təlimi ilə əhatə edir. Məzunlar akademiya, muzeylər, arxivlər, irs idarəetməsi, nəşriyyat və müəllimlikdə karyera qururlar.',
      ru: 'Изучение истории в Турции — это обучение среди наследия Византии, Османской империи, Сельджуков и древних анатолийских цивилизаций. Университеты Стамбула, Анкары и Измира предлагают архивы, музеи и археологические площадки. Программы охватывают турецкую, исламскую, европейскую и всемирную историю с сильной методологической подготовкой. Выпускники работают в науке, музеях, архивах, управлении наследием, издательстве и преподавании.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-03-13',
    coverImage: seedImages.istanbul,
    category: {
      en: 'Humanities',
      tr: 'Beşeri Bilimler',
      az: 'Humanitar Elmlər',
      ru: 'Гуманитарные науки',
    },
    readingMinutes: 6,
  },
  {
    id: 'b-18',
    slug: 'literature-faculties-in-turkey',
    title: {
      en: 'Literature Faculties in Turkey: Literary Programs, Turkey',
      tr: 'Türkiye\'de Edebiyat Fakülteleri: Edebi Programlar, Türkiye',
      az: 'Türkiyədə Ədəbiyyat Fakültələri: Ədəbi Proqramlar, Türkiyə',
      ru: 'Литературные факультеты в Турции: литературные программы, Турция',
    },
    excerpt: {
      en: 'A guide to literary programs and literature faculties across Turkey.',
      tr: 'Türkiye genelindeki edebi programlara ve edebiyat fakültelerine bir rehber.',
      az: 'Türkiyə boyu ədəbi proqramlara və ədəbiyyat fakültələrinə bələdçi.',
      ru: 'Гид по литературным программам и факультетам Турции.',
    },
    content: {
      en: 'Turkish literature faculties offer programs in Turkish language and literature, comparative literature, English and world literatures. Studying in Turkey gives access to a rich literary tradition shaped by figures like Orhan Pamuk, Nazım Hikmet and Yaşar Kemal. Programs develop critical thinking, textual analysis and creative writing across genres and periods. Graduates work in publishing, media, education, translation, cultural organizations and academia.',
      tr: 'Türk edebiyat fakülteleri; Türk dili ve edebiyatı, karşılaştırmalı edebiyat, İngiliz ve dünya edebiyatı programları sunar. Türkiye\'de eğitim; Orhan Pamuk, Nazım Hikmet ve Yaşar Kemal gibi isimlerle şekillenmiş zengin bir edebi geleneğe erişim sağlar. Programlar türler ve dönemler boyunca eleştirel düşünce, metin analizi ve yaratıcı yazım geliştirir. Mezunlar yayıncılık, medya, eğitim, çeviri, kültür kuruluşları ve akademide çalışır.',
      az: 'Türk ədəbiyyat fakültələri türk dili və ədəbiyyatı, müqayisəli ədəbiyyat, ingilis və dünya ədəbiyyatı proqramları təklif edir. Türkiyədə təhsil Orhan Pamuk, Nizam Hikmət və Yaşar Kəmal kimi simalarla formalaşmış zəngin ədəbi ənənəyə çıxış təmin edir. Proqramlar janrlar və dövrlər boyu tənqidi düşüncə, mətn təhlili və yaradıcı yazı inkişaf etdirir. Məzunlar nəşriyyat, media, təhsil, tərcümə, mədəni təşkilatlar və akademiyada işləyirlər.',
      ru: 'Турецкие литературные факультеты предлагают программы по турецкому языку и литературе, сравнительному литературоведению, английской и мировой литературе. Обучение в Турции даёт доступ к богатой традиции, сформированной Орханом Памуком, Назымом Хикметом и Яшаром Кемалом. Программы развивают критическое мышление, анализ текста и творческое письмо. Выпускники работают в издательстве, медиа, образовании, переводе, культуре и науке.',
    },
    author: 'StudyHub Team',
    publishedAt: '2026-03-13',
    coverImage: seedImages.campusLibrary,
    category: {
      en: 'Humanities',
      tr: 'Beşeri Bilimler',
      az: 'Humanitar Elmlər',
      ru: 'Гуманитарные науки',
    },
    readingMinutes: 5,
  },
];
