import type { City } from '@/types';

export const seedCities: City[] = [
  {
    id: 'c-istanbul',
    slug: 'istanbul',
    countryId: 'TR',
    monthlyLivingCostUSD: 700,
    name: {
      en: 'Istanbul', tr: 'İstanbul', az: 'İstanbul', ru: 'Стамбул',
      de: 'Istanbul', fr: 'Istanbul', fa: 'استانبول', ar: 'إسطنبول',
      tk: 'Stambul', kk: 'Ыстамбұл', ky: 'Стамбул', zh: '伊斯坦布尔',
      bg: 'Истанбул', ur: 'استنبول', uz: 'Istanbul', sw: 'Istanbul',
      so: 'Istanbul', id: 'Istanbul',
    },
  },
  {
    id: 'c-ankara',
    slug: 'ankara',
    countryId: 'TR',
    monthlyLivingCostUSD: 450,
    name: {
      en: 'Ankara', tr: 'Ankara', az: 'Ankara', ru: 'Анкара',
      de: 'Ankara', fr: 'Ankara', fa: 'آنکارا', ar: 'أنقرة',
      tk: 'Ankara', kk: 'Анкара', ky: 'Анкара', zh: '安卡拉',
      bg: 'Анкара', ur: 'انقرہ', uz: 'Ankara', sw: 'Ankara',
      so: 'Ankara', id: 'Ankara',
    },
  },
  {
    id: 'c-izmir',
    slug: 'izmir',
    countryId: 'TR',
    monthlyLivingCostUSD: 500,
    name: {
      en: 'Izmir', tr: 'İzmir', az: 'İzmir', ru: 'Измир',
      de: 'Izmir', fr: 'Izmir', fa: 'ازمیر', ar: 'إزمير',
      tk: 'Izmir', kk: 'Измир', ky: 'Измир', zh: '伊兹密尔',
      bg: 'Измир', ur: 'ازمیر', uz: 'Izmir', sw: 'Izmir',
      so: 'Izmir', id: 'Izmir',
    },
  },
  {
    id: 'c-bursa',
    slug: 'bursa',
    countryId: 'TR',
    monthlyLivingCostUSD: 350,
    name: {
      en: 'Bursa', tr: 'Bursa', az: 'Bursa', ru: 'Бурса',
      de: 'Bursa', fr: 'Brousse', fa: 'بورسا', ar: 'بورصة',
      tk: 'Bursa', kk: 'Бурса', ky: 'Бурса', zh: '布尔萨',
      bg: 'Бурса', ur: 'بورصہ', uz: 'Bursa', sw: 'Bursa',
      so: 'Bursa', id: 'Bursa',
    },
  },
  {
    id: 'c-antalya',
    slug: 'antalya',
    countryId: 'TR',
    monthlyLivingCostUSD: 400,
    name: {
      en: 'Antalya', tr: 'Antalya', az: 'Antalya', ru: 'Анталья',
      de: 'Antalya', fr: 'Antalya', fa: 'آنتالیا', ar: 'أنطاليا',
      tk: 'Antalya', kk: 'Анталия', ky: 'Анталья', zh: '安塔利亚',
      bg: 'Анталия', ur: 'انطالیہ', uz: 'Antalya', sw: 'Antalya',
      so: 'Antalya', id: 'Antalya',
    },
  },
  {
    id: 'c-konya',
    slug: 'konya',
    countryId: 'TR',
    monthlyLivingCostUSD: 300,
    name: {
      en: 'Konya', tr: 'Konya', az: 'Konya', ru: 'Конья',
      de: 'Konya', fr: 'Konya', fa: 'قونیه', ar: 'قونية',
      tk: 'Konya', kk: 'Конья', ky: 'Конья', zh: '科尼亚',
      bg: 'Кония', ur: 'قونیہ', uz: 'Konya', sw: 'Konya',
      so: 'Konya', id: 'Konya',
    },
  },
  {
    id: 'c-trabzon',
    slug: 'trabzon',
    countryId: 'TR',
    monthlyLivingCostUSD: 320,
    name: {
      en: 'Trabzon', tr: 'Trabzon', az: 'Trabzon', ru: 'Трабзон',
      de: 'Trabzon', fr: 'Trabzon', fa: 'ترابزون', ar: 'طرابزون',
      tk: 'Trabzon', kk: 'Трабзон', ky: 'Трабзон', zh: '特拉布宗',
      bg: 'Трабзон', ur: 'ترابزون', uz: 'Trabzon', sw: 'Trabzon',
      so: 'Trabzon', id: 'Trabzon',
    },
  },
  {
    id: 'c-mersin',
    slug: 'mersin',
    countryId: 'TR',
    monthlyLivingCostUSD: 280,
    name: {
      en: 'Mersin', tr: 'Mersin', az: 'Mersin', ru: 'Мерсин',
      de: 'Mersin', fr: 'Mersin', fa: 'مرسین', ar: 'مرسين',
      tk: 'Mersin', kk: 'Мерсин', ky: 'Мерсин', zh: '梅尔辛',
      bg: 'Мерсин', ur: 'مرسین', uz: 'Mersin', sw: 'Mersin',
      so: 'Mersin', id: 'Mersin',
    },
  },
  {
    id: 'c-gaziantep',
    slug: 'gaziantep',
    countryId: 'TR',
    monthlyLivingCostUSD: 250,
    name: {
      en: 'Gaziantep', tr: 'Gaziantep', az: 'Qəzziantəp', ru: 'Газиантеп',
      de: 'Gaziantep', fr: 'Gaziantep', fa: 'غازی عینتاب', ar: 'غازي عنتاب',
      tk: 'Gaziantep', kk: 'Газиантеп', ky: 'Газиантеп', zh: '加济安泰普',
      bg: 'Газиантеп', ur: 'غازی عینتاب', uz: 'Gaziantep', sw: 'Gaziantep',
      so: 'Gaziantep', id: 'Gaziantep',
    },
  },
  {
    id: 'c-kayseri',
    slug: 'kayseri',
    countryId: 'TR',
    monthlyLivingCostUSD: 280,
    name: {
      en: 'Kayseri', tr: 'Kayseri', az: 'Kayseri', ru: 'Кайсери',
      de: 'Kayseri', fr: 'Kayseri', fa: 'قیصریه', ar: 'قيصري',
      tk: 'Kayseri', kk: 'Кайсери', ky: 'Кайсери', zh: '开塞利',
      bg: 'Кайсери', ur: 'قیصری', uz: 'Kayseri', sw: 'Kayseri',
      so: 'Kayseri', id: 'Kayseri',
    },
  },
  {
    id: 'c-nevsehir',
    slug: 'nevsehir',
    countryId: 'TR',
    monthlyLivingCostUSD: 250,
    name: {
      en: 'Nevsehir', tr: 'Nevşehir', az: 'Nevşəhər', ru: 'Невшехир',
      de: 'Nevşehir', fr: 'Nevşehir', fa: 'نوشهر', ar: 'نوشهر',
      tk: 'Nevşehir', kk: 'Невшехир', ky: 'Невшехир', zh: '内夫谢希尔',
      bg: 'Невшехир', ur: 'نو شہر', uz: 'Nevşehir', sw: 'Nevsehir',
      so: 'Nevsehir', id: 'Nevsehir',
    },
  },
  {
    id: 'c-kocaeli',
    slug: 'kocaeli',
    countryId: 'TR',
    monthlyLivingCostUSD: 330,
    name: {
      en: 'Kocaeli', tr: 'Kocaeli', az: 'Kocaeli', ru: 'Коджаэли',
      de: 'Kocaeli', fr: 'Kocaeli', fa: 'قوجا ایلی', ar: 'قوجه ايلي',
      tk: 'Kocaeli', kk: 'Коджаэли', ky: 'Коджаэли', zh: '科贾埃利',
      bg: 'Коджаели', ur: 'کوجائلی', uz: 'Kocaeli', sw: 'Kocaeli',
      so: 'Kocaeli', id: 'Kocaeli',
    },
  },
  {
    id: 'c-alanya',
    slug: 'alanya',
    countryId: 'TR',
    monthlyLivingCostUSD: 400,
    name: {
      en: 'Alanya', tr: 'Alanya', az: 'Alaniya', ru: 'Аланья',
      de: 'Alanya', fr: 'Alanya', fa: 'آلانیا', ar: 'ألانيا',
      tk: 'Alanya', kk: 'Алания', ky: 'Алания', zh: '阿拉尼亚',
      bg: 'Алания', ur: 'آلانیا', uz: 'Alanya', sw: 'Alanya',
      so: 'Alanya', id: 'Alanya',
    },
  },
];
