import type { Country } from '@/types';

export const seedCountries: Country[] = [
  // === Existing (priority — source markets) ===
  { code: 'AZ', slug: 'azerbaijan', flag: '🇦🇿', name: { en: 'Azerbaijan', tr: 'Azerbaycan', az: 'Azərbaycan', ru: 'Азербайджан' } },
  { code: 'UZ', slug: 'uzbekistan', flag: '🇺🇿', name: { en: 'Uzbekistan', tr: 'Özbekistan', az: 'Özbəkistan', ru: 'Узбекистан' } },
  { code: 'RU', slug: 'russia', flag: '🇷🇺', name: { en: 'Russia', tr: 'Rusya', az: 'Rusiya', ru: 'Россия' } },
  { code: 'KZ', slug: 'kazakhstan', flag: '🇰🇿', name: { en: 'Kazakhstan', tr: 'Kazakistan', az: 'Qazaxıstan', ru: 'Казахстан' } },
  { code: 'TM', slug: 'turkmenistan', flag: '🇹🇲', name: { en: 'Turkmenistan', tr: 'Türkmenistan', az: 'Türkmənistan', ru: 'Туркменистан' } },
  { code: 'KG', slug: 'kyrgyzstan', flag: '🇰🇬', name: { en: 'Kyrgyzstan', tr: 'Kırgızistan', az: 'Qırğızıstan', ru: 'Кыргызстан' } },
  { code: 'PK', slug: 'pakistan', flag: '🇵🇰', name: { en: 'Pakistan', tr: 'Pakistan', az: 'Pakistan', ru: 'Пакистан' } },
  { code: 'NG', slug: 'nigeria', flag: '🇳🇬', name: { en: 'Nigeria', tr: 'Nijerya', az: 'Nigeriya', ru: 'Нигерия' } },
  { code: 'IR', slug: 'iran', flag: '🇮🇷', name: { en: 'Iran', tr: 'İran', az: 'İran', ru: 'Иран' } },
  { code: 'IQ', slug: 'iraq', flag: '🇮🇶', name: { en: 'Iraq', tr: 'Irak', az: 'İraq', ru: 'Ирак' } },
  { code: 'TR', slug: 'turkey', flag: '🇹🇷', name: { en: 'Turkey', tr: 'Türkiye', az: 'Türkiyə', ru: 'Турция' } },

  // === Europe ===
  { code: 'DE', slug: 'germany', flag: '🇩🇪', name: { en: 'Germany', tr: 'Almanya', az: 'Almaniya', ru: 'Германия' } },
  { code: 'FR', slug: 'france', flag: '🇫🇷', name: { en: 'France', tr: 'Fransa', az: 'Fransa', ru: 'Франция' } },
  { code: 'GB', slug: 'united-kingdom', flag: '🇬🇧', name: { en: 'United Kingdom', tr: 'İngiltere', az: 'Böyük Britaniya', ru: 'Великобритания' } },
  { code: 'IT', slug: 'italy', flag: '🇮🇹', name: { en: 'Italy', tr: 'İtalya', az: 'İtaliya', ru: 'Италия' } },
  { code: 'ES', slug: 'spain', flag: '🇪🇸', name: { en: 'Spain', tr: 'İspanya', az: 'İspaniya', ru: 'Испания' } },
  { code: 'NL', slug: 'netherlands', flag: '🇳🇱', name: { en: 'Netherlands', tr: 'Hollanda', az: 'Niderland', ru: 'Нидерланды' } },
  { code: 'BE', slug: 'belgium', flag: '🇧🇪', name: { en: 'Belgium', tr: 'Belçika', az: 'Belçika', ru: 'Бельгия' } },
  { code: 'AT', slug: 'austria', flag: '🇦🇹', name: { en: 'Austria', tr: 'Avusturya', az: 'Avstriya', ru: 'Австрия' } },
  { code: 'CH', slug: 'switzerland', flag: '🇨🇭', name: { en: 'Switzerland', tr: 'İsviçre', az: 'İsveçrə', ru: 'Швейцария' } },
  { code: 'SE', slug: 'sweden', flag: '🇸🇪', name: { en: 'Sweden', tr: 'İsveç', az: 'İsveç', ru: 'Швеция' } },
  { code: 'NO', slug: 'norway', flag: '🇳🇴', name: { en: 'Norway', tr: 'Norveç', az: 'Norveç', ru: 'Норвегия' } },
  { code: 'DK', slug: 'denmark', flag: '🇩🇰', name: { en: 'Denmark', tr: 'Danimarka', az: 'Danimarka', ru: 'Дания' } },
  { code: 'FI', slug: 'finland', flag: '🇫🇮', name: { en: 'Finland', tr: 'Finlandiya', az: 'Finlandiya', ru: 'Финляндия' } },
  { code: 'PL', slug: 'poland', flag: '🇵🇱', name: { en: 'Poland', tr: 'Polonya', az: 'Polşa', ru: 'Польша' } },
  { code: 'UA', slug: 'ukraine', flag: '🇺🇦', name: { en: 'Ukraine', tr: 'Ukrayna', az: 'Ukrayna', ru: 'Украина' } },
  { code: 'BY', slug: 'belarus', flag: '🇧🇾', name: { en: 'Belarus', tr: 'Belarus', az: 'Belarus', ru: 'Беларусь' } },
  { code: 'RO', slug: 'romania', flag: '🇷🇴', name: { en: 'Romania', tr: 'Romanya', az: 'Rumıniya', ru: 'Румыния' } },
  { code: 'BG', slug: 'bulgaria', flag: '🇧🇬', name: { en: 'Bulgaria', tr: 'Bulgaristan', az: 'Bolqarıstan', ru: 'Болгария' } },
  { code: 'GR', slug: 'greece', flag: '🇬🇷', name: { en: 'Greece', tr: 'Yunanistan', az: 'Yunanıstan', ru: 'Греция' } },
  { code: 'PT', slug: 'portugal', flag: '🇵🇹', name: { en: 'Portugal', tr: 'Portekiz', az: 'Portuqaliya', ru: 'Португалия' } },
  { code: 'IE', slug: 'ireland', flag: '🇮🇪', name: { en: 'Ireland', tr: 'İrlanda', az: 'İrlandiya', ru: 'Ирландия' } },
  { code: 'CZ', slug: 'czech-republic', flag: '🇨🇿', name: { en: 'Czech Republic', tr: 'Çekya', az: 'Çexiya', ru: 'Чехия' } },
  { code: 'HU', slug: 'hungary', flag: '🇭🇺', name: { en: 'Hungary', tr: 'Macaristan', az: 'Macarıstan', ru: 'Венгрия' } },
  { code: 'SK', slug: 'slovakia', flag: '🇸🇰', name: { en: 'Slovakia', tr: 'Slovakya', az: 'Slovakiya', ru: 'Словакия' } },
  { code: 'HR', slug: 'croatia', flag: '🇭🇷', name: { en: 'Croatia', tr: 'Hırvatistan', az: 'Xırvatıstan', ru: 'Хорватия' } },
  { code: 'RS', slug: 'serbia', flag: '🇷🇸', name: { en: 'Serbia', tr: 'Sırbistan', az: 'Serbiya', ru: 'Сербия' } },
  { code: 'BA', slug: 'bosnia-and-herzegovina', flag: '🇧🇦', name: { en: 'Bosnia and Herzegovina', tr: 'Bosna-Hersek', az: 'Bosniya və Herseqovina', ru: 'Босния и Герцеговина' } },
  { code: 'AL', slug: 'albania', flag: '🇦🇱', name: { en: 'Albania', tr: 'Arnavutluk', az: 'Albaniya', ru: 'Албания' } },
  { code: 'MK', slug: 'north-macedonia', flag: '🇲🇰', name: { en: 'North Macedonia', tr: 'Kuzey Makedonya', az: 'Şimali Makedoniya', ru: 'Северная Македония' } },
  { code: 'SI', slug: 'slovenia', flag: '🇸🇮', name: { en: 'Slovenia', tr: 'Slovenya', az: 'Sloveniya', ru: 'Словения' } },
  { code: 'LT', slug: 'lithuania', flag: '🇱🇹', name: { en: 'Lithuania', tr: 'Litvanya', az: 'Litva', ru: 'Литва' } },
  { code: 'LV', slug: 'latvia', flag: '🇱🇻', name: { en: 'Latvia', tr: 'Letonya', az: 'Latviya', ru: 'Латвия' } },
  { code: 'EE', slug: 'estonia', flag: '🇪🇪', name: { en: 'Estonia', tr: 'Estonya', az: 'Estoniya', ru: 'Эстония' } },
  { code: 'MD', slug: 'moldova', flag: '🇲🇩', name: { en: 'Moldova', tr: 'Moldova', az: 'Moldova', ru: 'Молдова' } },
  { code: 'GE', slug: 'georgia', flag: '🇬🇪', name: { en: 'Georgia', tr: 'Gürcistan', az: 'Gürcüstan', ru: 'Грузия' } },
  { code: 'AM', slug: 'armenia', flag: '🇦🇲', name: { en: 'Armenia', tr: 'Ermenistan', az: 'Ermənistan', ru: 'Армения' } },
  { code: 'IS', slug: 'iceland', flag: '🇮🇸', name: { en: 'Iceland', tr: 'İzlanda', az: 'İslandiya', ru: 'Исландия' } },
  { code: 'LU', slug: 'luxembourg', flag: '🇱🇺', name: { en: 'Luxembourg', tr: 'Lüksemburg', az: 'Lüksemburq', ru: 'Люксембург' } },
  { code: 'MT', slug: 'malta', flag: '🇲🇹', name: { en: 'Malta', tr: 'Malta', az: 'Malta', ru: 'Мальта' } },
  { code: 'CY', slug: 'cyprus', flag: '🇨🇾', name: { en: 'Cyprus', tr: 'Kıbrıs', az: 'Kipr', ru: 'Кипр' } },
  { code: 'ME', slug: 'montenegro', flag: '🇲🇪', name: { en: 'Montenegro', tr: 'Karadağ', az: 'Çernoqoriya', ru: 'Черногория' } },

  // === Americas ===
  { code: 'US', slug: 'united-states', flag: '🇺🇸', name: { en: 'United States', tr: 'Amerika', az: 'ABŞ', ru: 'США' } },
  { code: 'CA', slug: 'canada', flag: '🇨🇦', name: { en: 'Canada', tr: 'Kanada', az: 'Kanada', ru: 'Канада' } },
  { code: 'BR', slug: 'brazil', flag: '🇧🇷', name: { en: 'Brazil', tr: 'Brezilya', az: 'Braziliya', ru: 'Бразилия' } },
  { code: 'AR', slug: 'argentina', flag: '🇦🇷', name: { en: 'Argentina', tr: 'Arjantin', az: 'Argentina', ru: 'Аргентина' } },
  { code: 'MX', slug: 'mexico', flag: '🇲🇽', name: { en: 'Mexico', tr: 'Meksika', az: 'Meksika', ru: 'Мексика' } },
  { code: 'CO', slug: 'colombia', flag: '🇨🇴', name: { en: 'Colombia', tr: 'Kolombiya', az: 'Kolumbiya', ru: 'Колумбия' } },
  { code: 'CL', slug: 'chile', flag: '🇨🇱', name: { en: 'Chile', tr: 'Şili', az: 'Çili', ru: 'Чили' } },
  { code: 'PE', slug: 'peru', flag: '🇵🇪', name: { en: 'Peru', tr: 'Peru', az: 'Peru', ru: 'Перу' } },
  { code: 'VE', slug: 'venezuela', flag: '🇻🇪', name: { en: 'Venezuela', tr: 'Venezuela', az: 'Venezuela', ru: 'Венесуэла' } },
  { code: 'EC', slug: 'ecuador', flag: '🇪🇨', name: { en: 'Ecuador', tr: 'Ekvador', az: 'Ekvador', ru: 'Эквадор' } },
  { code: 'BO', slug: 'bolivia', flag: '🇧🇴', name: { en: 'Bolivia', tr: 'Bolivya', az: 'Boliviya', ru: 'Боливия' } },
  { code: 'PY', slug: 'paraguay', flag: '🇵🇾', name: { en: 'Paraguay', tr: 'Paraguay', az: 'Paraqvay', ru: 'Парагвай' } },
  { code: 'UY', slug: 'uruguay', flag: '🇺🇾', name: { en: 'Uruguay', tr: 'Uruguay', az: 'Uruqvay', ru: 'Уругвай' } },
  { code: 'CR', slug: 'costa-rica', flag: '🇨🇷', name: { en: 'Costa Rica', tr: 'Kosta Rika', az: 'Kosta Rika', ru: 'Коста-Рика' } },
  { code: 'PA', slug: 'panama', flag: '🇵🇦', name: { en: 'Panama', tr: 'Panama', az: 'Panama', ru: 'Панама' } },
  { code: 'DO', slug: 'dominican-republic', flag: '🇩🇴', name: { en: 'Dominican Republic', tr: 'Dominik Cumhuriyeti', az: 'Dominikan Respublikası', ru: 'Доминиканская Республика' } },
  { code: 'GT', slug: 'guatemala', flag: '🇬🇹', name: { en: 'Guatemala', tr: 'Guatemala', az: 'Qvatemala', ru: 'Гватемала' } },
  { code: 'HN', slug: 'honduras', flag: '🇭🇳', name: { en: 'Honduras', tr: 'Honduras', az: 'Honduras', ru: 'Гондурас' } },
  { code: 'SV', slug: 'el-salvador', flag: '🇸🇻', name: { en: 'El Salvador', tr: 'El Salvador', az: 'El Salvador', ru: 'Сальвадор' } },
  { code: 'NI', slug: 'nicaragua', flag: '🇳🇮', name: { en: 'Nicaragua', tr: 'Nikaragua', az: 'Nikaraqua', ru: 'Никарагуа' } },
  { code: 'CU', slug: 'cuba', flag: '🇨🇺', name: { en: 'Cuba', tr: 'Küba', az: 'Kuba', ru: 'Куба' } },
  { code: 'HT', slug: 'haiti', flag: '🇭🇹', name: { en: 'Haiti', tr: 'Haiti', az: 'Haiti', ru: 'Гаити' } },
  { code: 'JM', slug: 'jamaica', flag: '🇯🇲', name: { en: 'Jamaica', tr: 'Jamaika', az: 'Yamayka', ru: 'Ямайка' } },
  { code: 'TT', slug: 'trinidad-and-tobago', flag: '🇹🇹', name: { en: 'Trinidad and Tobago', tr: 'Trinidad ve Tobago', az: 'Trinidad və Tobaqo', ru: 'Тринидад и Тобаго' } },

  // === Asia ===
  { code: 'CN', slug: 'china', flag: '🇨🇳', name: { en: 'China', tr: 'Çin', az: 'Çin', ru: 'Китай' } },
  { code: 'IN', slug: 'india', flag: '🇮🇳', name: { en: 'India', tr: 'Hindistan', az: 'Hindistan', ru: 'Индия' } },
  { code: 'JP', slug: 'japan', flag: '🇯🇵', name: { en: 'Japan', tr: 'Japonya', az: 'Yaponiya', ru: 'Япония' } },
  { code: 'KR', slug: 'south-korea', flag: '🇰🇷', name: { en: 'South Korea', tr: 'Güney Kore', az: 'Cənubi Koreya', ru: 'Южная Корея' } },
  { code: 'ID', slug: 'indonesia', flag: '🇮🇩', name: { en: 'Indonesia', tr: 'Endonezya', az: 'İndoneziya', ru: 'Индонезия' } },
  { code: 'MY', slug: 'malaysia', flag: '🇲🇾', name: { en: 'Malaysia', tr: 'Malezya', az: 'Malayziya', ru: 'Малайзия' } },
  { code: 'TH', slug: 'thailand', flag: '🇹🇭', name: { en: 'Thailand', tr: 'Tayland', az: 'Tailand', ru: 'Таиланд' } },
  { code: 'VN', slug: 'vietnam', flag: '🇻🇳', name: { en: 'Vietnam', tr: 'Vietnam', az: 'Vyetnam', ru: 'Вьетнам' } },
  { code: 'PH', slug: 'philippines', flag: '🇵🇭', name: { en: 'Philippines', tr: 'Filipinler', az: 'Filippin', ru: 'Филиппины' } },
  { code: 'SG', slug: 'singapore', flag: '🇸🇬', name: { en: 'Singapore', tr: 'Singapur', az: 'Sinqapur', ru: 'Сингапур' } },
  { code: 'BD', slug: 'bangladesh', flag: '🇧🇩', name: { en: 'Bangladesh', tr: 'Bangladeş', az: 'Banqladeş', ru: 'Бангладеш' } },
  { code: 'LK', slug: 'sri-lanka', flag: '🇱🇰', name: { en: 'Sri Lanka', tr: 'Sri Lanka', az: 'Şri-Lanka', ru: 'Шри-Ланка' } },
  { code: 'NP', slug: 'nepal', flag: '🇳🇵', name: { en: 'Nepal', tr: 'Nepal', az: 'Nepal', ru: 'Непал' } },
  { code: 'AF', slug: 'afghanistan', flag: '🇦🇫', name: { en: 'Afghanistan', tr: 'Afganistan', az: 'Əfqanıstan', ru: 'Афганистан' } },
  { code: 'SA', slug: 'saudi-arabia', flag: '🇸🇦', name: { en: 'Saudi Arabia', tr: 'Suudi Arabistan', az: 'Səudiyyə Ərəbistanı', ru: 'Саудовская Аравия' } },
  { code: 'AE', slug: 'united-arab-emirates', flag: '🇦🇪', name: { en: 'United Arab Emirates', tr: 'BAE', az: 'BƏE', ru: 'ОАЭ' } },
  { code: 'QA', slug: 'qatar', flag: '🇶🇦', name: { en: 'Qatar', tr: 'Katar', az: 'Qətər', ru: 'Катар' } },
  { code: 'KW', slug: 'kuwait', flag: '🇰🇼', name: { en: 'Kuwait', tr: 'Kuveyt', az: 'Küveyt', ru: 'Кувейт' } },
  { code: 'BH', slug: 'bahrain', flag: '🇧🇭', name: { en: 'Bahrain', tr: 'Bahreyn', az: 'Bəhreyn', ru: 'Бахрейн' } },
  { code: 'OM', slug: 'oman', flag: '🇴🇲', name: { en: 'Oman', tr: 'Umman', az: 'Oman', ru: 'Оман' } },
  { code: 'JO', slug: 'jordan', flag: '🇯🇴', name: { en: 'Jordan', tr: 'Ürdün', az: 'İordaniya', ru: 'Иордания' } },
  { code: 'LB', slug: 'lebanon', flag: '🇱🇧', name: { en: 'Lebanon', tr: 'Lübnan', az: 'Livan', ru: 'Ливан' } },
  { code: 'SY', slug: 'syria', flag: '🇸🇾', name: { en: 'Syria', tr: 'Suriye', az: 'Suriya', ru: 'Сирия' } },
  { code: 'PS', slug: 'palestine', flag: '🇵🇸', name: { en: 'Palestine', tr: 'Filistin', az: 'Fələstin', ru: 'Палестина' } },
  { code: 'YE', slug: 'yemen', flag: '🇾🇪', name: { en: 'Yemen', tr: 'Yemen', az: 'Yəmən', ru: 'Йемен' } },
  { code: 'MM', slug: 'myanmar', flag: '🇲🇲', name: { en: 'Myanmar', tr: 'Myanmar', az: 'Myanma', ru: 'Мьянма' } },
  { code: 'KH', slug: 'cambodia', flag: '🇰🇭', name: { en: 'Cambodia', tr: 'Kamboçya', az: 'Kamboca', ru: 'Камбоджа' } },
  { code: 'LA', slug: 'laos', flag: '🇱🇦', name: { en: 'Laos', tr: 'Laos', az: 'Laos', ru: 'Лаос' } },
  { code: 'MN', slug: 'mongolia', flag: '🇲🇳', name: { en: 'Mongolia', tr: 'Moğolistan', az: 'Monqolustan', ru: 'Монголия' } },
  { code: 'KZ', slug: 'kazakhstan', flag: '🇰🇿', name: { en: 'Kazakhstan', tr: 'Kazakistan', az: 'Qazaxıstan', ru: 'Казахстан' } },
  { code: 'TW', slug: 'taiwan', flag: '🇹🇼', name: { en: 'Taiwan', tr: 'Tayvan', az: 'Tayvan', ru: 'Тайвань' } },
  { code: 'HK', slug: 'hong-kong', flag: '🇭🇰', name: { en: 'Hong Kong', tr: 'Hong Kong', az: 'Honq Konq', ru: 'Гонконг' } },

  // === Africa ===
  { code: 'EG', slug: 'egypt', flag: '🇪🇬', name: { en: 'Egypt', tr: 'Mısır', az: 'Misir', ru: 'Египет' } },
  { code: 'MA', slug: 'morocco', flag: '🇲🇦', name: { en: 'Morocco', tr: 'Fas', az: 'Mərakeş', ru: 'Марокко' } },
  { code: 'DZ', slug: 'algeria', flag: '🇩🇿', name: { en: 'Algeria', tr: 'Cezayir', az: 'Əlcəzair', ru: 'Алжир' } },
  { code: 'TN', slug: 'tunisia', flag: '🇹🇳', name: { en: 'Tunisia', tr: 'Tunus', az: 'Tunis', ru: 'Тунис' } },
  { code: 'LY', slug: 'libya', flag: '🇱🇾', name: { en: 'Libya', tr: 'Libya', az: 'Liviya', ru: 'Ливия' } },
  { code: 'SD', slug: 'sudan', flag: '🇸🇩', name: { en: 'Sudan', tr: 'Sudan', az: 'Sudan', ru: 'Судан' } },
  { code: 'ET', slug: 'ethiopia', flag: '🇪🇹', name: { en: 'Ethiopia', tr: 'Etiyopya', az: 'Efiopiya', ru: 'Эфиопия' } },
  { code: 'KE', slug: 'kenya', flag: '🇰🇪', name: { en: 'Kenya', tr: 'Kenya', az: 'Keniya', ru: 'Кения' } },
  { code: 'TZ', slug: 'tanzania', flag: '🇹🇿', name: { en: 'Tanzania', tr: 'Tanzanya', az: 'Tanzaniya', ru: 'Танзания' } },
  { code: 'UG', slug: 'uganda', flag: '🇺🇬', name: { en: 'Uganda', tr: 'Uganda', az: 'Uqanda', ru: 'Уганда' } },
  { code: 'GH', slug: 'ghana', flag: '🇬🇭', name: { en: 'Ghana', tr: 'Gana', az: 'Qana', ru: 'Гана' } },
  { code: 'CI', slug: 'ivory-coast', flag: '🇨🇮', name: { en: 'Ivory Coast', tr: 'Fildişi Sahili', az: 'Kotd’ivuar', ru: 'Кот-д\'Ивуар' } },
  { code: 'SN', slug: 'senegal', flag: '🇸🇳', name: { en: 'Senegal', tr: 'Senegal', az: 'Seneqal', ru: 'Сенегал' } },
  { code: 'CM', slug: 'cameroon', flag: '🇨🇲', name: { en: 'Cameroon', tr: 'Kamerun', az: 'Kamerun', ru: 'Камерун' } },
  { code: 'ZA', slug: 'south-africa', flag: '🇿🇦', name: { en: 'South Africa', tr: 'Güney Afrika', az: 'Cənubi Afrika', ru: 'ЮАР' } },
  { code: 'RW', slug: 'rwanda', flag: '🇷🇼', name: { en: 'Rwanda', tr: 'Ruanda', az: 'Ruanda', ru: 'Руанда' } },
  { code: 'MZ', slug: 'mozambique', flag: '🇲🇿', name: { en: 'Mozambique', tr: 'Mozambik', az: 'Mozambik', ru: 'Мозамбик' } },
  { code: 'AO', slug: 'angola', flag: '🇦🇴', name: { en: 'Angola', tr: 'Angola', az: 'Anqola', ru: 'Ангола' } },
  { code: 'SO', slug: 'somalia', flag: '🇸🇴', name: { en: 'Somalia', tr: 'Somali', az: 'Somali', ru: 'Сомали' } },
  { code: 'CD', slug: 'dr-congo', flag: '🇨🇩', name: { en: 'DR Congo', tr: 'Kongo DC', az: 'KDR Konqo', ru: 'ДР Конго' } },
  { code: 'MG', slug: 'madagascar', flag: '🇲🇬', name: { en: 'Madagascar', tr: 'Madagaskar', az: 'Madaqaskar', ru: 'Мадагаскар' } },
  { code: 'ZM', slug: 'zambia', flag: '🇿🇲', name: { en: 'Zambia', tr: 'Zambiya', az: 'Zambiya', ru: 'Замбия' } },
  { code: 'ZW', slug: 'zimbabwe', flag: '🇿🇼', name: { en: 'Zimbabwe', tr: 'Zimbabve', az: 'Zimbabve', ru: 'Зимбабве' } },
  { code: 'NA', slug: 'namibia', flag: '🇳🇦', name: { en: 'Namibia', tr: 'Namibya', az: 'Namibiya', ru: 'Намибия' } },
  { code: 'BW', slug: 'botswana', flag: '🇧🇼', name: { en: 'Botswana', tr: 'Botsvana', az: 'Botsvana', ru: 'Ботсвана' } },
  { code: 'GM', slug: 'gambia', flag: '🇬🇲', name: { en: 'Gambia', tr: 'Gambiya', az: 'Qambiya', ru: 'Гамбия' } },
  { code: 'GN', slug: 'guinea', flag: '🇬🇳', name: { en: 'Guinea', tr: 'Gine', az: 'Qvineya', ru: 'Гвинея' } },
  { code: 'ML', slug: 'mali', flag: '🇲🇱', name: { en: 'Mali', tr: 'Mali', az: 'Mali', ru: 'Мали' } },
  { code: 'BF', slug: 'burkina-faso', flag: '🇧🇫', name: { en: 'Burkina Faso', tr: 'Burkina Faso', az: 'Burkina Faso', ru: 'Буркина-Фасо' } },
  { code: 'BJ', slug: 'benin', flag: '🇧🇯', name: { en: 'Benin', tr: 'Benin', az: 'Benin', ru: 'Бенин' } },
  { code: 'TG', slug: 'togo', flag: '🇹🇬', name: { en: 'Togo', tr: 'Togo', az: 'Toqo', ru: 'Того' } },
  { code: 'MR', slug: 'mauritania', flag: '🇲🇷', name: { en: 'Mauritania', tr: 'Moritanya', az: 'Mavritaniya', ru: 'Мавритания' } },
  { code: 'ER', slug: 'eritrea', flag: '🇪🇷', name: { en: 'Eritrea', tr: 'Eritre', az: 'Eritreya', ru: 'Эритрея' } },

  // === Oceania ===
  { code: 'AU', slug: 'australia', flag: '🇦🇺', name: { en: 'Australia', tr: 'Avustralya', az: 'Avstraliya', ru: 'Австралия' } },
  { code: 'NZ', slug: 'new-zealand', flag: '🇳🇿', name: { en: 'New Zealand', tr: 'Yeni Zelanda', az: 'Yeni Zelandiya', ru: 'Новая Зеландия' } },
  { code: 'FJ', slug: 'fiji', flag: '🇫🇯', name: { en: 'Fiji', tr: 'Fiji', az: 'Fici', ru: 'Фиджи' } },
];