import type { Faq } from "@/types";

export const seedFaqs: Faq[] = [
  // General FAQs
  {
    id: "f-g1",
    entityType: "general",
    entityId: "general",
    question: {
      en: "Do I need to know Turkish to study in Turkey?",
      tr: "Türkiye'de okumak için Türkçe bilmem gerekir mi?",
      az: "Türkiyədə oxumaq üçün türkçə bilməliyəmmi?",
      ru: "Нужно ли знать турецкий, чтобы учиться в Турции?",
      de: "Muss ich Türkisch können, um in der Türkei zu studieren?",
      fr: "Dois-je parler turc pour étudier en Turquie ?",
      fa: "آیا برای تحصیل در ترکیه باید ترکی بدانم؟",
      ar: "هل أحتاج إلى معرفة التركية للدراسة في تركيا؟",
      tk: "Türkiýede okamak üçin türk dilini bilmek gerekmi?",
      kk: "Түркияда оқу үшін түрік тілін білуім керек пе?",
      ky: "Түркияда окуу үчүн түрк тилин билишим керекпи?",
      zh: "在土耳其留学需要会土耳其语吗？",
      bg: "Трябва ли да знам турски, за да уча в Турция?",
      ur: "کیا ترکی میں تعلیم کے لیے ترکی زبان آنا ضروری ہے؟",
      uz: "Turkiyada o'qish uchun turk tilini bilishim kerakmi?",
      sw: "Je, ninahitaji kujua Kituruki kusoma Uturuki?",
      so: "Ma waxaan u baahanahay inaan ogaado Turkiga si aan u barto Turkiga?",
      id: "Apakah saya perlu bisa bahasa Turki untuk kuliah di Turki?",
    },
    answer: {
      en: "No. Hundreds of programs are taught fully in English. Turkish is helpful for daily life but not required for English-medium programs.",
      tr: "Hayır. Yüzlerce program tamamen İngilizce verilir. Türkçe günlük hayat için faydalıdır ama İngilizce programlar için gerekli değildir.",
      az: "Xeyr. Yüzlərlə proqram tamamilə ingilis dilindədir. Türkçə gündəlik həyat üçün faydalıdır, amma ingilis dilində proqramlar üçün tələb olunmur.",
      ru: "Нет. Сотни программ полностью на английском. Турецкий полезен в быту, но не обязателен для англоязычных программ.",
      de: "Nein. Hunderte Programme werden vollständig auf Englisch unterrichtet. Türkisch ist im Alltag hilfreich, aber für englischsprachige Programme nicht erforderlich.",
      fr: "Non. Des centaines de programmes sont entièrement en anglais. Le turc est utile au quotidien mais pas requis pour les programmes en anglais.",
      fa: "خیر. صدها برنامه کاملاً به انگلیسی ارائه میشوند. ترکی برای زندگی روزمره مفید است اما برای برنامههای انگلیسی الزامی نیست.",
      ar: "لا. المئات من البرامج تُدرَّس بالكامل بالإنجليزية. التركية مفيدة للحياة اليومية لكنها غير مطلوبة للبرامج الإنجليزية.",
      tk: "Ýok. Ýüzlerçe programma doly iňlis dilinde okadylýar. Türk dili gündelik durmuşda peýdaly, ýöne iňlis dilindäki programmalar üçin hökman däl.",
      kk: "Жоқ. Жүздеген бағдарлама толығымен ағылшын тілінде оқытылады. Түрік тілі күнделікті өмірде пайдалы, бірақ ағылшын тілді бағдарламалар үшін қажет емес.",
      ky: "Жок. Жүздөгөн программа толугу менен англис тилинде окутулат. Түрк тили күнүмдүк жашоодо пайдалуу, бирок англис тилиндеги программалар үчүн талап кылынбайт.",
      zh: "不需要。数百个课程完全用英语授课。土耳其语对日常生活有帮助，但英语授课课程不作要求。",
      bg: "Не. Стотици програми се преподават изцяло на английски. Турският е полезен в ежедневието, но не е задължителен за англоезични програми.",
      ur: "نہیں۔ سینکڑوں پروگرام مکمل طور پر انگریزی میں پڑھائے جاتے ہیں۔ ترکی روزمرہ زندگی کے لیے مفید ہے لیکن انگریزی پروگراموں کے لیے ضروری نہیں۔",
      uz: "Yo'q. Yuzlab dasturlar to'liq ingliz tilida o'qitiladi. Turk tili kundalik hayotda foydali, lekin ingliz tilidagi dasturlar uchun shart emas.",
      sw: "Hapana. Mamia ya programu hufundishwa kwa Kiingereza kabisa. Kituruki kinasaidia maisha ya kila siku lakini hakihitajiki kwa programu za Kiingereza.",
      so: "Maya. Boqollaal barnaamij ayaa si buuxda ku baxa Ingiriisiga. Turkiga waxaa faa'iido u leh nolol maalmeedka laakiin loogama baahna barnaamijyada Ingiriisiga.",
      id: "Tidak. Ratusan program diajarkan sepenuhnya dalam bahasa Inggris. Bahasa Turki berguna untuk kehidupan sehari-hari tetapi tidak wajib untuk program berbahasa Inggris.",
    },
  },
  {
    id: "f-g2",
    entityType: "general",
    entityId: "general",
    question: {
      en: "How much does it cost to study in Turkey?",
      tr: "Türkiye'de eğitim maliyeti ne kadar?",
      az: "Türkiyədə təhsilin dəyəri nə qədərdir?",
      ru: "Сколько стоит учёба в Турции?",
      de: "Wie viel kostet ein Studium in der Türkei?",
      fr: "Combien coûte un séjour d'études en Turquie ?",
      fa: "هزینه تحصیل در ترکیه چقدر است؟",
      ar: "كم تكلفة الدراسة في تركيا؟",
      tk: "Türkiýede okuw näçe çekýär?",
      kk: "Түркияда оқу қанша тұрады?",
      ky: "Түркияда окуу канча турат?",
      zh: "在土耳其留学费用是多少？",
      bg: "Колко струва обучението в Турция?",
      ur: "ترکی میں تعلیم کی لاگت کتنی ہے؟",
      uz: "Turkiyada o'qish qancha turadi?",
      sw: "Kusoma Uturuki kunagharimu kiasi gani?",
      so: "Waxbarashada Turkiga imisa ayay ku kacdaa?",
      id: "Berapa biaya kuliah di Turki?",
    },
    answer: {
      en: "State universities cost roughly USD 600–2,000 per year; private universities USD 5,000–25,000. Living costs are around USD 300–600 per month.",
      tr: "Devlet üniversiteleri yılda yaklaşık 600–2.000 USD; vakıf üniversiteleri 5.000–25.000 USD. Yaşam maliyeti aylık 300–600 USD civarındadır.",
      az: "Dövlət universitetləri təxminən 600–2000 ABŞ dolları; özəl universitetlər 5000–25000 ABŞ dolları. Yaşayış xərcləri ayda 300–600 ABŞ dollarıdır.",
      ru: "Государственные вузы: 600–2 000 USD в год; частные: 5 000–25 000 USD. Проживание — около 300–600 USD в месяц.",
      de: "Staatliche Universitäten kosten etwa 600–2.000 USD pro Jahr; private Universitäten 5.000–25.000 USD. Lebenshaltungskosten liegen bei etwa 300–600 USD pro Monat.",
      fr: "Les universités publiques coûtent environ 600 à 2 000 USD par an ; les universités privées 5 000 à 25 000 USD. Le coût de la vie est d'environ 300 à 600 USD par mois.",
      fa: "دانشگاههای دولتی حدود ۶۰۰ تا ۲۰۰۰ دلار در سال و دانشگاههای خصوصی ۵۰۰۰ تا ۲۵۰۰۰ دلار هزینه دارند. هزینه زندگی ماهانه حدود ۳۰۰ تا ۶۰۰ دلار است.",
      ar: "الجامعات الحكومية تكلف حوالي 600–2000 دولار سنوياً؛ والخاصة 5000–25000 دولار. تكاليف المعيشة حوالي 300–600 دولار شهرياً.",
      tk: "Döwlet uniwersitetleri ýylda takmynan 600–2000 USD; hususy uniwersitetler 5000–25000 USD. Ýaşaýyş çykdajylary aýda 300–600 USD töweregi.",
      kk: "Мемлекеттік университеттер жылына шамамен 600–2000 АҚШ доллары; жеке университеттер 5000–25000 АҚШ доллары. Өмір сүру құны айына 300–600 АҚШ доллары.",
      ky: "Мамлекеттик университеттер жылына болжол менен 600–2000 АКШ доллары; жеке университеттер 5000–25000 АКШ доллары. Жашоо чыгымдары айына 300–600 АКШ доллары.",
      zh: "公立大学每年约600–2000美元；私立大学5000–25000美元。生活费每月约300–600美元。",
      bg: "Държавните университети струват около 600–2000 USD годишно; частните 5000–25000 USD. Разходите за живот са около 300–600 USD месечно.",
      ur: "سرکاری یونیورسٹیاں سالانہ تقریباً 600–2000 ڈالر؛ پرائیویٹ یونیورسٹیاں 5000–25000 ڈالر۔ رہائشی اخراجات ماہانہ 300–600 ڈالر۔",
      uz: "Davlat universitetlari yiliga taxminan 600–2000 AQSh dollari; xususiy universitetlar 5000–25000 AQSh dollari. Yashash xarajatlari oyiga 300–600 AQSh dollari.",
      sw: "Vyuo vya umma hugharimu takriban USD 600–2,000 kwa mwaka; vyuo vya kibinafsi USD 5,000–25,000. Gharama za maisha ni karibu USD 300–600 kwa mwezi.",
      so: "Jaamacadaha dawladda waxay ku kacaan qiyaastii 600–2000 dollar sanadkii; kuwa gaarka ah 5000–25000 dollar. Kharashka noloshu waa 300–600 dollar bishii.",
      id: "Universitas negeri sekitar USD 600–2.000 per tahun; universitas swasta USD 5.000–25.000. Biaya hidup sekitar USD 300–600 per bulan.",
    },
  },
  {
    id: "f-g3",
    entityType: "general",
    entityId: "general",
    question: {
      en: "Do I need a student visa?",
      tr: "Öğrenci vizesi gerekli mi?",
      az: "Tələbə vizası lazımdırmı?",
      ru: "Нужна ли студенческая виза?",
      de: "Brauche ich ein Studentenvisum?",
      fr: "Ai-je besoin d'un visa étudiant ?",
      fa: "آیا به ویزای دانشجویی نیاز دارم؟",
      ar: "هل أحتاج إلى تأشيرة طالب؟",
      tk: "Okuwçy wizasy gerekmi?",
      kk: "Маған студенттік виза керек пе?",
      ky: "Мага студенттик виза керекпи?",
      zh: "我需要学生签证吗？",
      bg: "Нужна ли ми е студентска виза?",
      ur: "کیا مجھے طالب علم ویزا چاہیے؟",
      uz: "Menga talaba vizasi kerakmi?",
      sw: "Je, ninahitaji visa ya mwanafunzi?",
      so: "Ma waxaan u baahanahay fiisaha ardayga?",
      id: "Apakah saya perlu visa pelajar?",
    },
    answer: {
      en: "Yes. After acceptance you apply for a student visa at the Turkish consulate, then convert it to a residence permit after arrival.",
      tr: "Evet. Kabul aldıktan sonra Türk konsolosluğundan öğrenci vizesi alır, varıştan sonra ikamet iznine dönüştürürsünüz.",
      az: "Bəli. Qəbul aldıqdan sonra Türkiyə konsolulluğundan tələbə vizası alır, gəlişdən sonra yaşayış icazəsinə çevirirsiniz.",
      ru: "Да. После зачисления вы получаете студенческую визу в консульстве, а по приезде меняете её на вид на жительство.",
      de: "Ja. Nach der Zulassung beantragen Sie ein Studentenvisum beim türkischen Konsulat und wandeln es nach der Ankunft in eine Aufenthaltserlaubnis um.",
      fr: "Oui. Après acceptation, vous demandez un visa étudiant au consulat turc, puis vous le convertissez en permis de séjour à l'arrivée.",
      fa: "بله. پس از پذیرش، در کنسولگری ترکیه ویزای دانشجویی میگیرید و پس از ورود آن را به اجازه اقامت تبدیل میکنید.",
      ar: "نعم. بعد القبول تتقدم بطلب تأشيرة طالب في القنصلية التركية، ثم تحوّلها إلى تصريح إقامة بعد الوصول.",
      tk: "Hawa. Kabul alanyňyzdan soň türk konsullygyndan okuwçy wizasyny alyp, geleniňizden soň ýaşaýyş rugsadyna öwürýärsiňiz.",
      kk: "Иә. Қабылданғаннан кейін түрік консулдығынан студенттік виза аласыз, содан кейін келгеннен кейін тұруға рұқсатқа айналдырасыз.",
      ky: "Ооба. Кабыл алынгандан кийин түрк консулдугунан студенттик виза алып, келгенден кийин жашоо уруксатына айландырасыз.",
      zh: "是的。被录取后，你在土耳其领事馆申请学生签证，抵达后将其转为居留许可。",
      bg: "Да. След приема кандидатствате за студентска виза в турското консулство, а след пристигане я превръщате в разрешително за престой.",
      ur: "جی ہاں۔ قبولیت کے بعد ترک قونصل خانے سے طالب علم ویزا حاصل کریں، پھر آمد پر اسے رہائشی اجازت نامے میں تبدیل کریں۔",
      uz: "Ha. Qabul qilingandan so'ng Turkiya konsulxonasidan talaba vizasi olasiz va kelgach uni yashash guvohnomasiga aylantirasiz.",
      sw: "Ndiyo. Baada ya kukubaliwa, unaomba visa ya mwanafunzi kwenye ubalozi wa Uturuki, kisha uibadilishe kuwa kibali cha kukaa baada ya kuwasili.",
      so: "Haa. Ka dib marka la aqbalo, waxaad ka codsanaysaa fiisaha ardayga xafiiska Turkiga, ka dibna waxaad u beddeshaa ogolaanshaha degenaanshaha.",
      id: "Ya. Setelah diterima, Anda mengajukan visa pelajar di konsulat Turki, lalu mengubahnya menjadi izin tinggal setelah tiba.",
    },
  },
  {
    id: "f-g4",
    entityType: "general",
    entityId: "general",
    question: {
      en: "Are scholarships available for international students?",
      tr: "Uluslararası öğrenciler için burs var mı?",
      az: "Beynəlxalq tələbələr üçün təqaüd varmı?",
      ru: "Есть ли стипендии для иностранных студентов?",
      de: "Gibt es Stipendien für internationale Studierende?",
      fr: "Des bourses sont-elles disponibles pour les étudiants internationaux ?",
      fa: "آیا بورسیههایی برای دانشجویان بینالمللی وجود دارد؟",
      ar: "هل توجد منح للطلاب الدوليين؟",
      tk: "Halkara talyplar üçin stipendiýalar barmy?",
      kk: "Халықаралық студенттерге стипендия бар ма?",
      ky: "Эл аралык студенттерге стипендия барбы?",
      zh: "国际学生有奖学金吗？",
      bg: "Има ли стипендии за международни студенти?",
      ur: "کیا بین الاقوامی طلباء کے لیے اسکالرشپس دستیاب ہیں؟",
      uz: "Xalqaro talabalar uchun stipendiyalar bormi?",
      sw: "Je, kuna ufadhili kwa wanafunzi wa kimataifa?",
      so: "Ma jiraan deeqo loogu talagalay ardayda caalamiga ah?",
      id: "Apakah tersedia beasiswa untuk mahasiswa internasional?",
    },
    answer: {
      en: "Yes. The Türkiye Bursları government program offers full scholarships, and most private universities offer merit discounts of 25–100%.",
      tr: "Evet. Türkiye Bursları devlet programı tam burs sunar ve çoğu vakıf üniversitesi %25–100 başarı indirimleri verir.",
      az: "Bəli. Türkiye Bursları dövlət proqramı tam təqaüd təklif edir və əksər özəl universitetlər 25–100% nailiyyət endirimləri verir.",
      ru: "Да. Программа Türkiye Bursları даёт полные стипендии, а частные вузы — скидки 25–100% за заслуги.",
      de: "Ja. Das staatliche Programm Türkiye Bursları bietet Vollstipendien, und die meisten privaten Universitäten geben Leistungsrabatte von 25–100%.",
      fr: "Oui. Le programme gouvernemental Türkiye Bursları offre des bourses complètes, et la plupart des universités privées offrent des réductions au mérite de 25 à 100 %.",
      fa: "بله. برنامه دولتی ترکیه بورسلری بورسیه کامل ارائه میدهد و اکثر دانشگاههای خصوصی تخفیف ۲۵ تا ۱۰۰ درصدی میدهند.",
      ar: "نعم. برنامج المنح الحكومي التركي يقدم منحاً كاملة، ومعظم الجامعات الخاصة تقدم خصومات على الاستحقاق من 25 إلى 100%.",
      tk: "Hawa. Türkiye Bursleri döwlet programmasy doly stipendiýa berýär we köp hususy uniwersitetler 25–100% başaryş endirimini berýär.",
      kk: "Иә. Türkiye Bursları мемлекеттік бағдарламасы толық стипендия береді, ал жеке университеттердің көпшілігі 25–100% жетістік жеңілдігін ұсынады.",
      ky: "Ооба. Türkiye Bursları мамлекеттик программасы толук стипендия берет, ал көпчүлүк жеке университеттер 25–100% жетишкендик арзандатуусун сунуштайт.",
      zh: "是的。土耳其政府奖学金项目提供全额奖学金，大多数私立大学提供25–100%的成绩折扣。",
      bg: "Да. Държавната програма Türkiye Bursları дава пълни стипендии, а повечето частни университети дават отстъпки 25–100% за успех.",
      ur: "جی ہاں۔ ترک سرکاری اسکالرشپ پروگرام مکمل اسکالرشپ دیتا ہے، اور زیادہ تر پرائیویٹ یونیورسٹیاں 25–100% میرٹ ڈسکاؤنٹ دیتی ہیں۔",
      uz: "Ha. Türkiye Bursları davlat dasturi to'liq stipendiya beradi va aksariyat xususiy universitetlar 25–100% merit chegirmalarini taqdim etadi.",
      sw: "Ndiyo. Mpango wa serikali wa Türkiye Bursları unatoa ufadhili kamili, na vyuo vingi vya kibinafsi vinatoa punguzo la 25–100% kwa sifa.",
      so: "Haa. Barnaamijka dawladda ee Türkiye Bursları wuxuu bixiyaa deeqo buuxda, jaamacadaha gaarka ah badankooduna waxay bixiyaan qiimo dhimis 25–100% ah.",
      id: "Ya. Program pemerintah Türkiye Bursları menawarkan beasiswa penuh, dan sebagian besar universitas swasta memberikan diskon prestasi 25–100%.",
    },
  },
  {
    id: "f-g5",
    entityType: "general",
    entityId: "general",
    question: {
      en: "What documents do I need to apply?",
      tr: "Başvuru için hangi belgeler gerekli?",
      az: "Müraciət üçün hansı sənədlər lazımdır?",
      ru: "Какие документы нужны для подачи заявки?",
      de: "Welche Unterlagen benötige ich für die Bewerbung?",
      fr: "Quels documents dois-je fournir pour candidater ?",
      fa: "برای ثبتنام چه مدارکی نیاز دارم؟",
      ar: "ما الوثائق المطلوبة للتقديم؟",
      tk: "Ýüz tutmak üçin haýsy resminamalar gerek?",
      kk: "Өтінім беру үшін қандай құжаттар қажет?",
      ky: "Арыз берүү үчүн кандай документтер керек?",
      zh: "申请需要什么材料？",
      bg: "Какви документи са ми нужни за кандидатстване?",
      ur: "درخواست کے لیے کون سی دستاویزات درکار ہیں؟",
      uz: "Ariza topshirish uchun qanday hujjatlar kerak?",
      sw: "Nina hati gani zinahitajika kuomba?",
      so: "Waa kuwee dukumentiyada aan u baahanahay in aan codsado?",
      id: "Dokumen apa saja yang diperlukan untuk mendaftar?",
    },
    answer: {
      en: "Typically: passport, high-school diploma and transcript (translated & notarised), passport photo, motivational letter and language certificate.",
      tr: "Genellikle: pasaport, lise diploması ve transkripti (tercümeli ve onaylı), vesikalık fotoğraf, motivasyon mektubu ve dil sertifikası.",
      az: "Adətən: pasport, orta məktəb diploması və transkripti (tərcümə və təsdiq edilmiş), şəkil, motivasiya məktubu və dil sertifikatı.",
      ru: "Обычно: паспорт, аттестат и выписка оценок (перевод и нотариальное заверение), фото, мотивационное письмо и сертификат о языке.",
      de: "In der Regel: Reisepass, Schulabschlusszeugnis und Notenübersicht (übersetzt und notariell beglaubigt), Passfoto, Motivationsschreiben und Sprachzertifikat.",
      fr: "En général : passeport, diplôme et relevé de notes (traduits et notariés), photo d'identité, lettre de motivation et certificat de langue.",
      fa: "معمولاً: پاسپورت، دیپلم دبیرستان و ریزنمرات (ترجمه و تایید شده)، عکس پرسنلی، نامه انگیزشی و مدرک زبان.",
      ar: "عادةً: جواز السفر، شهادة الثانوية وكشف الدرجات (مترجمة وموثقة)، صورة شخصية، خطاب تحفيزي وشهادة لغة.",
      tk: "Adatça: pasport, orta mekdep diplom we transkript (terjime we tassyklanan), surat, höwes haty we dil şahadatnamasy.",
      kk: "Әдетте: паспорт, мектеп аттестаты және үлгерім көшірмесі (аударылған және куәландырылған), фотосурет, мотивациялық хат және тіл сертификаты.",
      ky: "Адатта: паспорт, орто мектеп диплому жана транскрипт (которулган жана тастыкталган), сүрөт, мотивациялык кат жана тил сертификаты.",
      zh: "通常包括：护照、高中毕业证和成绩单（翻译并公证）、证件照、动机信和语言证书。",
      bg: "Обикновено: паспорт, диплома и стенограма (преведени и нотариално заверени), снимка, мотивационно писмо и езиков сертификат.",
      ur: "عام طور پر: پاسپورٹ، ہائی اسکول ڈپلومہ اور ٹرانسکرپٹ (ترجمہ شدہ اور تصدیق شدہ)، پاسپورٹ تصویر، حوصلہ افزائی خط اور زبان کا سرٹیفکیٹ۔",
      uz: "Odatda: pasport, o'rta maktab diplomi va transkript (tarjima qilingan va tasdiqlangan), rasm, motivatsiya xati va til sertifikati.",
      sw: "Kwa kawaida: pasipoti, diploma ya shule na nakala ya alama (zilizotafsiriwa na kuthibitishwa), picha, barua ya motisha na cheti cha lugha.",
      so: "Sida caadiga ah: baasaboor, shahaadada dugsiga sare iyo nuqulka (oo la turjumay oo la xaqiijiyay), sawir, warqadda dhiirigelinta iyo shahaadada luqadda.",
      id: "Biasanya: paspor, ijazah SMA dan transkrip (diterjemahkan dan dilegalisir), foto, surat motivasi, dan sertifikat bahasa.",
    },
  },
  {
    id: "f-g6",
    entityType: "general",
    entityId: "general",
    question: {
      en: "Can I study in Turkey without IELTS?",
      tr: "IELTS olmadan Türkiye'de okuyabilir miyim?",
      az: "IELTS olmadan Türkiyədə oxuya bilərəmmi?",
      ru: "Можно ли учиться в Турции без IELTS?",
      de: "Kann ich ohne IELTS in der Türkei studieren?",
      fr: "Puis-je étudier en Turquie sans IELTS ?",
      fa: "آیا میتوانم بدون آیلتس در ترکیه تحصیل کنم؟",
      ar: "هل يمكنني الدراسة في تركيا بدون آيلتس؟",
      tk: "IELTS-siz Türkiýede okap bilermi?",
      kk: "IELTS-сіз Түркияда оқуға бола ма?",
      ky: "IELTSсиз Түркияда окуй аламбы?",
      zh: "没有雅思成绩可以到土耳其留学吗？",
      bg: "Мога ли да уча в Турция без IELTS?",
      ur: "کیا میں آئی ایل ٹی ایس کے بغیر ترکی میں تعلیم حاصل کر سکتا ہوں؟",
      uz: "IELTSsiz Turkiyada o‘qish mumkinmi?",
      sw: "Je, ninaweza kusoma Uturuki bila IELTS?",
      so: "Ma waxaan ku baran karaa Turkiga iyada oo aan IELTS lahayn?",
      id: "Bisakah saya kuliah di Turki tanpa IELTS?",
    },
    answer: {
      en: "Yes. Many universities accept an internal English exam, a preparatory year or alternative certificates like TOEFL, and some programs are taught in Turkish, Arabic or Russian. Check each university language requirements before applying.",
      tr: "Evet. Birçok üniversite kurum içi İngilizce sınavı, hazırlık yılı veya TOEFL gibi alternatif sertifikalar kabul eder; bazı programlar Türkçe, Arapça veya Rusça verilir. Başvurmadan önce her üniversitenin dil şartlarını kontrol edin.",
      az: "Bəli. Bir çox universitet daxili ingilis dili imtahanı, hazırlıq ili və ya TOEFL kimi alternativ sertifikatlar qəbul edir; bəzi proqramlar türkcə, ərəbcə və ya rusca tədris olunur. Müraciət etməzdən əvvəl hər universitetin dil tələblərini yoxlayın.",
      ru: "Да. Многие вузы принимают внутренний экзамен по английскому, подготовительный год или альтернативные сертификаты вроде TOEFL; часть программ преподаётся на турецком, арабском или русском. Перед подачей заявки проверяйте языковые требования каждого вуза.",
      de: "Ja. Viele Universitäten akzeptieren eine interne Englischprüfung, ein Vorbereitungsjahr oder alternative Zertifikate wie TOEFL, und einige Programme werden auf Türkisch, Arabisch oder Russisch unterrichtet. Prüfe vor der Bewerbung die Sprachanforderungen jeder Universität.",
      fr: "Oui. De nombreuses universités acceptent un examen d'anglais interne, une année préparatoire ou des certificats alternatifs comme le TOEFL, et certains programmes sont enseignés en turc, en arabe ou en russe. Vérifiez les exigences linguistiques de chaque université avant de postuler.",
      fa: "بله. بسیاری از دانشگاهها آزمون زبان انگلیسی داخلی، سال آمادگی یا مدارک جایگزین مانند تافل میپذیرند و برخی برنامهها به ترکی، عربی یا روسی تدریس میشوند. قبل از درخواست، شرایط زبان هر دانشگاه را بررسی کنید.",
      ar: "نعم. تقبل العديد من الجامعات اختباراً داخلياً للغة الإنجليزية أو سنة تحضيرية أو شهادات بديلة مثل التوفل، وبعض البرامج تُدرَّس بالتركية أو العربية أو الروسية. تحقق من متطلبات اللغة لكل جامعة قبل التقديم.",
      tk: "Hawa. Köp uniwersitet içki iňlis dili synagyny, taýýarlyk ýylny ýa-da TOEFL ýaly alternatiw şahadatnamalary kabul edýär; käbir programmalar türk, arap ýa-da rus dilinde okadylýar. Ýüz tutmazdan öň her uniwersitetiň dil talaplaryny barlaň.",
      kk: "Иә. Көптеген университеттер ішкі ағылшын тілі емтиханын, дайындық жылын немесе TOEFL сияқты балама сертификаттарды қабылдайды; кейбір бағдарламалар түрік, араб немесе орыс тілінде оқытылады. Өтінім бермес бұрын әр университеттің тіл талаптарын тексеріңіз.",
      ky: "Ооба. Көптөгөн университеттер ички англис тили сынагын, даярдоо жылын же TOEFL сыяктуу альтернативдүү сертификаттарды кабыл алат; кээ бир программалар түрк, араб же орус тилинде окутулат. Арыз берүүдөн мурун ар бир университеттин тил талаптарын текшериңиз.",
      zh: "可以。许多大学接受校内英语考试、预科一年或托福等替代证书，部分课程用土耳其语、阿拉伯语或俄语授课。申请前请查看每所大学的语言要求。",
      bg: "Да. Много университети приемат вътрешен изпит по английски, подготвителна година или алтернативни сертификати като TOEFL, а някои програми се преподават на турски, арабски или руски. Проверете езиковите изисквания на всеки университет преди да кандидатствате.",
      ur: "جی ہاں۔ بہت سی یونیورسٹیاں اندرونی انگریزی امتحان، پریپریٹری سال یا TOEFL جیسے متبادل سرٹیفکیٹ قبول کرتی ہیں، اور کچھ پروگرام ترکی، عربی یا روسی میں پڑھائے جاتے ہیں۔ درخواست سے پہلے ہر یونیورسٹی کی زبان کی شرائط چیک کریں۔",
      uz: "Ha. Ko‘plab universitetlar ichki ingliz tili imtihonini, tayyorlov yilini yoki TOEFL kabi muqobil sertifikatlarni qabul qiladi; baʼzi dasturlar turk, arab yoki rus tillarida o‘qitiladi. Ariza topshirishdan oldin har bir universitetning til talablarini tekshiring.",
      sw: "Ndiyo. Vyuo vingi vinakubali mtihani wa ndani wa Kiingereza, mwaka wa maandalizi au vyeti mbadala kama TOEFL, na baadhi ya programu hufundishwa kwa Kituruki, Kiarabu au Kirusi. Angalia mahitaji ya lugha ya kila chuo kabla ya kuomba.",
      so: "Haa. Jaamacado badan ayaa aqbala imtixaanka Ingiriisiga ee gudaha, sannad diyaarin ah ama shahaado kale sida TOEFL, qaar barnaamijyadana waxaa lagu baraa Turkiga, Carabiga ama Ruushka. Hubi shuruudaha luqadda ee jaamacad kasta ka hor intaadan codsan.",
      id: "Ya. Banyak universitas menerima tes bahasa Inggris internal, tahun persiapan, atau sertifikat alternatif seperti TOEFL, dan sebagian program diajarkan dalam bahasa Turki, Arab, atau Rusia. Periksa persyaratan bahasa setiap universitas sebelum mendaftar.",
    },
  },
  {
    id: "f-g7",
    entityType: "general",
    entityId: "general",
    question: {
      en: "Is studying in Turkey worth it?",
      tr: "Türkiye'de okumak buna değer mi?",
      az: "Türkiyədə oxumaq buna dəyərmi?",
      ru: "Стоит ли учиться в Турции?",
      de: "Lohnt es sich, in der Türkei zu studieren?",
      fr: "Vaut-il la peine d'étudier en Turquie ?",
      fa: "آیا تحصیل در ترکیه ارزشش را دارد؟",
      ar: "هل تستحق الدراسة في تركيا ذلك؟",
      tk: "Türkiýede okamak mynasypmy?",
      kk: "Түркияда оқуға тұрарлық па?",
      ky: "Түркияда окуу татыктуубу?",
      zh: "到土耳其留学值得吗？",
      bg: "Струва ли си да уча в Турция?",
      ur: "کیا ترکی میں تعلیم حاصل کرنا قابلِ قدر ہے؟",
      uz: "Turkiyada o‘qish arziydimi?",
      sw: "Je, inafaa kusoma Uturuki?",
      so: "Ma waxaa mudan in laga barto Turkiga?",
      id: "Apakah kuliah di Turki sepadan?",
    },
    answer: {
      en: "For most international students, yes. You get YÖK-accredited degrees, tuition far below Western Europe or the US, scholarships up to 100% and a low cost of living — with strong engineering, medicine and business programs.",
      tr: "Çoğu uluslararası öğrenci için evet. YÖK akrediteli diplomalar, Batı Avrupa veya ABD'nin çok altında ücretler, %100'e varan burslar ve düşük yaşam maliyeti elde edersiniz — güçlü mühendislik, tıp ve işletme programlarıyla.",
      az: "Əksər beynəlxalq tələbələr üçün bəli. YÖK akreditəli dərəcələr, Qərbi Avropa və ya ABŞ-dan xeyli aşağı təhsil haqları, 100%-ə qədər təqaüdlər və aşağı yaşayış xərcləri — güclü mühəndislik, tibb və biznes proqramları ilə.",
      ru: "Для большинства иностранных студентов — да. Вы получаете дипломы, признаваемые YÖK, обучение гораздо дешевле, чем в Западной Европе или США, стипендии до 100% и низкую стоимость жизни — при сильных программах по инженерии, медицине и бизнесу.",
      de: "Für die meisten internationalen Studierenden ja. Du bekommst YÖK-akkreditierte Abschlüsse, Studiengebühren weit unter Westeuropa oder den USA, Stipendien bis zu 100 % und niedrige Lebenshaltungskosten — mit starken Ingenieur-, Medizin- und Wirtschaftsprogrammen.",
      fr: "Pour la plupart des étudiants internationaux, oui. Vous obtenez des diplômes accrédités YÖK, des frais de scolarité bien inférieurs à ceux de l'Europe occidentale ou des États-Unis, des bourses jusqu'à 100 % et un faible coût de la vie — avec de solides programmes d'ingénierie, de médecine et de commerce.",
      fa: "برای بیشتر دانشجویان بینالمللی، بله. مدرک معتبر YÖK، شهریه بسیار کمتر از اروپای غربی یا آمریکا، بورسیه تا ۱۰۰٪ و هزینه زندگی پایین دریافت میکنید — با برنامههای قوی مهندسی، پزشکی و بازرگانی.",
      ar: "بالنسبة لمعظم الطلاب الدوليين، نعم. تحصل على شهادات معتمدة من YÖK، ورسوم أقل بكثير من أوروبا الغربية أو الولايات المتحدة، ومنح تصل إلى 100% وتكلفة معيشة منخفضة — مع برامج قوية في الهندسة والطب والأعمال.",
      tk: "Köp halkara talyp üçin hawa. YÖK akkreditlenen diplomlary, Günbatar Europewropadan ýa-da ABŞ-dan ep-esli arzan okuw töleglerini, 100% çenli stipendiýalary we pes ýaşaýyş çykdajylaryny alýarsyňyz — güýçli inženerlik, medisina we biznes programmalary bilen.",
      kk: "Көптеген шетелдік студенттер үшін иә. Сіз YÖK аккредиттелген дипломдарды, Батыс Еуропадан немесе АҚШ-тан әлдеқайда төмен оқу ақысын, 100%-ға дейін стипендияны және төмен өмір сүру құнын аласыз — күшті инженерия, медицина және бизнес бағдарламаларымен.",
      ky: "Көпчүлүк эл аралык студенттер үчүн ооба. Сиз YÖK аккредитацияланган дипломдорду, Батыш Европадан же АКШтан алда канча арзан окуу акысын, 100% чейин стипендияны жана аз жашоо чыгымын аласыз — күчтүү инженерия, медицина жана бизнес программалары менен.",
      zh: "对大多数国际学生来说，值得。你可以获得YÖK认证的学位、远低于西欧或美国的学费、最高100%的奖学金和较低的生活成本——还有强大的工程、医学和商科课程。",
      bg: "За повечето чуждестранни студенти — да. Получавате дипломи, акредитирани от YÖK, обучение далеч по-евтино от Западна Европа или САЩ, стипендии до 100% и нисък разход за живот — със силни инженерни, медицински и бизнес програми.",
      ur: "زیادہ تر بین الاقوامی طلباء کے لیے جی ہاں۔ آپ کو YÖK تسلیم شدہ ڈگریاں، مغربی یورپ یا امریکہ سے کہیں سستی ٹیوشن، 100% تک اسکالرشپس اور کم رہائشی اخراجات ملتے ہیں — مضبوط انجینئرنگ، طب اور بزنس پروگراموں کے ساتھ۔",
      uz: "Ko‘pchilik xalqaro talabalar uchun ha. Siz YÖK akkreditatsiyali diplomlar, G‘arbiy Yevropa yoki AQShdan ancha arzon o‘qish to‘lovlari, 100%gacha stipendiyalar va past yashash xarajatlarini olasiz — kuchli muhandislik, tibbiyot va biznes dasturlari bilan.",
      sw: "Kwa wanafunzi wengi wa kimataifa, ndiyo. Unapata digrii zilizoidhinishwa na YÖK, ada za chini sana kuliko Ulaya Magharibi au Marekani, ufadhili hadi 100% na gharama ndogo za maisha — pamoja na programu imara za uhandisi, tiba na biashara.",
      so: "Ardayda caalamiga ah badankood, haa. Waxaad heshaa shahaadooyin ay aqoonsadeen YÖK, lacagaha waxbarasho oo aad uga jaban Galbeedka Yurub ama Maraykanka, deeqo ilaa 100% iyo kharash nololeed hoose — iyada oo leh barnaamijyada injineeriyadda, caafimaadka iyo ganacsiga ee xooggan.",
      id: "Bagi kebanyakan mahasiswa internasional, ya. Anda mendapatkan gelar terakreditasi YÖK, biaya kuliah jauh lebih rendah daripada Eropa Barat atau AS, beasiswa hingga 100%, dan biaya hidup rendah — dengan program teknik, kedokteran, dan bisnis yang kuat.",
    },
  },
  {
    id: "f-g8",
    entityType: "general",
    entityId: "general",
    question: {
      en: "Is a Turkish university degree recognized internationally?",
      tr: "Türk üniversite diploması uluslararası alanda tanınır mı?",
      az: "Türkiyə universitet diplomu beynəlxalq səviyyədə tanınır?",
      ru: "Признаётся ли турецкий диплом за рубежом?",
      de: "Wird ein türkischer Universitätsabschluss international anerkannt?",
      fr: "Un diplôme universitaire turc est-il reconnu à l'international ?",
      fa: "آیا مدرک دانشگاه ترکیه در سطح بینالمللی معتبر است؟",
      ar: "هل الشهادة الجامعية التركية معترف بها دولياً؟",
      tk: "Türk uniwersitet diplomyna halkara derejede ykrar edilýärmi?",
      kk: "Түрік университетінің дипломы халықаралық деңгейде таныла ма?",
      ky: "Түрк университетинин диплому эл аралык деңгээлде таанылабы?",
      zh: "土耳其大学学位在国际上被认可吗？",
      bg: "Признава ли се турската университетска диплома в чужбина?",
      ur: "کیا ترک یونیورسٹی کی ڈگری بین الاقوامی طور پر تسلیم شدہ ہے؟",
      uz: "Turkiya universiteti diplomi xalqaro miqyosda tan olinadimi?",
      sw: "Je, digrii ya chuo kikuu cha Uturuki inatambulika kimataifa?",
      so: "Ma shahaadada jaamacadda Turkiga ayaa caalami ahaan la aqoonsaday?",
      id: "Apakah gelar universitas Turki diakui secara internasional?",
    },
    answer: {
      en: "Yes. Degrees from YÖK-accredited Turkish universities are recognized across Europe, the Middle East, Africa and Asia, and many programs hold international accreditations such as ABET or AACSB.",
      tr: "Evet. YÖK akrediteli Türk üniversitelerinden alınan diplomalar Avrupa, Orta Doğu, Afrika ve Asya'da tanınır; birçok program ABET veya AACSB gibi uluslararası akreditasyonlara sahiptir.",
      az: "Bəli. YÖK akreditəli Türkiyə universitetlərinin diplomları Avropada, Yaxın Şərqdə, Afrikada və Asiyada tanınır; bir çox proqram ABET və ya AACSB kimi beynəlxalq akreditasiyalara malikdir.",
      ru: "Да. Дипломы аккредитованных YÖK турецких вузов признаются в Европе, на Ближнем Востоке, в Африке и Азии, а многие программы имеют международные аккредитации, например ABET или AACSB.",
      de: "Ja. Abschlüsse von YÖK-akkreditierten türkischen Universitäten werden in Europa, im Nahen Osten, in Afrika und Asien anerkannt, und viele Programme besitzen internationale Akkreditierungen wie ABET oder AACSB.",
      fr: "Oui. Les diplômes des universités turques accréditées YÖK sont reconnus en Europe, au Moyen-Orient, en Afrique et en Asie, et de nombreux programmes détiennent des accréditations internationales comme l'ABET ou l'AACSB.",
      fa: "بله. مدارک دانشگاههای ترکیه با اعتبار YÖK در اروپا، خاورمیانه، آفریقا و آسیا شناخته میشوند و بسیاری از برنامهها اعتبارنامههای بینالمللی مانند ABET یا AACSB دارند.",
      ar: "نعم. الشهادات من الجامعات التركية المعتمدة من YÖK معترف بها في أوروبا والشرق الأوسط وأفريقيا وآسيا، والعديد من البرامج حاصلة على اعتمادات دولية مثل ABET أو AACSB.",
      tk: "Hawa. YÖK akkreditlenen türk uniwersitetleriniň diplomlary Europewropada, Ýakyn Gündogarda, Afrikada we Aziýada tanalýar; köp programmalar ABET ýa-da AACSB ýaly halkara akkreditasiýalara eýe.",
      kk: "Иә. YÖK аккредиттелген түрік университеттерінің дипломдары Еуропада, Таяу Шығыста, Африкада және Азияда танылады; көптеген бағдарламалар ABET немесе AACSB сияқты халықаралық аккредитацияларға ие.",
      ky: "Ооба. YÖK аккредитацияланган түрк университеттеринин дипломдору Европада, Жакынкы Чыгышта, Африкада жана Азияда таанылат; көптөгөн программалар ABET же AACSB сыяктуу эл аралык аккредитацияларга ээ.",
      zh: "是的。YÖK认证的土耳其大学学位在欧洲、中东、非洲和亚洲都得到认可，许多课程还拥有ABET或AACSB等国际认证。",
      bg: "Да. Дипломите от акредитирани от YÖK турски университети се признават в Европа, Близкия изток, Африка и Азия, а много програми притежават международни акредитации като ABET или AACSB.",
      ur: "جی ہاں۔ YÖK تسلیم شدہ ترک یونیورسٹیوں کی ڈگریاں یورپ، مشرق وسطیٰ، افریقہ اور ایشیا میں تسلیم کی جاتی ہیں، اور بہت سے پروگرام ABET یا AACSB جیسی بین الاقوامی تسلیم شدگیاں رکھتے ہیں۔",
      uz: "Ha. YÖK akkreditatsiyali turk universitetlari diplomlari Yevropa, Yaqin Sharq, Afrika va Osiyoda tan olinadi; ko‘plab dasturlar ABET yoki AACSB kabi xalqaro akkreditatsiyalarga ega.",
      sw: "Ndiyo. Digrii kutoka vyuo vikuu vya Uturuki vilivyoidhinishwa na YÖK hutambulika Ulaya, Mashariki ya Kati, Afrika na Asia, na programu nyingi zina idhini za kimataifa kama ABET au AACSB.",
      so: "Haa. Shahaadooyinka jaamacadaha Turkiga ee ay aqoonsadeen YÖK ayaa laga aqoonsan yahay Yurubta, Bariga Dhexe, Afrika iyo Aasiya, qaar badan oo barnaamijyadana waxay leeyihiin aqoonsiyo caalami ah sida ABET ama AACSB.",
      id: "Ya. Gelar dari universitas Turki yang terakreditasi YÖK diakui di Eropa, Timur Tengah, Afrika, dan Asia, dan banyak program memiliki akreditasi internasional seperti ABET atau AACSB.",
    },
  },
  {
    id: "f-g9",
    entityType: "general",
    entityId: "general",
    question: {
      en: "How long does a Turkish student visa take?",
      tr: "Türk öğrenci vizesi ne kadar sürer?",
      az: "Türkiyə tələbə vizası nə qədər çəkir?",
      ru: "Сколько занимает получение турецкой студенческой визы?",
      de: "Wie lange dauert ein türkisches Studentenvisum?",
      fr: "Combien de temps faut-il pour obtenir un visa étudiant turc ?",
      fa: "دریافت ویزای دانشجویی ترکیه چقدر طول میکشد؟",
      ar: "كم تستغرق تأشيرة الطالب التركية؟",
      tk: "Türk okuwçy wizasyny almak näçe wagt alýar?",
      kk: "Түрік студенттік визасын алу қанша уақыт алады?",
      ky: "Түрк студенттик визасын алуу канча убакыт алат?",
      zh: "土耳其学生签证需要多长时间？",
      bg: "Колко време отнема турска студентска виза?",
      ur: "ترک طالب علم ویزا حاصل کرنے میں کتنا وقت لگتا ہے؟",
      uz: "Turkiya talaba vizasini olish qancha vaqt oladi?",
      sw: "Visa ya mwanafunzi ya Uturuki inachukua muda gani?",
      so: "Immisa ayay qaadataa fiisaha ardayga ee Turkiga?",
      id: "Berapa lama pengurusan visa pelajar Turki?",
    },
    answer: {
      en: "Most student visas are processed within 2 to 4 weeks after your appointment at the Turkish consulate, though it varies by country. Apply as soon as you receive your acceptance letter.",
      tr: "Çoğu öğrenci vizesi, Türk konsolosluğundaki randevunuzdan sonra 2-4 hafta içinde işleme alınır; ancak ülkeye göre değişir. Kabul mektubunuzu alır almaz başvurun.",
      az: "Əksər tələbə vizaları Türkiyə konsulluğundakı görüşünüzdən sonra 2-4 həftə ərzində işlənir, lakin ölkədən asılıdır. Qəbul məktubunuzu alan kimi müraciət edin.",
      ru: "Большинство студенческих виз оформляется за 2-4 недели после приёма в консульстве, хотя сроки зависят от страны. Подавайте заявку сразу после получения письма о зачислении.",
      de: "Die meisten Studentenvisa werden innerhalb von 2 bis 4 Wochen nach deinem Termin beim türkischen Konsulat bearbeitet, je nach Land. Beantrage es, sobald du deinen Zulassungsbrief erhältst.",
      fr: "La plupart des visas étudiants sont traités en 2 à 4 semaines après votre rendez-vous au consulat turc, selon le pays. Postulez dès réception de votre lettre d'acceptation.",
      fa: "بیشتر ویزاهای دانشجویی طی ۲ تا ۴ هفته پس از وقت کنسولگری ترکیه صادر میشوند، هرچند بسته به کشور متفاوت است. به محض دریافت نامه پذیرش درخواست دهید.",
      ar: "تُعالج معظم تأشيرات الطلاب خلال 2 إلى 4 أسابيع بعد موعدك في القنصلية التركية، رغم اختلافها حسب البلد. تقدم بطلبك فور استلام خطاب القبول.",
      tk: "Köp okuwçy wizasy türk konsullygyndaky duşuşygyňyzdan soň 2-4 hepde içinde işlenilýär, ýöne ýurda görä üýtgeýär. Kabul hatyňyzy alan badyňa ýüz tutuň.",
      kk: "Көптеген студенттік визалар түрік консулдығындағы қабылдаудан кейін 2-4 апта ішінде өңделеді, бірақ елге байланысты. Қабылдау хатын алған бойда өтінім беріңіз.",
      ky: "Көпчүлүк студенттик визалар түрк консулдугундагы кабылдоодон кийин 2-4 жума ичинде иштелип чыгат, бирок өлкөгө жараша. Кабыл алуу катын алганда эле арыз бериңиз.",
      zh: "大多数学生签证在土耳其领事馆预约后2至4周内处理完毕，但视国家而定。收到录取通知书后请尽快申请。",
      bg: "Повечето студентски визи се обработват в рамките на 2 до 4 седмици след срещата ви в турското консулство, макар че зависи от държавата. Кандидатствайте веднага след получаване на писмото за приемане.",
      ur: "زیادہ تر طالب علم ویزے ترک قونصل خانے میں آپ کی ملاقات کے بعد 2 سے 4 ہفتوں میں بن جاتے ہیں، حالانکہ ملک کے لحاظ سے مختلف ہوتا ہے۔ قبولیت کا خط ملتے ہی درخواست دیں۔",
      uz: "Ko‘pchilik talaba vizalari Turkiya konsulxonasidagi uchrashuvdan keyin 2-4 hafta ichida rasmiylashtiriladi, biroq mamlakatga qarab farq qiladi. Qabul xatini olishingiz bilanoq ariza topshiring.",
      sw: "Visa nyingi za wanafunzi huchakatwa ndani ya wiki 2 hadi 4 baada ya miadi yako kwenye ubalozi wa Uturuki, ingawa inatofautiana kwa nchi. Omba mara tu unapopokea barua yako ya kukubaliwa.",
      so: "Fiisaha ardayga badankood waxaa la sameeyaa 2 ilaa 4 toddobaad gudahood ka dib ballantaada xafiiska Turkiga, in kasta oo ay ku kala duwan tahay dalalka. Codsada isla marka aad hesho warqadda aqbalaadda.",
      id: "Sebagian besar visa pelajar diproses dalam 2 hingga 4 minggu setelah janji temu Anda di konsulat Turki, meski bervariasi menurut negara. Ajukan segera setelah menerima surat penerimaan.",
    },
  },
  // University-specific
  {
    id: "f-bau1",
    entityType: "university",
    entityId: "u-bahcesehir",
    question: {
      en: "Is Bahçeşehir University accredited internationally?",
      tr: "Bahçeşehir Üniversitesi uluslararası akredite mi?",
      az: "Bahçeşehir Universiteti beynəlxalq akreditə olunubmu?",
      ru: "Аккредитован ли Бахчешеширский университет международно?",
      de: "Ist die Bahçeşehir-Universität international akkreditiert?",
      fr: "L'université Bahçeşehir est-elle accréditée à l'international ?",
      fa: "آیا دانشگاه باغچهشهر اعتبار بینالمللی دارد؟",
      ar: "هل جامعة بهتشه شهير معتمدة دولياً؟",
      tk: "Bahçeşehir uniwersiteti halkara derejede akkreditlenenmi?",
      kk: "Бахчешехир университеті халықаралық аккредиттелген бе?",
      ky: "Bahçeşehir университети эл аралык аккредитацияга ээби?",
      zh: "巴哈切希尔大学获得国际认证吗？",
      bg: "Бахчешехирският университет международно акредитиран ли е?",
      ur: "کیا بہچہ شہر یونیورسٹی بین الاقوامی طور پر تسلیم شدہ ہے؟",
      uz: "Bahçeşehir universiteti xalqaro akkreditatsiyaga egami?",
      sw: "Je, Chuo Kikuu cha Bahçeşehir kimeidhinishwa kimataifa?",
      so: "Ma jaamacadda Bahçeşehir ayaa caalami ahaan la aqoonsaday?",
      id: "Apakah Universitas Bahçeşehir terakreditasi secara internasional?",
    },
    answer: {
      en: "Yes. It is recognised by YÖK and holds several international accreditations for its business and engineering programs.",
      tr: "Evet. YÖK tarafından tanınır ve işletme ile mühendislik programları için çeşitli uluslararası akreditasyonlara sahiptir.",
      az: "Bəli. YÖK tərəfindən tanınır və biznes və mühəndislik proqramları üçün bir neçə beynəlxalq akreditasiyaya malikdir.",
      ru: "Да. Признан YÖK и имеет ряд международных аккредитаций по бизнесу и инженерии.",
      de: "Ja. Sie wird vom YÖK anerkannt und besitzt mehrere internationale Akkreditierungen für ihre Wirtschafts- und Ingenieurprogramme.",
      fr: "Oui. Elle est reconnue par le YÖK et possède plusieurs accréditations internationales pour ses programmes de commerce et d'ingénierie.",
      fa: "بله. توسط YÖK به رسمیت شناخته شده و برای برنامههای تجاری و مهندسی خود چندین اعتبار بینالمللی دارد.",
      ar: "نعم. معترف بها من قبل YÖK ولديها عدة اعتمادات دولية لبرامجها في الأعمال والهندسة.",
      tk: "Hawa. YÖK tarapyndan tanalýar we biznes we inženerlik programmalary üçin birnäçe halkara akkreditasiýasyna eýedir.",
      kk: "Иә. YÖK таныған және бизнес пен инженерия бағдарламалары үшін бірнеше халықаралық аккредитацияға ие.",
      ky: "Ооба. YÖK тарабынан таанылган жана бизнес жана инженерия программалары үчүн бир нече эл аралык аккредитацияга ээ.",
      zh: "是的。该校获得YÖK认可，其商科和工程课程拥有多项国际认证。",
      bg: "Да. Признат е от YÖK и има няколко международни акредитации за бизнес и инженерни програми.",
      ur: "جی ہاں۔ اسے YÖK تسلیم کرتا ہے اور اس کے بزنس اور انجینئرنگ پروگراموں کے لیے کئی بین الاقوامی تسلیم شدگیاں ہیں۔",
      uz: "Ha. U YÖK tomonidan tan olingan va biznes hamda muhandislik dasturlari uchun bir qancha xalqaro akkreditatsiyalarga ega.",
      sw: "Ndiyo. Inatambulika na YÖK na ina idhini nyingi za kimataifa kwa programu zake za biashara na uhandisi.",
      so: "Haa. Waxaa aqoonsaday YÖK waxayna u haysaa dhowr aqoonsi caalami ah oo loogu talagalay barnaamijyada ganacsiga iyo injineeriyada.",
      id: "Ya. Diakui oleh YÖK dan memiliki beberapa akreditasi internasional untuk program bisnis dan tekniknya.",
    },
  },
  {
    id: "f-metu1",
    entityType: "university",
    entityId: "u-metu",
    question: {
      en: "Does METU offer accommodation on campus?",
      tr: "ODTÜ kampüste konaklama sunuyor mu?",
      az: "ODTÜ kampusda qalma yeri təklif edirmi?",
      ru: "Предоставляет ли ODTÜ проживание на кампусе?",
      de: "Bietet die METU Unterkunft auf dem Campus?",
      fr: "L'ODTÜ propose-t-il un logement sur le campus ?",
      fa: "آیا ODTÜ اقامتگاه درون دانشگاه ارائه میدهد؟",
      ar: "هل توفر ODTÜ سكناً داخل الحرم الجامعي؟",
      tk: "ODTÜ kampusda ýaşaýyş hödürleýärmi?",
      kk: "ODTÜ кампуста тұрғын үй ұсына ма?",
      ky: "ODTÜ кампуста турак-жай сунуштайбы?",
      zh: "中东技术大学提供校内住宿吗？",
      bg: "Предлага ли ODTÜ настаняване в кампуса?",
      ur: "کیا ODTÜ کیمپس میں رہائش فراہم کرتی ہے؟",
      uz: "ODTÜ kampusda yashash joyini taklif qiladimi?",
      sw: "Je, ODTÜ inatoa malazi kwenye kampasi?",
      so: "Ma ODTÜ waxay bixisaa hoy gudaha kambaska?",
      id: "Apakah ODTÜ menyediakan akomodasi di kampus?",
    },
    answer: {
      en: "Yes. METU has one of the largest dormitory capacities in Turkey, with affordable on-campus housing for students.",
      tr: "Evet. ODTÜ, Türkiye'nin en büyük yurt kapasitelerinden birine sahiptir ve uygun fiyatlı kampüs içi konaklama sunar.",
      az: "Bəli. ODTÜ Türkiyənin ən böyük yataqxana tutumlarından birinə malikdir və tələbələr üçün uyğun qiymətli kampus içi qalma yeri təklif edir.",
      ru: "Да. В ODTÜ одно из крупнейших общежитий в Турции с доступным проживанием на кампусе.",
      de: "Ja. Die METU verfügt über eine der größten Wohnheimkapazitäten der Türkei mit erschwinglicher Unterkunft auf dem Campus.",
      fr: "Oui. L'ODTÜ possède l'une des plus grandes capacités de dortoirs de Turquie, avec un logement abordable sur le campus.",
      fa: "بله. ODTÜ یکی از بزرگترین ظرفیتهای خوابگاهی ترکیه را دارد و اقامت درون دانشگاه با هزینه مناسب ارائه میدهد.",
      ar: "نعم. تمتلك ODTÜ واحدة من أكبر سعات السكن الطلابي في تركيا مع إقامة ميسورة داخل الحرم.",
      tk: "Hawa. ODTÜ Türkiýäniň iň uly ýatakhana kuwwatlaryndan birine eýedir we kampus içinde elýeterli ýaşaýyş hödürleýär.",
      kk: "Иә. ODTÜ Түркиядағы ең үлкен жатақхана сыйымдылығының біріне ие және кампуста қолжетімді тұрғын үй ұсынады.",
      ky: "Ооба. ODTÜ Түркиядагы эң чоң жатакана сыйымдуулуктарынын бирине ээ жана кампуста жеткиликтүү турак-жай сунуштайт.",
      zh: "是的。中东技术大学拥有土耳其最大的宿舍容量之一，为学生提供实惠的校内住宿。",
      bg: "Да. ODTÜ има един от най-големите общежития в Турция с достъпно настаняване в кампуса.",
      ur: "جی ہاں۔ ODTÜ ترکی کے سب سے بڑے ہاسٹل میں سے ایک رکھتی ہے جس میں طلباء کے لیے سستی رہائش ہے۔",
      uz: "Ha. ODTÜ Turkiyadagi eng katta yotoqxona quvvatlaridan biriga ega va talabalar uchun kampusda qulay narxlarda yashashni taklif qiladi.",
      sw: "Ndiyo. ODTÜ ina moja ya uwezo mkubwa zaidi wa mabweni nchini Uturuki, ikiwa na malazi ya bei nafuu kwenye kampasi.",
      so: "Haa. ODTÜ waxay leedahay mid ka mid ah awoodaha ugu weyn ee hostelka ee Turkiga, iyadoo bixisay hoy ku habboon oo kambaska ah.",
      id: "Ya. ODTÜ memiliki salah satu kapasitas asrama terbesar di Turki dengan akomodasi di kampus yang terjangkau.",
    },
  },
  {
    id: "f-itu1",
    entityType: "university",
    entityId: "u-itu",
    question: {
      en: "Does Istanbul Technical University teach engineering programs in English?",
      tr: "İstanbul Teknik Üniversitesi mühendislik programlarını İngilizce mi veriyor?",
      az: "İstanbul Texniki Universiteti mühəndislik proqramlarını ingilis dilində tədris edirmi?",
      ru: "Преподаёт ли Стамбульский технический университет инженерные программы на английском?",
      de: "Bietet die Technische Universität Istanbul Ingenieurprogramme auf Englisch an?",
      fr: "L'Université technique d'Istanbul enseigne-t-elle ses programmes d'ingénierie en anglais ?",
      fa: "آیا دانشگاه فنی استانبول برنامههای مهندسی را به زبان انگلیسی ارائه میدهد؟",
      ar: "هل تدرّس جامعة إسطنبول التقنية برامج الهندسة باللغة الإنجليزية؟",
      tk: "Stambul tehniki uniwersiteti inženerlik programmalaryny iňlis dilinde okadýarmy?",
      kk: "Ыстамбұл техникалық университеті инженерлік бағдарламаларды ағылшын тілінде оқыта ма?",
      ky: "Стамбул техникалык университети инженерия программаларын англис тилинде окутабы?",
      zh: "伊斯坦布尔技术大学的工程课程用英语授课吗？",
      bg: "Преподава ли Истанбулският технически университет инженерни програми на английски?",
      ur: "کیا استنبول ٹیکنیکل یونیورسٹی انجینئرنگ پروگرام انگریزی میں پڑھاتی ہے؟",
      uz: "Istanbul texnika universiteti muhandislik dasturlarini ingliz tilida o‘qitadimi?",
      sw: "Je, Chuo Kikuu cha Ufundi cha Istanbul kinafundisha programu za uhandisi kwa Kiingereza?",
      so: "Ma Jaamacadda Farsanada ee Istanbul waxay baraan barnaamijyada injineeriyadda Ingiriisiga?",
      id: "Apakah Universitas Teknik Istanbul mengajarkan program teknik dalam bahasa Inggris?",
    },
    answer: {
      en: "Yes. ITU is one of Turkey's oldest and strongest technical universities, with many undergraduate engineering programs taught fully in English and a global reputation for engineering and architecture.",
      tr: "Evet. İTÜ, Türkiye'nin en köklü ve güçlü teknik üniversitelerinden biridir; birçok lisans mühendislik programı tamamen İngilizce verilir ve mühendislik ile mimarlıkta küresel bir üne sahiptir.",
      az: "Bəli. İTÜ Türkiyənin ən qədim və güclü texniki universitetlərindən biridir; bir çox bakalavr mühəndislik proqramı tamamilə ingilis dilində tədris olunur və mühəndislik və memarlıq sahəsində qlobal reputasiyaya malikdir.",
      ru: "Да. ИТУ — один из старейших и сильнейших технических вузов Турции; многие инженерные программы бакалавриата полностью на английском, а вуз имеет мировую репутацию в инженерии и архитектуре.",
      de: "Ja. Die ITU ist eine der ältesten und stärksten technischen Universitäten der Türkei; viele Ingenieurstudiengänge werden vollständig auf Englisch unterrichtet, mit weltweitem Ruf in Ingenieurwesen und Architektur.",
      fr: "Oui. L'ITU est l'une des plus anciennes et des plus solides universités techniques de Turquie ; de nombreux programmes d'ingénierie de premier cycle sont entièrement en anglais, avec une réputation mondiale en ingénierie et en architecture.",
      fa: "بله. ITU یکی از قدیمیترین و قویترین دانشگاههای فنی ترکیه است؛ بسیاری از برنامههای مهندسی کارشناسی کاملاً به انگلیسی تدریس میشوند و در مهندسی و معماری شهرت جهانی دارد.",
      ar: "نعم. تعد ITU من أقدم وأقوى الجامعات التقنية في تركيا؛ تُدرَّس العديد من برامج الهندسة الجامعية بالكامل بالإنجليزية، ولها سمعة عالمية في الهندسة والعمارة.",
      tk: "Hawa. ITU Türkiýäniň iň gadymy we güýçli tehniki uniwersitetlerinden biridir; köp bakalawr inženerlik programmalary doly iňlis dilinde okadylýar we inženerlik we arhitektura boýunça dünýä abraýyna eýedir.",
      kk: "Иә. ITU Түркиядағы ең көне әрі мықты техникалық университеттердің бірі; көптеген бакалавриат инженерлік бағдарламалар толығымен ағылшын тілінде оқытылады, инженерия мен сәулетте әлемдік беделге ие.",
      ky: "Ооба. ITU Түркиядагы эң байыркы жана күчтүү техникалык университеттердин бири; көптөгөн бакалавр инженерия программалары толугу менен англис тилинде окутулат жана инженерия менен архитектурада дүйнөлүк абройго ээ.",
      zh: "是的。伊斯坦布尔技术大学是土耳其历史最悠久、实力最强的理工大学之一，许多本科工程课程完全用英语授课，在工程和建筑领域享有全球声誉。",
      bg: "Да. ИТУ е един от най-старите и силни технически университети в Турция; много инженерни програми се преподават изцяло на английски и има световна репутация в инженерството и архитектурата.",
      ur: "جی ہاں۔ ITU ترکی کی قدیم ترین اور مضبوط ترین تکنیکی یونیورسٹیوں میں سے ایک ہے؛ بہت سے انڈرگریجویٹ انجینئرنگ پروگرام مکمل طور پر انگریزی میں پڑھائے جاتے ہیں اور انجینئرنگ و فن تعمیر میں عالمی شہرت رکھتی ہے۔",
      uz: "Ha. ITU Turkiyaning eng qadimgi va kuchli texnika universitetlaridan biri; ko‘plab bakalavriat muhandislik dasturlari to‘liq ingliz tilida o‘qitiladi va muhandislik hamda arxitektura sohasida jahon miqyosida obro‘ga ega.",
      sw: "Ndiyo. ITU ni mojawapo ya vyuo vikuu vya zamani na vyenye nguvu zaidi vya ufundi nchini Uturuki; programu nyingi za uhandisi za shahada ya kwanza hufundishwa kwa Kiingereza kabisa na ina sifa ya kimataifa katika uhandisi na usanifu wa majengo.",
      so: "Haa. ITU waa mid ka mid ah jaamacadaha ugu da'da weyn uguna xooggan ee farsanada ee Turkiga; barnaamijyo badan oo injineeriyadda heerka koowaad ayaa si buuxda Ingiriisiga loogu baraa waxayna leedahay sumcad caalami ah injineeriyadda iyo naqshadda.",
      id: "Ya. ITU adalah salah satu universitas teknik tertua dan terkuat di Turki; banyak program teknik sarjana diajarkan sepenuhnya dalam bahasa Inggris dan memiliki reputasi global di bidang teknik dan arsitektur.",
    },
  },
  {
    id: "f-bogazici1",
    entityType: "university",
    entityId: "u-bogazici",
    question: {
      en: "Is Boğaziçi University good for international students?",
      tr: "Boğaziçi Üniversitesi uluslararası öğrenciler için iyi mi?",
      az: "Boğaziçi Universiteti beynəlxalq tələbələr üçün yaxşıdırmı?",
      ru: "Подходит ли Босфорский университет иностранным студентам?",
      de: "Ist die Boğaziçi-Universität gut für internationale Studierende?",
      fr: "L'université Boğaziçi est-elle bonne pour les étudiants internationaux ?",
      fa: "آیا دانشگاه بغازچی برای دانشجویان بینالمللی خوب است؟",
      ar: "هل جامعة بوغازيتشي جيدة للطلاب الدوليين؟",
      tk: "Boğaziçi uniwersiteti halkara talyplar üçin gowumy?",
      kk: "Боғазичи университеті шетелдік студенттерге жақсы ма?",
      ky: "Boğaziçi университети эл аралык студенттер үчүн жакшыбы?",
      zh: "博阿齐奇大学对国际学生好吗？",
      bg: "Подходящ ли е университетът Боазиджи за чуждестранни студенти?",
      ur: "کیا بوغازیچی یونیورسٹی بین الاقوامی طلباء کے لیے اچھی ہے؟",
      uz: "Boğaziçi universiteti xalqaro talabalar uchun yaxshimi?",
      sw: "Je, Chuo Kikuu cha Boğaziçi ni kizuri kwa wanafunzi wa kimataifa?",
      so: "Ma jaamacadda Boğaziçi ayaa u fiican ardayda caalamiga ah?",
      id: "Apakah Universitas Boğaziçi bagus untuk mahasiswa internasional?",
    },
    answer: {
      en: "Yes. Boğaziçi is consistently ranked among Turkey's top universities, with strong English-medium programs, an international campus community and a high reputation for engineering, social sciences and business.",
      tr: "Evet. Boğaziçi sürekli Türkiye'nin en iyi üniversiteleri arasında yer alır; güçlü İngilizce programlar, uluslararası bir kampüs topluluğu ve mühendislik, sosyal bilimler ve işletmede yüksek bir itibar sunar.",
      az: "Bəli. Boğaziçi daim Türkiyənin ən yaxşı universitetləri arasında yer alır; güclü ingilisdilli proqramlar, beynəlxalq kampus birliyi və mühəndislik, sosial elmlər və biznes sahəsində yüksək reputasiya təklif edir.",
      ru: "Да. Босфорский университет стабильно входит в число лучших вузов Турции: сильные англоязычные программы, международный кампус и высокая репутация в инженерии, социальных науках и бизнесе.",
      de: "Ja. Die Boğaziçi-Universität zählt durchgehend zu den besten Universitäten der Türkei — mit starken englischsprachigen Programmen, einer internationalen Campusgemeinschaft und hohem Ansehen in Ingenieurwesen, Sozialwissenschaften und Wirtschaft.",
      fr: "Oui. Boğaziçi figure régulièrement parmi les meilleures universités de Turquie, avec de solides programmes en anglais, une communauté de campus internationale et une grande réputation en ingénierie, sciences sociales et commerce.",
      fa: "بله. بغازچی بهطور مداوم در میان برترین دانشگاههای ترکیه قرار دارد؛ برنامههای قوی انگلیسی، جامعه بینالمللی دانشگاهی و شهرت بالا در مهندسی، علوم اجتماعی و تجارت.",
      ar: "نعم. تتصدر بوغازيتشي باستمرار قائمة أفضل الجامعات التركية، مع برامج إنجليزية قوية، ومجتمع جامعي دولي، وسمعة عالية في الهندسة والعلوم الاجتماعية والأعمال.",
      tk: "Hawa. Boğaziçi yzygiderli Türkiýäniň iň gowy uniwersitetleriniň hatarynda; güýçli iňlis programmalary, halkara kampus jemgyýeti we inženerlik, jemgyýetçilik ylymlary we biznes boýunça ýokary abraý hödürleýär.",
      kk: "Иә. Боғазичи үнемі Түркияның үздік университеттерінің қатарында; күшті ағылшын тілді бағдарламалар, халықаралық кампус қоғамдастығы және инженерия, әлеуметтік ғылымдар мен бизнесте жоғары бедел.",
      ky: "Ооба. Boğaziçi дайыма Түркиянын эң мыкты университеттеринин катарында; күчтүү англис программалары, эл аралык кампус коомчулугу жана инженерия, социалдык илимдер жана бизнес тармагында жогорку аброй.",
      zh: "是的。博阿齐奇大学一直位列土耳其顶尖大学之列，拥有强大的英语授课课程、国际化的校园社区，并在工程、社会科学和商科领域享有盛誉。",
      bg: "Да. Боазиджи постоянно е сред най-добрите университети в Турция — със силни англоезични програми, международна кампус общност и висока репутация в инженерството, социалните науки и бизнеса.",
      ur: "جی ہاں۔ بوغازیچی مسلسل ترکی کی بہترین یونیورسٹیوں میں شمار ہوتی ہے — مضبوط انگریزی پروگرام، بین الاقوامی کیمپس کمیونٹی اور انجینئرنگ، سماجی علوم اور کاروبار میں بلند شہرت۔",
      uz: "Ha. Boğaziçi doimiy ravishda Turkiyaning eng yaxshi universitetlari qatorida; kuchli ingliz tilidagi dasturlar, xalqaro kampus jamoasi hamda muhandislik, ijtimoiy fanlar va biznes sohasida yuqori obro‘ga ega.",
      sw: "Ndiyo. Boğaziçi ni mara kwa mara miongoni mwa vyuo vikuu bora vya Uturuki, ikiwa na programu imara za Kiingereza, jumuiya ya kimataifa ya kampasi na sifa kubwa katika uhandisi, sayansi za jamii na biashara.",
      so: "Haa. Boğaziçi si joogto ah ka mid ah jaamacadaha ugu wanaagsan ee Turkiga; barnaamijyo Ingiriisi oo xooggan, bulsho kambas oo caalami ah iyo sumcad sare injineeriyadda, cilmiga bulshada iyo ganacsiga.",
      id: "Ya. Boğaziçi secara konsisten termasuk universitas terbaik di Turki, dengan program bahasa Inggris yang kuat, komunitas kampus internasional, dan reputasi tinggi di bidang teknik, ilmu sosial, dan bisnis.",
    },
  },
  {
    id: "f-ankara1",
    entityType: "university",
    entityId: "u-ankara",
    question: {
      en: "Does Ankara University offer programs in English?",
      tr: "Ankara Üniversitesi İngilizce programlar sunuyor mu?",
      az: "Ankara Universiteti ingilis dilində proqramlar təklif edirmi?",
      ru: "Есть ли в Университете Анкары программы на английском?",
      de: "Bietet die Universität Ankara Programme auf Englisch an?",
      fr: "L'Université d'Ankara propose-t-elle des programmes en anglais ?",
      fa: "آیا دانشگاه آنکارا برنامههای انگلیسی ارائه میدهد؟",
      ar: "هل تقدم جامعة أنقرة برامج باللغة الإنجليزية؟",
      tk: "Ankara uniwersiteti iňlis dilinde programmalary hödürleýärmi?",
      kk: "Анкара университеті ағылшын тілінде бағдарламалар ұсына ма?",
      ky: "Ankara университети англис тилинде программалар сунуштайбы?",
      zh: "安卡拉大学提供英语授课课程吗？",
      bg: "Предлага ли Анкарският университет програми на английски?",
      ur: "کیا انقرہ یونیورسٹی انگریزی میں پروگرام پیش کرتی ہے؟",
      uz: "Anqara universiteti ingliz tilida dasturlar taklif qiladimi?",
      sw: "Je, Chuo Kikuu cha Ankara kinatoa programu za Kiingereza?",
      so: "Ma jaamacadda Ankara waxay bixisaa barnaamijyo Ingiriisi ah?",
      id: "Apakah Universitas Ankara menawarkan program berbahasa Inggris?",
    },
    answer: {
      en: "Yes. Ankara University is one of Turkey's oldest and largest state universities. It offers several English-taught programs — especially in medicine, veterinary medicine and engineering — at an affordable public tuition rate.",
      tr: "Evet. Ankara Üniversitesi, Türkiye'nin en köklü ve en büyük devlet üniversitelerinden biridir. Özellikle tıp, veterinerlik ve mühendislikte İngilizce eğitim veren programlar sunar — uygun devlet ücretiyle.",
      az: "Bəli. Ankara Universiteti Türkiyənin ən qədim və ən böyük dövlət universitetlərindən biridir. Xüsusilə tibb, baytarlıq və mühəndislik sahələrində ingilis dilində tədris olunan proqramlar təklif edir — münasib dövlət təhsil haqqı ilə.",
      ru: "Да. Университет Анкары — один из старейших и крупнейших государственных вузов Турции. Он предлагает несколько программ на английском — особенно по медицине, ветеринарии и инженерии — по доступной государственной цене.",
      de: "Ja. Die Universität Ankara ist eine der ältesten und größten staatlichen Universitäten der Türkei. Sie bietet mehrere englischsprachige Programme an — besonders in Medizin, Tiermedizin und Ingenieurwesen — zu günstigen staatlichen Gebühren.",
      fr: "Oui. L'Université d'Ankara est l'une des plus anciennes et des plus grandes universités publiques de Turquie. Elle propose plusieurs programmes en anglais — notamment en médecine, médecine vétérinaire et ingénierie — à un tarif public abordable.",
      fa: "بله. دانشگاه آنکارا یکی از قدیمیترین و بزرگترین دانشگاههای دولتی ترکیه است. چندین برنامه انگلیسی — بهویژه در پزشکی، دامپزشکی و مهندسی — با شهریه دولتی مقرونبهصرفه ارائه میدهد.",
      ar: "نعم. جامعة أنقرة من أقدم وأكبر الجامعات الحكومية في تركيا. تقدم عدة برامج بالإنجليزية — خاصة في الطب والطب البيطري والهندسة — برسوم حكومية ميسورة.",
      tk: "Hawa. Ankara uniwersiteti Türkiýäniň iň gadymy we iň uly döwlet uniwersitetlerinden biridir. Esasan lukmançylyk, weterinariýa we inženerlik boýunça iňlis dilinde okadylýan programmalary hödürleýär — elýeterli döwlet tölegi bilen.",
      kk: "Иә. Анкара университеті — Түркиядағы ең көне әрі ірі мемлекеттік университеттердің бірі. Ол ағылшын тілінде бірнеше бағдарлама ұсынады — әсіресе медицина, ветеринария және инженерия — қолжетімді мемлекеттік ақымен.",
      ky: "Ооба. Ankara университети Түркиядагы эң байыркы жана эң ири мамлекеттик университеттердин бири. Ал англис тилинде бир нече программаны сунуштайт — өзгөчө медицина, ветеринария жана инженерия — жеткиликтүү мамлекеттик акы менен.",
      zh: "是的。安卡拉大学是土耳其历史最悠久、规模最大的公立大学之一，提供多门英语授课课程——尤其是医学、兽医学和工程学——学费低廉。",
      bg: "Да. Анкарският университет е един от най-старите и най-големи държавни университети в Турция. Предлага няколко програми на английски — особено по медицина, ветеринарна медицина и инженерство — на достъпна държавна такса.",
      ur: "جی ہاں۔ انقرہ یونیورسٹی ترکی کی قدیم ترین اور سب سے بڑی سرکاری یونیورسٹیوں میں سے ایک ہے۔ یہ کئی انگریزی پروگرام پیش کرتی ہے — خاص طور پر طب، ویٹرنری اور انجینئرنگ میں — سستی سرکاری فیس پر۔",
      uz: "Ha. Anqara universiteti Turkiyaning eng qadimgi va eng yirik davlat universitetlaridan biri. U ingliz tilida bir nechta dasturlarni taklif qiladi — ayniqsa tibbiyot, veterinariya va muhandislik — arzon davlat to‘lovi bilan.",
      sw: "Ndiyo. Chuo Kikuu cha Ankara ni mojawapo ya vyuo vikuu vya zamani na vikubwa zaidi vya umma nchini Uturuki. Kinatoa programu kadhaa za Kiingereza — hasa katika tiba, tiba ya mifugo na uhandisi — kwa ada nafuu ya umma.",
      so: "Haa. Jaamacadda Ankara waa mid ka mid ah jaamacadaha ugu da'da weyn uguna waaweyn ee dawladda ee Turkiga. Waxay bixisaa dhowr barnaamij oo Ingiriisi ah — gaar ahaan caafimaadka, caafimaadka xoolaha iyo injineeriyadda — qiimo dawladeed la awoodi karo.",
      id: "Ya. Universitas Ankara adalah salah satu universitas negeri tertua dan terbesar di Turki. Universitas ini menawarkan beberapa program berbahasa Inggris — terutama kedokteran, kedokteran hewan, dan teknik — dengan biaya publik yang terjangkau.",
    },
  },
  {
    id: "f-izmir-econ1",
    entityType: "university",
    entityId: "u-izmir-econ",
    question: {
      en: "Does Izmir University of Economics offer scholarships to international students?",
      tr: "İzmir Ekonomi Üniversitesi uluslararası öğrencilere burs sunuyor mu?",
      az: "İzmir İqtisadiyyat Universiteti beynəlxalq tələbələrə təqaüd təklif edirmi?",
      ru: "Предоставляет ли Университет экономики Измира стипендии иностранным студентам?",
      de: "Bietet die Wirtschaftsuniversität Izmir Stipendien für internationale Studierende an?",
      fr: "L'Université d'économie d'Izmir offre-t-elle des bourses aux étudiants internationaux ?",
      fa: "آیا دانشگاه اقتصاد ازمیر به دانشجویان بینالمللی بورسیه میدهد؟",
      ar: "هل تقدم جامعة إزمير للاقتصاد منحاً للطلاب الدوليين؟",
      tk: "Izmir Ykdysadyýet uniwersiteti halkara talyplara stipendiýa hödürleýärmi?",
      kk: "Измир экономика университеті шетелдік студенттерге стипендия ұсына ма?",
      ky: "Izmir экономика университети эл аралык студенттерге стипендия сунуштайбы?",
      zh: "伊兹密尔经济大学为国际学生提供奖学金吗？",
      bg: "Предлага ли Икономическият университет в Измир стипендии на чуждестранни студенти?",
      ur: "کیا ازمیر یونیورسٹی آف اکنامکس بین الاقوامی طلباء کو اسکالرشپ دیتی ہے؟",
      uz: "Izmir Iqtisodiyot universiteti xalqaro talabalarga stipendiya taklif qiladimi?",
      sw: "Je, Chuo Kikuu cha Uchumi cha Izmir kinatoa ufadhili kwa wanafunzi wa kimataifa?",
      so: "Ma jaamacadda dhaqaalaha ee Izmir waxay siisaa deeqo ardayda caalamiga ah?",
      id: "Apakah Universitas Ekonomi Izmir menawarkan beasiswa kepada mahasiswa internasional?",
    },
    answer: {
      en: "Yes. As a private foundation university, Izmir University of Economics offers merit scholarships and discounts for international students, and most of its programs are taught in English.",
      tr: "Evet. Bir vakıf üniversitesi olan İzmir Ekonomi Üniversitesi, uluslararası öğrencilere başarı bursları ve indirimler sunar; programlarının çoğu İngilizce verilir.",
      az: "Bəli. Fond universiteti olan İzmir İqtisadiyyat Universiteti beynəlxalq tələbələrə nailiyyət təqaüdləri və endirimlər təklif edir; proqramlarının əksəriyyəti ingilis dilində tədris olunur.",
      ru: "Да. Как частный фондовый университет, Университет экономики Измира предлагает иностранным студентам стипендии за успехи и скидки; большинство программ преподаётся на английском.",
      de: "Ja. Als private Stiftungsuniversität bietet die Wirtschaftsuniversität Izmir internationalen Studierenden Leistungsstipendien und Rabatte; die meisten Programme werden auf Englisch unterrichtet.",
      fr: "Oui. En tant qu'université privée à but non lucratif, l'Université d'économie d'Izmir offre des bourses au mérite et des réductions aux étudiants internationaux ; la plupart de ses programmes sont en anglais.",
      fa: "بله. دانشگاه اقتصاد ازمیر بهعنوان دانشگاه خصوصی، بورسیههای شایستگی و تخفیفهایی به دانشجویان بینالمللی ارائه میدهد و بیشتر برنامههای آن به انگلیسی تدریس میشود.",
      ar: "نعم. بصفتها جامعة أهلية، تقدم جامعة إزمير للاقتصاد منحاً استحقاقية وخصومات للطلاب الدوليين، ومعظم برامجها باللغة الإنجليزية.",
      tk: "Hawa. Hususy fond uniwersiteti hökmünde Izmir Ykdysadyýet uniwersiteti halkara talyplara başaryş stipendiýalaryny we endirimleri hödürleýär; programmalarynyň köpüsi iňlis dilinde.",
      kk: "Иә. Жеке қор университеті ретінде Измир экономика университеті шетелдік студенттерге жетістік стипендиялары мен жеңілдіктер ұсынады; бағдарламалардың көпшілігі ағылшын тілінде.",
      ky: "Ооба. Жеке фонд университети катарында Izmir экономика университети эл аралык студенттерге жетишкендик стипендияларын жана арзандатууларды сунуштайт; программалардын көпчүлүгү англис тилинде.",
      zh: "是的。作为一所私立基金会大学，伊兹密尔经济大学为国际学生提供成绩奖学金和折扣，大部分课程用英语授课。",
      bg: "Да. Като частен университет, Икономическият университет в Измир предлага стипендии за успех и отстъпки на чуждестранни студенти; повечето програми се преподават на английски.",
      ur: "جی ہاں۔ نجی فاؤنڈیشن یونیورسٹی ہونے کے ناطے، ازمیر یونیورسٹی آف اکنامکس بین الاقوامی طلباء کو میرٹ اسکالرشپس اور رعایتیں دیتی ہے؛ اس کے زیادہ تر پروگرام انگریزی میں ہیں۔",
      uz: "Ha. Xususiy fond universiteti sifatida Izmir Iqtisodiyot universiteti xalqaro talabalarga merit stipendiyalari va chegirmalar taklif qiladi; dasturlarining ko‘pchiligi ingliz tilida.",
      sw: "Ndiyo. Kama chuo kikuu cha kibinafsi, Chuo Kikuu cha Uchumi cha Izmir kinatoa ufadhili wa sifa na punguzo kwa wanafunzi wa kimataifa; programu zake nyingi hufundishwa kwa Kiingereza.",
      so: "Haa. Iyadoo jaamacad gaar ah, jaamacadda dhaqaalaha ee Izmir waxay siisaa deeqo mudnimo iyo qiimo dhimis ardayda caalamiga ah; barnaamijyadeeda badankoodna waxaa lagu baraa Ingiriisiga.",
      id: "Ya. Sebagai universitas yayasan swasta, Universitas Ekonomi Izmir menawarkan beasiswa prestasi dan diskon kepada mahasiswa internasional; sebagian besar programnya diajarkan dalam bahasa Inggris.",
    },
  },
  {
    id: "f-ytu1",
    entityType: "university",
    entityId: "u-ytu",
    question: {
      en: "Does Yıldız Technical University teach programs in English?",
      tr: "Yıldız Teknik Üniversitesi İngilizce programlar veriyor mu?",
      az: "Yıldız Texniki Universiteti ingilis dilində proqramlar tədris edirmi?",
      ru: "Есть ли в Техническом университете Йылдыз программы на английском?",
      de: "Bietet die Yıldız-Technische Universität Programme auf Englisch an?",
      fr: "L'Université technique de Yıldız enseigne-t-elle des programmes en anglais ?",
      fa: "آیا دانشگاه فنی یلدیز برنامههای انگلیسی ارائه میدهد؟",
      ar: "هل تقدم جامعة يلدز التقنية برامج باللغة الإنجليزية؟",
      tk: "Ýyldyz tehniki uniwersiteti iňlis dilinde programmalary okadýarmy?",
      kk: "Йылдыз техникалық университеті ағылшын тілінде бағдарламалар оқыта ма?",
      ky: "Yıldız техникалык университети англис тилинде программалар окутабы?",
      zh: "耶尔德兹理工大学用英语授课吗？",
      bg: "Преподава ли Техническият университет Йълдъз програми на английски?",
      ur: "کیا یلدز ٹیکنیکل یونیورسٹی انگریزی میں پروگرام پڑھاتی ہے؟",
      uz: "Yıldız texnika universiteti ingliz tilida dasturlar o‘qitadimi?",
      sw: "Je, Chuo Kikuu cha Ufundi cha Yıldız kinafundisha programu kwa Kiingereza?",
      so: "Ma jaamacadda farsanada ee Yıldız waxay ku baraa barnaamijyo Ingiriisiga?",
      id: "Apakah Universitas Teknik Yıldız mengajarkan program dalam bahasa Inggris?",
    },
    answer: {
      en: "Yes. Yıldız Technical University offers English-medium programs in engineering and other fields, and as a public university it keeps tuition affordable for international students.",
      tr: "Evet. Yıldız Teknik Üniversitesi mühendislik ve diğer alanlarda İngilizce programlar sunar; devlet üniversitesi olarak uluslararası öğrenciler için ücretleri uygun tutar.",
      az: "Bəli. Yıldız Texniki Universiteti mühəndislik və digər sahələrdə ingilisdilli proqramlar təklif edir; dövlət universiteti olaraq beynəlxalq tələbələr üçün təhsil haqqını münasib saxlayır.",
      ru: "Да. Технический университет Йылдыз предлагает программы на английском по инженерии и другим направлениям, а как государственный вуз держит доступные цены для иностранных студентов.",
      de: "Ja. Die Yıldız-Technische Universität bietet englischsprachige Programme in Ingenieurwesen und weiteren Fächern an und hält als staatliche Universität die Gebühren für internationale Studierende erschwinglich.",
      fr: "Oui. L'Université technique de Yıldız propose des programmes en anglais en ingénierie et dans d'autres domaines, et en tant qu'université publique elle maintient des frais abordables pour les étudiants internationaux.",
      fa: "بله. دانشگاه فنی یلدیز برنامههای انگلیسی در مهندسی و سایر رشتهها ارائه میدهد و بهعنوان دانشگاه دولتی شهریه را برای دانشجویان بینالمللی مقرونبهصرفه نگه میدارد.",
      ar: "نعم. تقدم جامعة يلدز التقنية برامج بالإنجليزية في الهندسة ومجالات أخرى، وبصفتها جامعة حكومية تُبقي الرسوم في متناول الطلاب الدوليين.",
      tk: "Hawa. Ýyldyz tehniki uniwersiteti inženerlik we beýleki ugurlarda iňlis dilindäki programmalary hödürleýär we döwlet uniwersiteti hökmünde halkara talyplar üçin tölegleri elýeterli saklaýar.",
      kk: "Иә. Йылдыз техникалық университеті инженерия және басқа салаларда ағылшын тілді бағдарламалар ұсынады және мемлекеттік университет ретінде шетелдік студенттерге ақыны қолжетімді ұстайды.",
      ky: "Ооба. Yıldız техникалык университети инженерия жана башка тармактарда англис тилиндеги программаларды сунуштайт жана мамлекеттик университет катары эл аралык студенттер үчүн акыны жеткиликтүү кармайт.",
      zh: "是的。耶尔德兹理工大学提供工程学及其他领域的英语授课课程，作为公立大学，学费对国际学生来说非常实惠。",
      bg: "Да. Техническият университет Йълдъз предлага англоезични програми по инженерство и други специалности и като държавен университет поддържа достъпни такси за чуждестранни студенти.",
      ur: "جی ہاں۔ یلدز ٹیکنیکل یونیورسٹی انجینئرنگ اور دیگر شعبوں میں انگریزی پروگرام پیش کرتی ہے، اور سرکاری یونیورسٹی ہونے کے ناطے بین الاقوامی طلباء کے لیے فیس مناسب رکھتی ہے۔",
      uz: "Ha. Yıldız texnika universiteti muhandislik va boshqa sohalarda ingliz tilidagi dasturlarni taklif qiladi va davlat universiteti sifatida xalqaro talabalar uchun to‘lovlarni arzon ushlab turadi.",
      sw: "Ndiyo. Chuo Kikuu cha Ufundi cha Yıldız kinatoa programu za Kiingereza katika uhandisi na nyanja zingine, na kama chuo cha umma kinaweka ada nafuu kwa wanafunzi wa kimataifa.",
      so: "Haa. Jaamacadda farsanada ee Yıldız waxay bixisaa barnaamijyo Ingiriisi ah oo ku saabsan injineeriyadda iyo qaybaha kale, iyadoo jaamacad dawladeed tahayna waxay ku haynaysaa qiimaha la awoodi karo ardayda caalamiga ah.",
      id: "Ya. Universitas Teknik Yıldız menawarkan program berbahasa Inggris di bidang teknik dan lainnya, dan sebagai universitas negeri, biaya kuliahnya tetap terjangkau bagi mahasiswa internasional.",
    },
  },
];
