import type { Faq } from '@/types';

export const seedFaqs: Faq[] = [
  // General FAQs
  {
    id: 'f-g1',
    entityType: 'general',
    entityId: 'general',
    question: {
      en: 'Do I need to know Turkish to study in Turkey?',
      tr: 'Türkiye\'de okumak için Türkçe bilmem gerekir mi?',
      az: 'Türkiyədə oxumaq üçün türkçə bilməliyəmmi?',
      ru: 'Нужно ли знать турецкий, чтобы учиться в Турции?',
      de: 'Muss ich Türkisch können, um in der Türkei zu studieren?',
      fr: 'Dois-je parler turc pour étudier en Turquie ?',
      fa: 'آیا برای تحصیل در ترکیه باید ترکی بدانم؟',
      ar: 'هل أحتاج إلى معرفة التركية للدراسة في تركيا؟',
      tk: 'Türkiýede okamak üçin türk dilini bilmek gerekmi?',
      kk: 'Түркияда оқу үшін түрік тілін білуім керек пе?',
      ky: 'Түркияда окуу үчүн түрк тилин билишим керекпи?',
      zh: '在土耳其留学需要会土耳其语吗？',
      bg: 'Трябва ли да знам турски, за да уча в Турция?',
      ur: 'کیا ترکی میں تعلیم کے لیے ترکی زبان آنا ضروری ہے؟',
      uz: 'Turkiyada o\'qish uchun turk tilini bilishim kerakmi?',
      sw: 'Je, ninahitaji kujua Kituruki kusoma Uturuki?',
      so: 'Ma waxaan u baahanahay inaan ogaado Turkiga si aan u barto Turkiga?',
      id: 'Apakah saya perlu bisa bahasa Turki untuk kuliah di Turki?',
    },
    answer: {
      en: 'No. Hundreds of programs are taught fully in English. Turkish is helpful for daily life but not required for English-medium programs.',
      tr: 'Hayır. Yüzlerce program tamamen İngilizce verilir. Türkçe günlük hayat için faydalıdır ama İngilizce programlar için gerekli değildir.',
      az: 'Xeyr. Yüzlərlə proqram tamamilə ingilis dilindədir. Türkçə gündəlik həyat üçün faydalıdır, amma ingilis dilində proqramlar üçün tələb olunmur.',
      ru: 'Нет. Сотни программ полностью на английском. Турецкий полезен в быту, но не обязателен для англоязычных программ.',
      de: 'Nein. Hunderte Programme werden vollständig auf Englisch unterrichtet. Türkisch ist im Alltag hilfreich, aber für englischsprachige Programme nicht erforderlich.',
      fr: 'Non. Des centaines de programmes sont entièrement en anglais. Le turc est utile au quotidien mais pas requis pour les programmes en anglais.',
      fa: 'خیر. صدها برنامه کاملاً به انگلیسی ارائه میشوند. ترکی برای زندگی روزمره مفید است اما برای برنامههای انگلیسی الزامی نیست.',
      ar: 'لا. المئات من البرامج تُدرَّس بالكامل بالإنجليزية. التركية مفيدة للحياة اليومية لكنها غير مطلوبة للبرامج الإنجليزية.',
      tk: 'Ýok. Ýüzlerçe programma doly iňlis dilinde okadylýar. Türk dili gündelik durmuşda peýdaly, ýöne iňlis dilindäki programmalar üçin hökman däl.',
      kk: 'Жоқ. Жүздеген бағдарлама толығымен ағылшын тілінде оқытылады. Түрік тілі күнделікті өмірде пайдалы, бірақ ағылшын тілді бағдарламалар үшін қажет емес.',
      ky: 'Жок. Жүздөгөн программа толугу менен англис тилинде окутулат. Түрк тили күнүмдүк жашоодо пайдалуу, бирок англис тилиндеги программалар үчүн талап кылынбайт.',
      zh: '不需要。数百个课程完全用英语授课。土耳其语对日常生活有帮助，但英语授课课程不作要求。',
      bg: 'Не. Стотици програми се преподават изцяло на английски. Турският е полезен в ежедневието, но не е задължителен за англоезични програми.',
      ur: 'نہیں۔ سینکڑوں پروگرام مکمل طور پر انگریزی میں پڑھائے جاتے ہیں۔ ترکی روزمرہ زندگی کے لیے مفید ہے لیکن انگریزی پروگراموں کے لیے ضروری نہیں۔',
      uz: 'Yo\'q. Yuzlab dasturlar to\'liq ingliz tilida o\'qitiladi. Turk tili kundalik hayotda foydali, lekin ingliz tilidagi dasturlar uchun shart emas.',
      sw: 'Hapana. Mamia ya programu hufundishwa kwa Kiingereza kabisa. Kituruki kinasaidia maisha ya kila siku lakini hakihitajiki kwa programu za Kiingereza.',
      so: 'Maya. Boqollaal barnaamij ayaa si buuxda ku baxa Ingiriisiga. Turkiga waxaa faa\'iido u leh nolol maalmeedka laakiin loogama baahna barnaamijyada Ingiriisiga.',
      id: 'Tidak. Ratusan program diajarkan sepenuhnya dalam bahasa Inggris. Bahasa Turki berguna untuk kehidupan sehari-hari tetapi tidak wajib untuk program berbahasa Inggris.',
    },
  },
  {
    id: 'f-g2',
    entityType: 'general',
    entityId: 'general',
    question: {
      en: 'How much does it cost to study in Turkey?',
      tr: 'Türkiye\'de eğitim maliyeti ne kadar?',
      az: 'Türkiyədə təhsilin dəyəri nə qədərdir?',
      ru: 'Сколько стоит учёба в Турции?',
      de: 'Wie viel kostet ein Studium in der Türkei?',
      fr: 'Combien coûte un séjour d\'études en Turquie ?',
      fa: 'هزینه تحصیل در ترکیه چقدر است؟',
      ar: 'كم تكلفة الدراسة في تركيا؟',
      tk: 'Türkiýede okuw näçe çekýär?',
      kk: 'Түркияда оқу қанша тұрады?',
      ky: 'Түркияда окуу канча турат?',
      zh: '在土耳其留学费用是多少？',
      bg: 'Колко струва обучението в Турция?',
      ur: 'ترکی میں تعلیم کی لاگت کتنی ہے؟',
      uz: 'Turkiyada o\'qish qancha turadi?',
      sw: 'Kusoma Uturuki kunagharimu kiasi gani?',
      so: 'Waxbarashada Turkiga imisa ayay ku kacdaa?',
      id: 'Berapa biaya kuliah di Turki?',
    },
    answer: {
      en: 'State universities cost roughly USD 600–2,000 per year; private universities USD 5,000–25,000. Living costs are around USD 300–600 per month.',
      tr: 'Devlet üniversiteleri yılda yaklaşık 600–2.000 USD; vakıf üniversiteleri 5.000–25.000 USD. Yaşam maliyeti aylık 300–600 USD civarındadır.',
      az: 'Dövlət universitetləri təxminən 600–2000 ABŞ dolları; özəl universitetlər 5000–25000 ABŞ dolları. Yaşayış xərcləri ayda 300–600 ABŞ dollarıdır.',
      ru: 'Государственные вузы: 600–2 000 USD в год; частные: 5 000–25 000 USD. Проживание — около 300–600 USD в месяц.',
      de: 'Staatliche Universitäten kosten etwa 600–2.000 USD pro Jahr; private Universitäten 5.000–25.000 USD. Lebenshaltungskosten liegen bei etwa 300–600 USD pro Monat.',
      fr: 'Les universités publiques coûtent environ 600 à 2 000 USD par an ; les universités privées 5 000 à 25 000 USD. Le coût de la vie est d\'environ 300 à 600 USD par mois.',
      fa: 'دانشگاههای دولتی حدود ۶۰۰ تا ۲۰۰۰ دلار در سال و دانشگاههای خصوصی ۵۰۰۰ تا ۲۵۰۰۰ دلار هزینه دارند. هزینه زندگی ماهانه حدود ۳۰۰ تا ۶۰۰ دلار است.',
      ar: 'الجامعات الحكومية تكلف حوالي 600–2000 دولار سنوياً؛ والخاصة 5000–25000 دولار. تكاليف المعيشة حوالي 300–600 دولار شهرياً.',
      tk: 'Döwlet uniwersitetleri ýylda takmynan 600–2000 USD; hususy uniwersitetler 5000–25000 USD. Ýaşaýyş çykdajylary aýda 300–600 USD töweregi.',
      kk: 'Мемлекеттік университеттер жылына шамамен 600–2000 АҚШ доллары; жеке университеттер 5000–25000 АҚШ доллары. Өмір сүру құны айына 300–600 АҚШ доллары.',
      ky: 'Мамлекеттик университеттер жылына болжол менен 600–2000 АКШ доллары; жеке университеттер 5000–25000 АКШ доллары. Жашоо чыгымдары айына 300–600 АКШ доллары.',
      zh: '公立大学每年约600–2000美元；私立大学5000–25000美元。生活费每月约300–600美元。',
      bg: 'Държавните университети струват около 600–2000 USD годишно; частните 5000–25000 USD. Разходите за живот са около 300–600 USD месечно.',
      ur: 'سرکاری یونیورسٹیاں سالانہ تقریباً 600–2000 ڈالر؛ پرائیویٹ یونیورسٹیاں 5000–25000 ڈالر۔ رہائشی اخراجات ماہانہ 300–600 ڈالر۔',
      uz: 'Davlat universitetlari yiliga taxminan 600–2000 AQSh dollari; xususiy universitetlar 5000–25000 AQSh dollari. Yashash xarajatlari oyiga 300–600 AQSh dollari.',
      sw: 'Vyuo vya umma hugharimu takriban USD 600–2,000 kwa mwaka; vyuo vya kibinafsi USD 5,000–25,000. Gharama za maisha ni karibu USD 300–600 kwa mwezi.',
      so: 'Jaamacadaha dawladda waxay ku kacaan qiyaastii 600–2000 dollar sanadkii; kuwa gaarka ah 5000–25000 dollar. Kharashka noloshu waa 300–600 dollar bishii.',
      id: 'Universitas negeri sekitar USD 600–2.000 per tahun; universitas swasta USD 5.000–25.000. Biaya hidup sekitar USD 300–600 per bulan.',
    },
  },
  {
    id: 'f-g3',
    entityType: 'general',
    entityId: 'general',
    question: {
      en: 'Do I need a student visa?',
      tr: 'Öğrenci vizesi gerekli mi?',
      az: 'Tələbə vizası lazımdırmı?',
      ru: 'Нужна ли студенческая виза?',
      de: 'Brauche ich ein Studentenvisum?',
      fr: 'Ai-je besoin d\'un visa étudiant ?',
      fa: 'آیا به ویزای دانشجویی نیاز دارم؟',
      ar: 'هل أحتاج إلى تأشيرة طالب؟',
      tk: 'Okuwçy wizasy gerekmi?',
      kk: 'Маған студенттік виза керек пе?',
      ky: 'Мага студенттик виза керекпи?',
      zh: '我需要学生签证吗？',
      bg: 'Нужна ли ми е студентска виза?',
      ur: 'کیا مجھے طالب علم ویزا چاہیے؟',
      uz: 'Menga talaba vizasi kerakmi?',
      sw: 'Je, ninahitaji visa ya mwanafunzi?',
      so: 'Ma waxaan u baahanahay fiisaha ardayga?',
      id: 'Apakah saya perlu visa pelajar?',
    },
    answer: {
      en: 'Yes. After acceptance you apply for a student visa at the Turkish consulate, then convert it to a residence permit after arrival.',
      tr: 'Evet. Kabul aldıktan sonra Türk konsolosluğundan öğrenci vizesi alır, varıştan sonra ikamet iznine dönüştürürsünüz.',
      az: 'Bəli. Qəbul aldıqdan sonra Türkiyə konsolulluğundan tələbə vizası alır, gəlişdən sonra yaşayış icazəsinə çevirirsiniz.',
      ru: 'Да. После зачисления вы получаете студенческую визу в консульстве, а по приезде меняете её на вид на жительство.',
      de: 'Ja. Nach der Zulassung beantragen Sie ein Studentenvisum beim türkischen Konsulat und wandeln es nach der Ankunft in eine Aufenthaltserlaubnis um.',
      fr: 'Oui. Après acceptation, vous demandez un visa étudiant au consulat turc, puis vous le convertissez en permis de séjour à l\'arrivée.',
      fa: 'بله. پس از پذیرش، در کنسولگری ترکیه ویزای دانشجویی میگیرید و پس از ورود آن را به اجازه اقامت تبدیل میکنید.',
      ar: 'نعم. بعد القبول تتقدم بطلب تأشيرة طالب في القنصلية التركية، ثم تحوّلها إلى تصريح إقامة بعد الوصول.',
      tk: 'Hawa. Kabul alanyňyzdan soň türk konsullygyndan okuwçy wizasyny alyp, geleniňizden soň ýaşaýyş rugsadyna öwürýärsiňiz.',
      kk: 'Иә. Қабылданғаннан кейін түрік консулдығынан студенттік виза аласыз, содан кейін келгеннен кейін тұруға рұқсатқа айналдырасыз.',
      ky: 'Ооба. Кабыл алынгандан кийин түрк консулдугунан студенттик виза алып, келгенден кийин жашоо уруксатына айландырасыз.',
      zh: '是的。被录取后，你在土耳其领事馆申请学生签证，抵达后将其转为居留许可。',
      bg: 'Да. След приема кандидатствате за студентска виза в турското консулство, а след пристигане я превръщате в разрешително за престой.',
      ur: 'جی ہاں۔ قبولیت کے بعد ترک قونصل خانے سے طالب علم ویزا حاصل کریں، پھر آمد پر اسے رہائشی اجازت نامے میں تبدیل کریں۔',
      uz: 'Ha. Qabul qilingandan so\'ng Turkiya konsulxonasidan talaba vizasi olasiz va kelgach uni yashash guvohnomasiga aylantirasiz.',
      sw: 'Ndiyo. Baada ya kukubaliwa, unaomba visa ya mwanafunzi kwenye ubalozi wa Uturuki, kisha uibadilishe kuwa kibali cha kukaa baada ya kuwasili.',
      so: 'Haa. Ka dib marka la aqbalo, waxaad ka codsanaysaa fiisaha ardayga xafiiska Turkiga, ka dibna waxaad u beddeshaa ogolaanshaha degenaanshaha.',
      id: 'Ya. Setelah diterima, Anda mengajukan visa pelajar di konsulat Turki, lalu mengubahnya menjadi izin tinggal setelah tiba.',
    },
  },
  {
    id: 'f-g4',
    entityType: 'general',
    entityId: 'general',
    question: {
      en: 'Are scholarships available for international students?',
      tr: 'Uluslararası öğrenciler için burs var mı?',
      az: 'Beynəlxalq tələbələr üçün təqaüd varmı?',
      ru: 'Есть ли стипендии для иностранных студентов?',
      de: 'Gibt es Stipendien für internationale Studierende?',
      fr: 'Des bourses sont-elles disponibles pour les étudiants internationaux ?',
      fa: 'آیا بورسیههایی برای دانشجویان بینالمللی وجود دارد؟',
      ar: 'هل توجد منح للطلاب الدوليين؟',
      tk: 'Halkara talyplar üçin stipendiýalar barmy?',
      kk: 'Халықаралық студенттерге стипендия бар ма?',
      ky: 'Эл аралык студенттерге стипендия барбы?',
      zh: '国际学生有奖学金吗？',
      bg: 'Има ли стипендии за международни студенти?',
      ur: 'کیا بین الاقوامی طلباء کے لیے اسکالرشپس دستیاب ہیں؟',
      uz: 'Xalqaro talabalar uchun stipendiyalar bormi?',
      sw: 'Je, kuna ufadhili kwa wanafunzi wa kimataifa?',
      so: 'Ma jiraan deeqo loogu talagalay ardayda caalamiga ah?',
      id: 'Apakah tersedia beasiswa untuk mahasiswa internasional?',
    },
    answer: {
      en: 'Yes. The Türkiye Bursları government program offers full scholarships, and most private universities offer merit discounts of 25–100%.',
      tr: 'Evet. Türkiye Bursları devlet programı tam burs sunar ve çoğu vakıf üniversitesi %25–100 başarı indirimleri verir.',
      az: 'Bəli. Türkiye Bursları dövlət proqramı tam təqaüd təklif edir və əksər özəl universitetlər 25–100% nailiyyət endirimləri verir.',
      ru: 'Да. Программа Türkiye Bursları даёт полные стипендии, а частные вузы — скидки 25–100% за заслуги.',
      de: 'Ja. Das staatliche Programm Türkiye Bursları bietet Vollstipendien, und die meisten privaten Universitäten geben Leistungsrabatte von 25–100%.',
      fr: 'Oui. Le programme gouvernemental Türkiye Bursları offre des bourses complètes, et la plupart des universités privées offrent des réductions au mérite de 25 à 100 %.',
      fa: 'بله. برنامه دولتی ترکیه بورسلری بورسیه کامل ارائه میدهد و اکثر دانشگاههای خصوصی تخفیف ۲۵ تا ۱۰۰ درصدی میدهند.',
      ar: 'نعم. برنامج المنح الحكومي التركي يقدم منحاً كاملة، ومعظم الجامعات الخاصة تقدم خصومات على الاستحقاق من 25 إلى 100%.',
      tk: 'Hawa. Türkiye Bursleri döwlet programmasy doly stipendiýa berýär we köp hususy uniwersitetler 25–100% başaryş endirimini berýär.',
      kk: 'Иә. Türkiye Bursları мемлекеттік бағдарламасы толық стипендия береді, ал жеке университеттердің көпшілігі 25–100% жетістік жеңілдігін ұсынады.',
      ky: 'Ооба. Türkiye Bursları мамлекеттик программасы толук стипендия берет, ал көпчүлүк жеке университеттер 25–100% жетишкендик арзандатуусун сунуштайт.',
      zh: '是的。土耳其政府奖学金项目提供全额奖学金，大多数私立大学提供25–100%的成绩折扣。',
      bg: 'Да. Държавната програма Türkiye Bursları дава пълни стипендии, а повечето частни университети дават отстъпки 25–100% за успех.',
      ur: 'جی ہاں۔ ترک سرکاری اسکالرشپ پروگرام مکمل اسکالرشپ دیتا ہے، اور زیادہ تر پرائیویٹ یونیورسٹیاں 25–100% میرٹ ڈسکاؤنٹ دیتی ہیں۔',
      uz: 'Ha. Türkiye Bursları davlat dasturi to\'liq stipendiya beradi va aksariyat xususiy universitetlar 25–100% merit chegirmalarini taqdim etadi.',
      sw: 'Ndiyo. Mpango wa serikali wa Türkiye Bursları unatoa ufadhili kamili, na vyuo vingi vya kibinafsi vinatoa punguzo la 25–100% kwa sifa.',
      so: 'Haa. Barnaamijka dawladda ee Türkiye Bursları wuxuu bixiyaa deeqo buuxda, jaamacadaha gaarka ah badankooduna waxay bixiyaan qiimo dhimis 25–100% ah.',
      id: 'Ya. Program pemerintah Türkiye Bursları menawarkan beasiswa penuh, dan sebagian besar universitas swasta memberikan diskon prestasi 25–100%.',
    },
  },
  {
    id: 'f-g5',
    entityType: 'general',
    entityId: 'general',
    question: {
      en: 'What documents do I need to apply?',
      tr: 'Başvuru için hangi belgeler gerekli?',
      az: 'Müraciət üçün hansı sənədlər lazımdır?',
      ru: 'Какие документы нужны для подачи заявки?',
      de: 'Welche Unterlagen benötige ich für die Bewerbung?',
      fr: 'Quels documents dois-je fournir pour candidater ?',
      fa: 'برای ثبتنام چه مدارکی نیاز دارم؟',
      ar: 'ما الوثائق المطلوبة للتقديم؟',
      tk: 'Ýüz tutmak üçin haýsy resminamalar gerek?',
      kk: 'Өтінім беру үшін қандай құжаттар қажет?',
      ky: 'Арыз берүү үчүн кандай документтер керек?',
      zh: '申请需要什么材料？',
      bg: 'Какви документи са ми нужни за кандидатстване?',
      ur: 'درخواست کے لیے کون سی دستاویزات درکار ہیں؟',
      uz: 'Ariza topshirish uchun qanday hujjatlar kerak?',
      sw: 'Nina hati gani zinahitajika kuomba?',
      so: 'Waa kuwee dukumentiyada aan u baahanahay in aan codsado?',
      id: 'Dokumen apa saja yang diperlukan untuk mendaftar?',
    },
    answer: {
      en: 'Typically: passport, high-school diploma and transcript (translated & notarised), passport photo, motivational letter and language certificate.',
      tr: 'Genellikle: pasaport, lise diploması ve transkripti (tercümeli ve onaylı), vesikalık fotoğraf, motivasyon mektubu ve dil sertifikası.',
      az: 'Adətən: pasport, orta məktəb diploması və transkripti (tərcümə və təsdiq edilmiş), şəkil, motivasiya məktubu və dil sertifikatı.',
      ru: 'Обычно: паспорт, аттестат и выписка оценок (перевод и нотариальное заверение), фото, мотивационное письмо и сертификат о языке.',
      de: 'In der Regel: Reisepass, Schulabschlusszeugnis und Notenübersicht (übersetzt und notariell beglaubigt), Passfoto, Motivationsschreiben und Sprachzertifikat.',
      fr: 'En général : passeport, diplôme et relevé de notes (traduits et notariés), photo d\'identité, lettre de motivation et certificat de langue.',
      fa: 'معمولاً: پاسپورت، دیپلم دبیرستان و ریزنمرات (ترجمه و تایید شده)، عکس پرسنلی، نامه انگیزشی و مدرک زبان.',
      ar: 'عادةً: جواز السفر، شهادة الثانوية وكشف الدرجات (مترجمة وموثقة)، صورة شخصية، خطاب تحفيزي وشهادة لغة.',
      tk: 'Adatça: pasport, orta mekdep diplom we transkript (terjime we tassyklanan), surat, höwes haty we dil şahadatnamasy.',
      kk: 'Әдетте: паспорт, мектеп аттестаты және үлгерім көшірмесі (аударылған және куәландырылған), фотосурет, мотивациялық хат және тіл сертификаты.',
      ky: 'Адатта: паспорт, орто мектеп диплому жана транскрипт (которулган жана тастыкталган), сүрөт, мотивациялык кат жана тил сертификаты.',
      zh: '通常包括：护照、高中毕业证和成绩单（翻译并公证）、证件照、动机信和语言证书。',
      bg: 'Обикновено: паспорт, диплома и стенограма (преведени и нотариално заверени), снимка, мотивационно писмо и езиков сертификат.',
      ur: 'عام طور پر: پاسپورٹ، ہائی اسکول ڈپلومہ اور ٹرانسکرپٹ (ترجمہ شدہ اور تصدیق شدہ)، پاسپورٹ تصویر، حوصلہ افزائی خط اور زبان کا سرٹیفکیٹ۔',
      uz: 'Odatda: pasport, o\'rta maktab diplomi va transkript (tarjima qilingan va tasdiqlangan), rasm, motivatsiya xati va til sertifikati.',
      sw: 'Kwa kawaida: pasipoti, diploma ya shule na nakala ya alama (zilizotafsiriwa na kuthibitishwa), picha, barua ya motisha na cheti cha lugha.',
      so: 'Sida caadiga ah: baasaboor, shahaadada dugsiga sare iyo nuqulka (oo la turjumay oo la xaqiijiyay), sawir, warqadda dhiirigelinta iyo shahaadada luqadda.',
      id: 'Biasanya: paspor, ijazah SMA dan transkrip (diterjemahkan dan dilegalisir), foto, surat motivasi, dan sertifikat bahasa.',
    },
  },
  // University-specific
  {
    id: 'f-bau1',
    entityType: 'university',
    entityId: 'u-bahcesehir',
    question: {
      en: 'Is Bahçeşehir University accredited internationally?',
      tr: 'Bahçeşehir Üniversitesi uluslararası akredite mi?',
      az: 'Bahçeşehir Universiteti beynəlxalq akreditə olunubmu?',
      ru: 'Аккредитован ли Бахчешеширский университет международно?',
      de: 'Ist die Bahçeşehir-Universität international akkreditiert?',
      fr: 'L\'université Bahçeşehir est-elle accréditée à l\'international ?',
      fa: 'آیا دانشگاه باغچهشهر اعتبار بینالمللی دارد؟',
      ar: 'هل جامعة بهتشه شهير معتمدة دولياً؟',
      tk: 'Bahçeşehir uniwersiteti halkara derejede akkreditlenenmi?',
      kk: 'Бахчешехир университеті халықаралық аккредиттелген бе?',
      ky: 'Bahçeşehir университети эл аралык аккредитацияга ээби?',
      zh: '巴哈切希尔大学获得国际认证吗？',
      bg: 'Бахчешехирският университет международно акредитиран ли е?',
      ur: 'کیا بہچہ شہر یونیورسٹی بین الاقوامی طور پر تسلیم شدہ ہے؟',
      uz: 'Bahçeşehir universiteti xalqaro akkreditatsiyaga egami?',
      sw: 'Je, Chuo Kikuu cha Bahçeşehir kimeidhinishwa kimataifa?',
      so: 'Ma jaamacadda Bahçeşehir ayaa caalami ahaan la aqoonsaday?',
      id: 'Apakah Universitas Bahçeşehir terakreditasi secara internasional?',
    },
    answer: {
      en: 'Yes. It is recognised by YÖK and holds several international accreditations for its business and engineering programs.',
      tr: 'Evet. YÖK tarafından tanınır ve işletme ile mühendislik programları için çeşitli uluslararası akreditasyonlara sahiptir.',
      az: 'Bəli. YÖK tərəfindən tanınır və biznes və mühəndislik proqramları üçün bir neçə beynəlxalq akreditasiyaya malikdir.',
      ru: 'Да. Признан YÖK и имеет ряд международных аккредитаций по бизнесу и инженерии.',
      de: 'Ja. Sie wird vom YÖK anerkannt und besitzt mehrere internationale Akkreditierungen für ihre Wirtschafts- und Ingenieurprogramme.',
      fr: 'Oui. Elle est reconnue par le YÖK et possède plusieurs accréditations internationales pour ses programmes de commerce et d\'ingénierie.',
      fa: 'بله. توسط YÖK به رسمیت شناخته شده و برای برنامههای تجاری و مهندسی خود چندین اعتبار بینالمللی دارد.',
      ar: 'نعم. معترف بها من قبل YÖK ولديها عدة اعتمادات دولية لبرامجها في الأعمال والهندسة.',
      tk: 'Hawa. YÖK tarapyndan tanalýar we biznes we inženerlik programmalary üçin birnäçe halkara akkreditasiýasyna eýedir.',
      kk: 'Иә. YÖK таныған және бизнес пен инженерия бағдарламалары үшін бірнеше халықаралық аккредитацияға ие.',
      ky: 'Ооба. YÖK тарабынан таанылган жана бизнес жана инженерия программалары үчүн бир нече эл аралык аккредитацияга ээ.',
      zh: '是的。该校获得YÖK认可，其商科和工程课程拥有多项国际认证。',
      bg: 'Да. Признат е от YÖK и има няколко международни акредитации за бизнес и инженерни програми.',
      ur: 'جی ہاں۔ اسے YÖK تسلیم کرتا ہے اور اس کے بزنس اور انجینئرنگ پروگراموں کے لیے کئی بین الاقوامی تسلیم شدگیاں ہیں۔',
      uz: 'Ha. U YÖK tomonidan tan olingan va biznes hamda muhandislik dasturlari uchun bir qancha xalqaro akkreditatsiyalarga ega.',
      sw: 'Ndiyo. Inatambulika na YÖK na ina idhini nyingi za kimataifa kwa programu zake za biashara na uhandisi.',
      so: 'Haa. Waxaa aqoonsaday YÖK waxayna u haysaa dhowr aqoonsi caalami ah oo loogu talagalay barnaamijyada ganacsiga iyo injineeriyada.',
      id: 'Ya. Diakui oleh YÖK dan memiliki beberapa akreditasi internasional untuk program bisnis dan tekniknya.',
    },
  },
  {
    id: 'f-metu1',
    entityType: 'university',
    entityId: 'u-metu',
    question: {
      en: 'Does METU offer accommodation on campus?',
      tr: 'ODTÜ kampüste konaklama sunuyor mu?',
      az: 'ODTÜ kampusda qalma yeri təklif edirmi?',
      ru: 'Предоставляет ли ODTÜ проживание на кампусе?',
      de: 'Bietet die METU Unterkunft auf dem Campus?',
      fr: 'L\'ODTÜ propose-t-il un logement sur le campus ?',
      fa: 'آیا ODTÜ اقامتگاه درون دانشگاه ارائه میدهد؟',
      ar: 'هل توفر ODTÜ سكناً داخل الحرم الجامعي؟',
      tk: 'ODTÜ kampusda ýaşaýyş hödürleýärmi?',
      kk: 'ODTÜ кампуста тұрғын үй ұсына ма?',
      ky: 'ODTÜ кампуста турак-жай сунуштайбы?',
      zh: '中东技术大学提供校内住宿吗？',
      bg: 'Предлага ли ODTÜ настаняване в кампуса?',
      ur: 'کیا ODTÜ کیمپس میں رہائش فراہم کرتی ہے؟',
      uz: 'ODTÜ kampusda yashash joyini taklif qiladimi?',
      sw: 'Je, ODTÜ inatoa malazi kwenye kampasi?',
      so: 'Ma ODTÜ waxay bixisaa hoy gudaha kambaska?',
      id: 'Apakah ODTÜ menyediakan akomodasi di kampus?',
    },
    answer: {
      en: 'Yes. METU has one of the largest dormitory capacities in Turkey, with affordable on-campus housing for students.',
      tr: 'Evet. ODTÜ, Türkiye\'nin en büyük yurt kapasitelerinden birine sahiptir ve uygun fiyatlı kampüs içi konaklama sunar.',
      az: 'Bəli. ODTÜ Türkiyənin ən böyük yataqxana tutumlarından birinə malikdir və tələbələr üçün uyğun qiymətli kampus içi qalma yeri təklif edir.',
      ru: 'Да. В ODTÜ одно из крупнейших общежитий в Турции с доступным проживанием на кампусе.',
      de: 'Ja. Die METU verfügt über eine der größten Wohnheimkapazitäten der Türkei mit erschwinglicher Unterkunft auf dem Campus.',
      fr: 'Oui. L\'ODTÜ possède l\'une des plus grandes capacités de dortoirs de Turquie, avec un logement abordable sur le campus.',
      fa: 'بله. ODTÜ یکی از بزرگترین ظرفیتهای خوابگاهی ترکیه را دارد و اقامت درون دانشگاه با هزینه مناسب ارائه میدهد.',
      ar: 'نعم. تمتلك ODTÜ واحدة من أكبر سعات السكن الطلابي في تركيا مع إقامة ميسورة داخل الحرم.',
      tk: 'Hawa. ODTÜ Türkiýäniň iň uly ýatakhana kuwwatlaryndan birine eýedir we kampus içinde elýeterli ýaşaýyş hödürleýär.',
      kk: 'Иә. ODTÜ Түркиядағы ең үлкен жатақхана сыйымдылығының біріне ие және кампуста қолжетімді тұрғын үй ұсынады.',
      ky: 'Ооба. ODTÜ Түркиядагы эң чоң жатакана сыйымдуулуктарынын бирине ээ жана кампуста жеткиликтүү турак-жай сунуштайт.',
      zh: '是的。中东技术大学拥有土耳其最大的宿舍容量之一，为学生提供实惠的校内住宿。',
      bg: 'Да. ODTÜ има един от най-големите общежития в Турция с достъпно настаняване в кампуса.',
      ur: 'جی ہاں۔ ODTÜ ترکی کے سب سے بڑے ہاسٹل میں سے ایک رکھتی ہے جس میں طلباء کے لیے سستی رہائش ہے۔',
      uz: 'Ha. ODTÜ Turkiyadagi eng katta yotoqxona quvvatlaridan biriga ega va talabalar uchun kampusda qulay narxlarda yashashni taklif qiladi.',
      sw: 'Ndiyo. ODTÜ ina moja ya uwezo mkubwa zaidi wa mabweni nchini Uturuki, ikiwa na malazi ya bei nafuu kwenye kampasi.',
      so: 'Haa. ODTÜ waxay leedahay mid ka mid ah awoodaha ugu weyn ee hostelka ee Turkiga, iyadoo bixisay hoy ku habboon oo kambaska ah.',
      id: 'Ya. ODTÜ memiliki salah satu kapasitas asrama terbesar di Turki dengan akomodasi di kampus yang terjangkau.',
    },
  },
];
