import type { Program, ProgramCategory } from '@/types';

export const seedCategories: ProgramCategory[] = [
  {
    slug: 'medicine',
    name: { en: 'Medicine', tr: 'Tıp', az: 'Tibb', ru: 'Медицина' },
    icon: 'stethoscope',
  },
  {
    slug: 'engineering',
    name: { en: 'Engineering', tr: 'Mühendislik', az: 'Mühəndislik', ru: 'Инженерия' },
    icon: 'cog',
  },
  {
    slug: 'computer-science',
    name: { en: 'Computer Science', tr: 'Bilgisayar Bilimleri', az: 'Kompüter Elmləri', ru: 'Компьютерные науки' },
    icon: 'code',
  },
  {
    slug: 'business',
    name: { en: 'Business', tr: 'İşletme', az: 'Biznes', ru: 'Бизнес' },
    icon: 'briefcase',
  },
  {
    slug: 'law',
    name: { en: 'Law', tr: 'Hukuk', az: 'Hüquq', ru: 'Право' },
    icon: 'scale',
  },
  {
    slug: 'architecture',
    name: { en: 'Architecture', tr: 'Mimarlık', az: 'Memarlıq', ru: 'Архитектура' },
    icon: 'compass',
  },
  {
    slug: 'dentistry',
    name: { en: 'Dentistry', tr: 'Diş Hekimliği', az: 'Stomatologiya', ru: 'Стоматология' },
    icon: 'smile',
  },
  {
    slug: 'arts',
    name: { en: 'Arts & Design', tr: 'Sanat ve Tasarım', az: 'İncəsənət və Dizayn', ru: 'Искусство и дизайн' },
    icon: 'palette',
  },
];

export const seedPrograms: Program[] = [
  {
    id: 'p-med-bach',
    slug: 'medicine',
    name: { en: 'Medicine (MD)', tr: 'Tıp', az: 'Tibb', ru: 'Медицина' },
    degreeLevel: 'bachelor',
    categorySlug: 'medicine',
    durationYears: 6,
  },
  {
    id: 'p-med-master',
    slug: 'medicine-master',
    name: { en: 'Medical Specialization', tr: 'Tıp Uzmanlığı', az: 'Tibb İxtisası', ru: 'Медицинская специализация' },
    degreeLevel: 'master',
    categorySlug: 'medicine',
    durationYears: 5,
  },
  {
    id: 'p-dent-bach',
    slug: 'dentistry',
    name: { en: 'Dentistry', tr: 'Diş Hekimliği', az: 'Stomatologiya', ru: 'Стоматология' },
    degreeLevel: 'bachelor',
    categorySlug: 'dentistry',
    durationYears: 5,
  },
  {
    id: 'p-cs-bach',
    slug: 'computer-engineering',
    name: { en: 'Computer Engineering', tr: 'Bilgisayar Mühendisliği', az: 'Kompüter Mühəndisliyi', ru: 'Компьютерная инженерия' },
    degreeLevel: 'bachelor',
    categorySlug: 'computer-science',
    durationYears: 4,
  },
  {
    id: 'p-cs-master',
    slug: 'computer-science-master',
    name: { en: 'Computer Science (MSc)', tr: 'Bilgisayar Bilimleri (YL)', az: 'Kompüter Elmləri (Magistr)', ru: 'Компьютерные науки (Магистр)' },
    degreeLevel: 'master',
    categorySlug: 'computer-science',
    durationYears: 2,
  },
  {
    id: 'p-se-bach',
    slug: 'software-engineering',
    name: { en: 'Software Engineering', tr: 'Yazılım Mühendisliği', az: 'Proqram Təminatı Mühəndisliyi', ru: 'Программная инженерия' },
    degreeLevel: 'bachelor',
    categorySlug: 'computer-science',
    durationYears: 4,
  },
  {
    id: 'p-eng-mech',
    slug: 'mechanical-engineering',
    name: { en: 'Mechanical Engineering', tr: 'Makine Mühendisliği', az: 'Mexanika Mühəndisliyi', ru: 'Машиностроение' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-elec',
    slug: 'electrical-engineering',
    name: { en: 'Electrical Engineering', tr: 'Elektrik Mühendisliği', az: 'Elektrik Mühəndisliyi', ru: 'Электротехника' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-civil',
    slug: 'civil-engineering',
    name: { en: 'Civil Engineering', tr: 'İnşaat Mühendisliği', az: 'İnşaat Mühəndisliyi', ru: 'Гражданское строительство' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-bus-bach',
    slug: 'business-administration',
    name: { en: 'Business Administration', tr: 'İşletme', az: 'Biznesin İdarəedilməsi', ru: 'Бизнес-администрирование' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-bus-mba',
    slug: 'mba',
    name: { en: 'MBA', tr: 'MBA', az: 'MBA', ru: 'MBA' },
    degreeLevel: 'master',
    categorySlug: 'business',
    durationYears: 2,
  },
  {
    id: 'p-bus-irm',
    slug: 'international-relations',
    name: { en: 'International Relations', tr: 'Uluslararası İlişkiler', az: 'Beynəlxalq Münasibətlər', ru: 'Международные отношения' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-law-bach',
    slug: 'law',
    name: { en: 'Law', tr: 'Hukuk', az: 'Hüquq', ru: 'Право' },
    degreeLevel: 'bachelor',
    categorySlug: 'law',
    durationYears: 4,
  },
  {
    id: 'p-arch-bach',
    slug: 'architecture',
    name: { en: 'Architecture', tr: 'Mimarlık', az: 'Memarlıq', ru: 'Архитектура' },
    degreeLevel: 'bachelor',
    categorySlug: 'architecture',
    durationYears: 4,
  },
  {
    id: 'p-arts-bach',
    slug: 'industrial-design',
    name: { en: 'Industrial Design', tr: 'Endüstriyel Tasarım', az: 'Sənaye Dizaynı', ru: 'Промышленный дизайн' },
    degreeLevel: 'bachelor',
    categorySlug: 'arts',
    durationYears: 4,
  },
  {
    id: 'p-ai-master',
    slug: 'artificial-intelligence',
    name: { en: 'Artificial Intelligence (MSc)', tr: 'Yapay Zeka (YL)', az: 'Süni İntellekt (Magistr)', ru: 'Искусственный интеллект (Магистр)' },
    degreeLevel: 'master',
    categorySlug: 'computer-science',
    durationYears: 2,
  },
];
