import type { Program, ProgramCategory } from '@/types';

export const seedCategories: ProgramCategory[] = [
  {
    slug: 'medicine',
    name: { en: 'Medicine', tr: 'Tıp', az: 'Tibb', ru: 'Медицина' },
    icon: 'stethoscope',
  },
  {
    slug: 'engineering',
    name: { en: 'Engineering', tr: 'Mühendislik', az: 'Mühəndislik', ru: 'Инженерия' },
    icon: 'cog',
  },
  {
    slug: 'computer-science',
    name: { en: 'Computer Science', tr: 'Bilgisayar Bilimleri', az: 'Kompüter Elmləri', ru: 'Компьютерные науки' },
    icon: 'code',
  },
  {
    slug: 'business',
    name: { en: 'Business', tr: 'İşletme', az: 'Biznes', ru: 'Бизнес' },
    icon: 'briefcase',
  },
  {
    slug: 'law',
    name: { en: 'Law', tr: 'Hukuk', az: 'Hüquq', ru: 'Право' },
    icon: 'scale',
  },
  {
    slug: 'architecture',
    name: { en: 'Architecture', tr: 'Mimarlık', az: 'Memarlıq', ru: 'Архитектура' },
    icon: 'compass',
  },
  {
    slug: 'dentistry',
    name: { en: 'Dentistry', tr: 'Diş Hekimliği', az: 'Stomatologiya', ru: 'Стоматология' },
    icon: 'smile',
  },
  {
    slug: 'arts',
    name: { en: 'Arts & Design', tr: 'Sanat ve Tasarım', az: 'İncəsənət və Dizayn', ru: 'Искусство и дизайн' },
    icon: 'palette',
  },
  {
    slug: 'social-sciences',
    name: { en: 'Social Sciences', tr: 'Sosyal Bilimler', az: 'Sosial Elmlər', ru: 'Социальные науки' },
    icon: 'users',
  },
  {
    slug: 'health-sciences',
    name: { en: 'Health Sciences', tr: 'Sağlık Bilimleri', az: 'Səhiyyə Elmləri', ru: 'Медицинские науки' },
    icon: 'heart-pulse',
  },
  {
    slug: 'natural-sciences',
    name: { en: 'Natural Sciences', tr: 'Fen Bilimleri', az: 'Təbiət Elmləri', ru: 'Естественные науки' },
    icon: 'atom',
  },
  {
    slug: 'humanities',
    name: { en: 'Humanities', tr: 'Beşeri Bilimler', az: 'Humanitar Elmlər', ru: 'Гуманитарные науки' },
    icon: 'book-open',
  },
  {
    slug: 'communication',
    name: { en: 'Communication', tr: 'İletişim', az: 'Kommunikasiya', ru: 'Коммуникации' },
    icon: 'radio',
  },
  {
    slug: 'tourism',
    name: { en: 'Tourism & Hospitality', tr: 'Turizm ve Otel İşletmeciliği', az: 'Turizm və Qonaqpərvərlik', ru: 'Туризм и гостеприимство' },
    icon: 'map-pin',
  },
  {
    slug: 'agriculture',
    name: { en: 'Agriculture & Food', tr: 'Tarım ve Gıda', az: 'Kənd Təsərrüfatı və Qida', ru: 'Сельское хозяйство и питание' },
    icon: 'leaf',
  },
];

export const seedPrograms: Program[] = [
  {
    id: 'p-med-bach',
    slug: 'medicine',
    name: { en: 'Medicine (MD)', tr: 'Tıp', az: 'Tibb', ru: 'Медицина' },
    degreeLevel: 'bachelor',
    categorySlug: 'medicine',
    durationYears: 6,
  },
  {
    id: 'p-med-master',
    slug: 'medicine-master',
    name: { en: 'Medical Specialization', tr: 'Tıp Uzmanlığı', az: 'Tibb İxtisası', ru: 'Медицинская специализация' },
    degreeLevel: 'master',
    categorySlug: 'medicine',
    durationYears: 5,
  },
  {
    id: 'p-dent-bach',
    slug: 'dentistry',
    name: { en: 'Dentistry', tr: 'Diş Hekimliği', az: 'Stomatologiya', ru: 'Стоматология' },
    degreeLevel: 'bachelor',
    categorySlug: 'dentistry',
    durationYears: 5,
  },
  {
    id: 'p-cs-bach',
    slug: 'computer-engineering',
    name: { en: 'Computer Engineering', tr: 'Bilgisayar Mühendisliği', az: 'Kompüter Mühəndisliyi', ru: 'Компьютерная инженерия' },
    degreeLevel: 'bachelor',
    categorySlug: 'computer-science',
    durationYears: 4,
  },
  {
    id: 'p-cs-master',
    slug: 'computer-science-master',
    name: { en: 'Computer Science (MSc)', tr: 'Bilgisayar Bilimleri (YL)', az: 'Kompüter Elmləri (Magistr)', ru: 'Компьютерные науки (Магистр)' },
    degreeLevel: 'master',
    categorySlug: 'computer-science',
    durationYears: 2,
  },
  {
    id: 'p-se-bach',
    slug: 'software-engineering',
    name: { en: 'Software Engineering', tr: 'Yazılım Mühendisliği', az: 'Proqram Təminatı Mühəndisliyi', ru: 'Программная инженерия' },
    degreeLevel: 'bachelor',
    categorySlug: 'computer-science',
    durationYears: 4,
  },
  {
    id: 'p-eng-mech',
    slug: 'mechanical-engineering',
    name: { en: 'Mechanical Engineering', tr: 'Makine Mühendisliği', az: 'Mexanika Mühəndisliyi', ru: 'Машиностроение' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-elec',
    slug: 'electrical-engineering',
    name: { en: 'Electrical Engineering', tr: 'Elektrik Mühendisliği', az: 'Elektrik Mühəndisliyi', ru: 'Электротехника' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-civil',
    slug: 'civil-engineering',
    name: { en: 'Civil Engineering', tr: 'İnşaat Mühendisliği', az: 'İnşaat Mühəndisliyi', ru: 'Гражданское строительство' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-bus-bach',
    slug: 'business-administration',
    name: { en: 'Business Administration', tr: 'İşletme', az: 'Biznesin İdarəedilməsi', ru: 'Бизнес-администрирование' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-bus-mba',
    slug: 'mba',
    name: { en: 'MBA', tr: 'MBA', az: 'MBA', ru: 'MBA' },
    degreeLevel: 'master',
    categorySlug: 'business',
    durationYears: 2,
  },
  {
    id: 'p-bus-irm',
    slug: 'international-relations',
    name: { en: 'International Relations', tr: 'Uluslararası İlişkiler', az: 'Beynəlxalq Münasibətlər', ru: 'Международные отношения' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-law-bach',
    slug: 'law',
    name: { en: 'Law', tr: 'Hukuk', az: 'Hüquq', ru: 'Право' },
    degreeLevel: 'bachelor',
    categorySlug: 'law',
    durationYears: 4,
  },
  {
    id: 'p-arch-bach',
    slug: 'architecture',
    name: { en: 'Architecture', tr: 'Mimarlık', az: 'Memarlıq', ru: 'Архитектура' },
    degreeLevel: 'bachelor',
    categorySlug: 'architecture',
    durationYears: 4,
  },
  {
    id: 'p-arts-bach',
    slug: 'industrial-design',
    name: { en: 'Industrial Design', tr: 'Endüstriyel Tasarım', az: 'Sənaye Dizaynı', ru: 'Промышленный дизайн' },
    degreeLevel: 'bachelor',
    categorySlug: 'arts',
    durationYears: 4,
  },
  {
    id: 'p-ai-master',
    slug: 'artificial-intelligence',
    name: { en: 'Artificial Intelligence (MSc)', tr: 'Yapay Zeka (YL)', az: 'Süni İntellekt (Magistr)', ru: 'Искусственный интеллект (Магистр)' },
    degreeLevel: 'master',
    categorySlug: 'computer-science',
    durationYears: 2,
  },
  {
    id: 'p-eng-mechatronics',
    slug: 'mechatronics-engineering',
    name: { en: 'Mechatronics Engineering', tr: 'Mekatronik Mühendisliği', az: 'Mekatronika Mühəndisliyi', ru: 'Мехатроника' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-chemical',
    slug: 'chemical-engineering',
    name: { en: 'Chemical Engineering', tr: 'Kimya Mühendisliği', az: 'Kimya Mühəndisliyi', ru: 'Химическая инженерия' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-automotive',
    slug: 'automotive-engineering',
    name: { en: 'Automotive Engineering', tr: 'Otomotiv Mühendisliği', az: 'Avtomobil Mühəndisliyi', ru: 'Автомобильная инженерия' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-industrial',
    slug: 'industrial-engineering',
    name: { en: 'Industrial Engineering', tr: 'Endüstri Mühendisliği', az: 'Sənaye Mühəndisliyi', ru: 'Промышленная инженерия' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-biomedical',
    slug: 'biomedical-engineering',
    name: { en: 'Biomedical Engineering', tr: 'Biyomedikal Mühendisliği', az: 'Biomedikal Mühəndisliyi', ru: 'Биомедицинская инженерия' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-aerospace',
    slug: 'aerospace-engineering',
    name: { en: 'Aerospace Engineering', tr: 'Havacılık ve Uzay Mühendisliği', az: 'Aviasiya və Kosmos Mühəndisliyi', ru: 'Аэрокосмическая инженерия' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-energy',
    slug: 'energy-systems-engineering',
    name: { en: 'Energy Systems Engineering', tr: 'Enerji Sistemleri Mühendisliği', az: 'Enerji Sistemləri Mühəndisliyi', ru: 'Инженерия энергетических систем' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-genetics',
    slug: 'genetics-and-bioengineering',
    name: { en: 'Genetics and Bioengineering', tr: 'Genetik ve Biyomühendislik', az: 'Genetika və Biomühəndislik', ru: 'Генетика и биоинженерия' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-petroleum',
    slug: 'petroleum-engineering',
    name: { en: 'Petroleum Engineering', tr: 'Petrol ve Doğal Gaz Mühendisliği', az: 'Neft və Qaz Mühəndisliyi', ru: 'Нефтегазовая инженерия' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-eng-environmental',
    slug: 'environmental-engineering',
    name: { en: 'Environmental Engineering', tr: 'Çevre Mühendisliği', az: 'Ekologiya Mühəndisliyi', ru: 'Экологическая инженерия' },
    degreeLevel: 'bachelor',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-cs-data-science',
    slug: 'data-science',
    name: { en: 'Data Science', tr: 'Veri Bilimi', az: 'Verilənlər Elmi', ru: 'Наука о данных' },
    degreeLevel: 'bachelor',
    categorySlug: 'computer-science',
    durationYears: 4,
  },
  {
    id: 'p-cs-cybersecurity',
    slug: 'cybersecurity',
    name: { en: 'Cybersecurity', tr: 'Siber Güvenlik', az: 'Kibertəhlükəsizlik', ru: 'Кибербезопасность' },
    degreeLevel: 'bachelor',
    categorySlug: 'computer-science',
    durationYears: 4,
  },
  {
    id: 'p-cs-info-systems',
    slug: 'information-systems',
    name: { en: 'Information Systems', tr: 'Bilişim Sistemleri', az: 'İnformasiya Sistemləri', ru: 'Информационные системы' },
    degreeLevel: 'bachelor',
    categorySlug: 'computer-science',
    durationYears: 4,
  },
  {
    id: 'p-cs-game-dev',
    slug: 'game-development',
    name: { en: 'Game Development', tr: 'Oyun Geliştirme', az: 'Oyun Yaradılması', ru: 'Разработка игр' },
    degreeLevel: 'bachelor',
    categorySlug: 'computer-science',
    durationYears: 4,
  },
  {
    id: 'p-bus-int-trade',
    slug: 'international-trade',
    name: { en: 'International Trade', tr: 'Uluslararası Ticaret', az: 'Beynəlxalq Ticarət', ru: 'Международная торговля' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-bus-marketing',
    slug: 'marketing',
    name: { en: 'Marketing', tr: 'Pazarlama', az: 'Marketinq', ru: 'Маркетинг' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-bus-economics',
    slug: 'economics',
    name: { en: 'Economics', tr: 'Ekonomi', az: 'İqtisadiyyat', ru: 'Экономика' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-bus-finance',
    slug: 'finance',
    name: { en: 'Finance', tr: 'Finans', az: 'Maliyyə', ru: 'Финансы' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-bus-accounting',
    slug: 'accounting',
    name: { en: 'Accounting', tr: 'Muhasebe', az: 'Mühasibat', ru: 'Бухгалтерский учёт' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-bus-hrm',
    slug: 'human-resources-management',
    name: { en: 'Human Resources Management', tr: 'İnsan Kaynakları Yönetimi', az: 'İnsan Resurslarının İdarəedilməsi', ru: 'Управление человеческими ресурсами' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-bus-scm',
    slug: 'supply-chain-management',
    name: { en: 'Supply Chain Management', tr: 'Tedarik Zinciri Yönetimi', az: 'Təchizat Zəncirinin İdarəedilməsi', ru: 'Управление цепочками поставок' },
    degreeLevel: 'bachelor',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-tour-tourism',
    slug: 'tourism-management',
    name: { en: 'Tourism Management', tr: 'Turizm İşletmeciliği', az: 'Turizm İdarəetməsi', ru: 'Менеджмент в туризме' },
    degreeLevel: 'bachelor',
    categorySlug: 'tourism',
    durationYears: 4,
  },
  {
    id: 'p-tour-hotel',
    slug: 'hotel-management',
    name: { en: 'Hotel Management', tr: 'Otel İşletmeciliği', az: 'Otel İdarəetməsi', ru: 'Гостиничный менеджмент' },
    degreeLevel: 'bachelor',
    categorySlug: 'tourism',
    durationYears: 4,
  },
  {
    id: 'p-tour-gastronomy',
    slug: 'gastronomy-and-culinary-arts',
    name: { en: 'Gastronomy and Culinary Arts', tr: 'Gastronomi ve Mutfak Sanatları', az: 'Qastronomiya və Aşpazlıq Sənəti', ru: 'Гастрономия и кулинарное искусство' },
    degreeLevel: 'bachelor',
    categorySlug: 'tourism',
    durationYears: 4,
  },
  {
    id: 'p-health-pharmacy',
    slug: 'pharmacy',
    name: { en: 'Pharmacy', tr: 'Eczacılık', az: 'Farmasiya', ru: 'Фармация' },
    degreeLevel: 'bachelor',
    categorySlug: 'health-sciences',
    durationYears: 5,
  },
  {
    id: 'p-health-nursing',
    slug: 'nursing',
    name: { en: 'Nursing', tr: 'Hemşirelik', az: 'Hemşirəlik', ru: 'Сестринское дело' },
    degreeLevel: 'bachelor',
    categorySlug: 'health-sciences',
    durationYears: 4,
  },
  {
    id: 'p-health-physio',
    slug: 'physiotherapy',
    name: { en: 'Physiotherapy', tr: 'Fizyoterapi', az: 'Fizioterapiya', ru: 'Физиотерапия' },
    degreeLevel: 'bachelor',
    categorySlug: 'health-sciences',
    durationYears: 4,
  },
  {
    id: 'p-health-nutrition',
    slug: 'nutrition-and-dietetics',
    name: { en: 'Nutrition and Dietetics', tr: 'Beslenme ve Diyetetik', az: 'Qidalanma və Dietetika', ru: 'Питание и диетология' },
    degreeLevel: 'bachelor',
    categorySlug: 'health-sciences',
    durationYears: 4,
  },
  {
    id: 'p-health-psychology',
    slug: 'psychology',
    name: { en: 'Psychology', tr: 'Psikoloji', az: 'Psixologiya', ru: 'Психология' },
    degreeLevel: 'bachelor',
    categorySlug: 'health-sciences',
    durationYears: 4,
  },
  {
    id: 'p-dent-prosthetics',
    slug: 'dental-prosthetics',
    name: { en: 'Dental Prosthetics', tr: 'Diş Protez', az: 'Diş Protezləri', ru: 'Зубное протезирование' },
    degreeLevel: 'associate',
    categorySlug: 'dentistry',
    durationYears: 2,
  },
  {
    id: 'p-health-biomed-tech',
    slug: 'biomedical-technology',
    name: { en: 'Biomedical Technology', tr: 'Biyomedikal Teknoloji', az: 'Biomedikal Texnologiyalar', ru: 'Биомедицинские технологии' },
    degreeLevel: 'bachelor',
    categorySlug: 'health-sciences',
    durationYears: 4,
  },
  {
    id: 'p-soc-political',
    slug: 'political-science',
    name: { en: 'Political Science', tr: 'Siyaset Bilimi', az: 'Siyasət Elmi', ru: 'Политология' },
    degreeLevel: 'bachelor',
    categorySlug: 'social-sciences',
    durationYears: 4,
  },
  {
    id: 'p-soc-sociology',
    slug: 'sociology',
    name: { en: 'Sociology', tr: 'Sosyoloji', az: 'Sosiologiya', ru: 'Социология' },
    degreeLevel: 'bachelor',
    categorySlug: 'social-sciences',
    durationYears: 4,
  },
  {
    id: 'p-soc-int-relations',
    slug: 'international-relations-social',
    name: { en: 'International Relations', tr: 'Uluslararası İlişkiler', az: 'Beynəlxalq Münasibətlər', ru: 'Международные отношения' },
    degreeLevel: 'bachelor',
    categorySlug: 'social-sciences',
    durationYears: 4,
  },
  {
    id: 'p-soc-public-admin',
    slug: 'public-administration',
    name: { en: 'Public Administration', tr: 'Kamu Yönetimi', az: 'Dövlət İdarəetməsi', ru: 'Государственное управление' },
    degreeLevel: 'bachelor',
    categorySlug: 'social-sciences',
    durationYears: 4,
  },
  {
    id: 'p-hum-history',
    slug: 'history',
    name: { en: 'History', tr: 'Tarih', az: 'Tarix', ru: 'История' },
    degreeLevel: 'bachelor',
    categorySlug: 'humanities',
    durationYears: 4,
  },
  {
    id: 'p-hum-literature',
    slug: 'turkish-language-and-literature',
    name: { en: 'Turkish Language and Literature', tr: 'Türk Dili ve Edebiyatı', az: 'Türk Dili və Ədəbiyyatı', ru: 'Турецкий язык и литература' },
    degreeLevel: 'bachelor',
    categorySlug: 'humanities',
    durationYears: 4,
  },
  {
    id: 'p-hum-philosophy',
    slug: 'philosophy',
    name: { en: 'Philosophy', tr: 'Felsefe', az: 'Fəlsəfə', ru: 'Философия' },
    degreeLevel: 'bachelor',
    categorySlug: 'humanities',
    durationYears: 4,
  },
  {
    id: 'p-hum-translation',
    slug: 'translation-and-interpreting',
    name: { en: 'Translation and Interpreting', tr: 'Mütercimlik ve Tercümanlık', az: 'Tərcümə və Təfsir', ru: 'Перевод и устный перевод' },
    degreeLevel: 'bachelor',
    categorySlug: 'humanities',
    durationYears: 4,
  },
  {
    id: 'p-com-journalism',
    slug: 'journalism',
    name: { en: 'Journalism', tr: 'Gazetecilik', az: 'Jurnalistika', ru: 'Журналистика' },
    degreeLevel: 'bachelor',
    categorySlug: 'communication',
    durationYears: 4,
  },
  {
    id: 'p-com-pr',
    slug: 'public-relations',
    name: { en: 'Public Relations', tr: 'Halkla İlişkiler', az: 'İctimai Əlaqələr', ru: 'Связи с общественностью' },
    degreeLevel: 'bachelor',
    categorySlug: 'communication',
    durationYears: 4,
  },
  {
    id: 'p-com-rtvc',
    slug: 'radio-television-and-cinema',
    name: { en: 'Radio, Television and Cinema', tr: 'Radyo, Televizyon ve Sinema', az: 'Radio, Televiziya və Kino', ru: 'Радио, телевидение и кино' },
    degreeLevel: 'bachelor',
    categorySlug: 'communication',
    durationYears: 4,
  },
  {
    id: 'p-com-advertising',
    slug: 'advertising',
    name: { en: 'Advertising', tr: 'Reklamcılık', az: 'Reklamçılıq', ru: 'Реклама' },
    degreeLevel: 'bachelor',
    categorySlug: 'communication',
    durationYears: 4,
  },
  {
    id: 'p-com-new-media',
    slug: 'new-media-and-communication',
    name: { en: 'New Media and Communication', tr: 'Yeni Medya ve İletişim', az: 'Yeni Media və Kommunikasiya', ru: 'Новые медиа и коммуникации' },
    degreeLevel: 'bachelor',
    categorySlug: 'communication',
    durationYears: 4,
  },
  {
    id: 'p-nat-mathematics',
    slug: 'mathematics',
    name: { en: 'Mathematics', tr: 'Matematik', az: 'Riyaziyyat', ru: 'Математика' },
    degreeLevel: 'bachelor',
    categorySlug: 'natural-sciences',
    durationYears: 4,
  },
  {
    id: 'p-nat-physics',
    slug: 'physics',
    name: { en: 'Physics', tr: 'Fizik', az: 'Fizika', ru: 'Физика' },
    degreeLevel: 'bachelor',
    categorySlug: 'natural-sciences',
    durationYears: 4,
  },
  {
    id: 'p-nat-chemistry',
    slug: 'chemistry',
    name: { en: 'Chemistry', tr: 'Kimya', az: 'Kimya', ru: 'Химия' },
    degreeLevel: 'bachelor',
    categorySlug: 'natural-sciences',
    durationYears: 4,
  },
  {
    id: 'p-nat-biology',
    slug: 'biology',
    name: { en: 'Biology', tr: 'Biyoloji', az: 'Biologiya', ru: 'Биология' },
    degreeLevel: 'bachelor',
    categorySlug: 'natural-sciences',
    durationYears: 4,
  },
  {
    id: 'p-nat-molbio',
    slug: 'molecular-biology-and-genetics',
    name: { en: 'Molecular Biology and Genetics', tr: 'Moleküler Biyoloji ve Genetik', az: 'Molekulyar Biologiya və Genetika', ru: 'Молекулярная биология и генетика' },
    degreeLevel: 'bachelor',
    categorySlug: 'natural-sciences',
    durationYears: 4,
  },
  {
    id: 'p-arts-graphic',
    slug: 'graphic-design',
    name: { en: 'Graphic Design', tr: 'Grafik Tasarım', az: 'Qrafik Dizayn', ru: 'Графический дизайн' },
    degreeLevel: 'bachelor',
    categorySlug: 'arts',
    durationYears: 4,
  },
  {
    id: 'p-arts-interior',
    slug: 'interior-architecture',
    name: { en: 'Interior Architecture', tr: 'İç Mimarlık', az: 'İnteryer Memarlığı', ru: 'Дизайн интерьера' },
    degreeLevel: 'bachelor',
    categorySlug: 'arts',
    durationYears: 4,
  },
  {
    id: 'p-arts-fashion',
    slug: 'fashion-design',
    name: { en: 'Fashion Design', tr: 'Moda Tasarımı', az: 'Moda Dizaynı', ru: 'Дизайн одежды' },
    degreeLevel: 'bachelor',
    categorySlug: 'arts',
    durationYears: 4,
  },
  {
    id: 'p-arts-music',
    slug: 'music',
    name: { en: 'Music', tr: 'Müzik', az: 'Musiqi', ru: 'Музыка' },
    degreeLevel: 'bachelor',
    categorySlug: 'arts',
    durationYears: 4,
  },
  {
    id: 'p-arts-cinema',
    slug: 'cinema-and-television',
    name: { en: 'Cinema and Television', tr: 'Sinema ve Televizyon', az: 'Kino və Televiziya', ru: 'Кино и телевидение' },
    degreeLevel: 'bachelor',
    categorySlug: 'arts',
    durationYears: 4,
  },
  {
    id: 'p-agri-food-eng',
    slug: 'food-engineering',
    name: { en: 'Food Engineering', tr: 'Gıda Mühendisliği', az: 'Qida Mühəndisliyi', ru: 'Пищевая инженерия' },
    degreeLevel: 'bachelor',
    categorySlug: 'agriculture',
    durationYears: 4,
  },
  {
    id: 'p-agri-agri-eng',
    slug: 'agricultural-engineering',
    name: { en: 'Agricultural Engineering', tr: 'Tarım Mühendisliği', az: 'Kənd Təsərrüfatı Mühəndisliyi', ru: 'Сельскохозяйственная инженерия' },
    degreeLevel: 'bachelor',
    categorySlug: 'agriculture',
    durationYears: 4,
  },
  {
    id: 'p-bus-mba-exec',
    slug: 'executive-mba',
    name: { en: 'Executive MBA', tr: 'Yönetici MBA', az: 'İcraçı MBA', ru: 'Executive MBA' },
    degreeLevel: 'master',
    categorySlug: 'business',
    durationYears: 2,
  },
  {
    id: 'p-eng-civil-master',
    slug: 'civil-engineering-master',
    name: { en: 'Civil Engineering (MSc)', tr: 'İnşaat Mühendisliği (YL)', az: 'İnşaat Mühəndisliyi (Magistr)', ru: 'Гражданское строительство (Магистр)' },
    degreeLevel: 'master',
    categorySlug: 'engineering',
    durationYears: 2,
  },
  {
    id: 'p-health-pharmacy-master',
    slug: 'pharmacy-master',
    name: { en: 'Pharmacy (MSc)', tr: 'Eczacılık (YL)', az: 'Farmasiya (Magistr)', ru: 'Фармация (Магистр)' },
    degreeLevel: 'master',
    categorySlug: 'health-sciences',
    durationYears: 2,
  },
  {
    id: 'p-eng-phd',
    slug: 'engineering-phd',
    name: { en: 'PhD in Engineering', tr: 'Mühendislik Doktorası', az: 'Mühəndislik Doktorantası', ru: 'Докторантура по инженерии' },
    degreeLevel: 'phd',
    categorySlug: 'engineering',
    durationYears: 4,
  },
  {
    id: 'p-bus-phd',
    slug: 'business-phd',
    name: { en: 'PhD in Business', tr: 'İşletme Doktorası', az: 'Biznes Doktorantası', ru: 'Докторантура по бизнесу' },
    degreeLevel: 'phd',
    categorySlug: 'business',
    durationYears: 4,
  },
  {
    id: 'p-med-phd',
    slug: 'medicine-phd',
    name: { en: 'PhD in Medicine', tr: 'Tıp Doktorası', az: 'Tibb Doktorantası', ru: 'Докторантура по медицине' },
    degreeLevel: 'phd',
    categorySlug: 'medicine',
    durationYears: 4,
  },
];
