import type { Review } from '@/types';

export const seedReviews: Review[] = [
  {
    id: 'r-1',
    universityId: 'u-bahcesehir',
    authorName: 'Leyla Mammadova',
    authorCountry: '🇦🇿 Azerbaijan',
    authorInitials: 'LM',
    rating: 5,
    text: {
      en: 'Great international environment and modern campus in the heart of Istanbul. The application process was smooth with my consultant.',
      tr: 'İstanbul\'un merkezinde harika uluslararası ortam ve modern kampüs. Başvuru süreci danışmanımla çok kolaydı.',
      az: 'İstanbulun mərkəzində əla beynəlxalq mühit və müasir kampus. Müraciət prosesi məsləhətçimlə çox rahat idi.',
      ru: 'Отличная международная среда и современный кампус в центре Стамбула. Процесс подачи заявки прошёл гладко.',
      de: 'Tolles internationales Umfeld und moderner Campus im Herzen von Istanbul. Der Bewerbungsprozess lief mit meinem Berater reibungslos.',
      fr: 'Excellent environnement international et campus moderne au cœur d\'Istanbul. Le processus de candidature s\'est bien passé avec mon conseiller.',
      fa: 'محیط بینالمللی عالی و پردیس مدرن در قلب استانبول. فرآیند ثبتنام با مشاورم روان پیش رفت.',
      ar: 'بيئة دولية رائعة وحرم جامعي حديث في قلب إسطنبول. كانت عملية التقديم سلسة مع مستشاري.',
      tk: 'Stambulyň merkezinde ajaýyp halkara gurşaw we döwrebap kampus. Ýüz tutmak prosesi maslahatçym bilen aňsat geçdi.',
      kk: 'Стамбулдың жүрегінде тамаша халықаралық орта және заманауи кампус. Өтінім процесі кеңесшіммен бірге тегіс өтті.',
      ky: 'Стамбулдун борборунда сонун эл аралык чөйрө жана заманбап кампус. Арыз берүү процесси кеңешчим менен жеңил өттү.',
      zh: '伊斯坦布尔市中心拥有极好的国际化环境和现代化校园。在顾问的帮助下申请过程很顺利。',
      bg: 'Чудесна международна среда и модерен кампус в центъра на Истанбул. Процесът на кандидатстване беше гладък с моя консултант.',
      ur: 'استنبول کے دل میں شاندار بین الاقوامی ماحول اور جدید کیمپس۔ میرے مشیر کے ساتھ درخواست کا عمل آسان تھا۔',
      uz: 'Istanbul markazida ajoyib xalqaro muhit va zamonaviy kampus. Maslahatchim bilan ariza jarayoni silliq o\'tdi.',
      sw: 'Mazingira bora ya kimataifa na kampasi ya kisasa katikati ya Istanbul. Mchakato wa kutuma ombi ulikuwa rahisi na mshauri wangu.',
      so: 'Deegaanka caalamiga ah ee wanaagsan iyo kambas casri ah ee bartamaha Istanbul. Nidaamka codsiga wuxuu ahaa mid fudud la taliyahayga.',
      id: 'Lingkungan internasional yang hebat dan kampus modern di jantung Istanbul. Proses aplikasi berjalan lancar dengan konsultan saya.',
    },
    verified: true,
    programStudied: { en: 'Computer Engineering', tr: 'Bilgisayar Mühendisliği', az: 'Kompüter Mühəndisliyi', ru: 'Компьютерная инженерия', de: 'Computertechnik', fr: 'Génie informatique', fa: 'مهندسی کامپیوتر', ar: 'هندسة الحاسوب', tk: 'Kompýuter inženerligi', kk: 'Компьютерлік инженерия', ky: 'Компьютер инженериясы', zh: '计算机工程', bg: 'Компютърно инженерство', ur: 'کمپیوٹر انجینئرنگ', uz: 'Kompyuter muhandisligi', sw: 'Uhandisi wa Kompyuta', so: 'Injineeriyada Kombiyuutarka', id: 'Teknik Komputer' },
    year: 2024,
  },
  {
    id: 'r-2',
    universityId: 'u-metu',
    authorName: 'Bekzod Karimov',
    authorCountry: '🇺🇿 Uzbekistan',
    authorInitials: 'BK',
    rating: 5,
    text: {
      en: 'METU exceeded my expectations. Fully English programs and a huge green campus. Strong career services.',
      tr: 'ODTÜ beklentilerimi aştı. Tamamen İngilizce programlar ve büyük yeşil kampüs. Güçlü kariyer hizmetleri.',
      az: 'ODTÜ gözləntilərimi aşdı. Tamamilə ingilis dilində proqramlar və böyük yaşıl kampus. Güclü karyera xidmətləri.',
      ru: 'ODTÜ превзошёл ожидания. Полностью англоязычные программы и огромный зелёный кампус.',
      de: 'Die METU hat meine Erwartungen übertroffen. Vollständig englischsprachige Programme und ein riesiger grüner Campus. Starker Karriereservice.',
      fr: 'L\'ODTÜ a dépassé mes attentes. Programmes entièrement en anglais et immense campus vert. Excellents services de carrière.',
      fa: 'ODTÜ فراتر از انتظارات من بود. برنامههای کاملاً انگلیسی و پردیس سبز بزرگ. خدمات شغلی قوی.',
      ar: 'تجاوزت ODTÜ توقعاتي. برامج إنجليزية بالكامل وحرم جامعي أخضر ضخم. خدمات مهنية قوية.',
      tk: 'ODTÜ meniň garaşýanlarymdan ýokary çykdy. Doly iňlis programmalary we ägirt ýaşyl kampus. Güýçli karýera hyzmatlary.',
      kk: 'ODTÜ күткенімнен асып түсті. Толығымен ағылшын бағдарламалары және үлкен жасыл кампус. Күшті мансап қызметтері.',
      ky: 'ODTÜ күткөндөрүмдөн ашты. Толугу менен англис программалары жана чоң жашыл кампус. Күчтүү карьера кызматтары.',
      zh: '中东技术大学超出了我的预期。全英文课程和巨大的绿色校园。强大的就业服务。',
      bg: 'ODTÜ надмина очакванията ми. Изцяло английски програми и огромен зелен кампус. Силни кариерни услуги.',
      ur: 'ODTÜ میری توقعات سے بڑھ گئی۔ مکمل انگریزی پروگرام اور بہت بڑا سبز کیمپس۔ مضبوط کیرئیر سروسز۔',
      uz: 'ODTÜ kutganimdan ham oshib ketdi. To\'liq ingliz tilidagi dasturlar va katta yashil kampus. Kuchli martaba xizmatlari.',
      sw: 'ODTÜ ilizidi kupita matarajio yangu. Programu za Kiingereza kamili na kampasi kubwa ya kijani. Huduma dhabiti za kazi.',
      so: 'ODTÜ waxay ka gudubtay rajooyinkayga. Barnaamijyo Ingiriisi buuxda iyo kambas weyn oo cagaaran. Adeegyo shaqo oo xooggan.',
      id: 'ODTÜ melampaui ekspektasi saya. Program berbahasa Inggris penuh dan kampus hijau yang luas. Layanan karier yang kuat.',
    },
    verified: true,
    programStudied: { en: 'Electrical Engineering', tr: 'Elektrik Mühendisliği', az: 'Elektrik Mühəndisliyi', ru: 'Электротехника', de: 'Elektrotechnik', fr: 'Génie électrique', fa: 'مهندسی برق', ar: 'الهندسة الكهربائية', tk: 'Elektrik inženerligi', kk: 'Электр инженериясы', ky: 'Электр инженериясы', zh: '电气工程', bg: 'Електроинженерство', ur: 'الیکٹریکل انجینئرنگ', uz: 'Elektr muhandisligi', sw: 'Uhandisi wa Umeme', so: 'Injineeriyada Korontada', id: 'Teknik Elektro' },
    year: 2023,
  },
  {
    id: 'r-3',
    universityId: 'u-bogazici',
    authorName: 'Aizat Nurlan',
    authorCountry: '🇰🇿 Kazakhstan',
    authorInitials: 'AN',
    rating: 5,
    text: {
      en: 'The prestige is real. Competitive to get in but worth every effort. The Bosphorus view never gets old.',
      tr: 'Prestij gerçek. Girmek rekabetçi ama her çabaya değer. Boğaz manzarası hiç eskimiyo.',
      az: 'Nüfuz gerçəkdir. Daxil olmaq rəqabətlidir, amma hər səyə dəyər. Boğaz mənzərəsi heç vaxt sıxmır.',
      ru: 'Престиж реален. Поступить сложно, но оно того стоит. Вид на Босфор не приедается.',
      de: 'Der Prestigewert ist real. Der Einstieg ist wettbewerbsintensiv, aber jede Anstrengung wert. Der Blick auf den Bosporus wird nie langweilig.',
      fr: 'Le prestige est réel. La sélection est compétitive mais en vaut chaque effort. La vue sur le Bosphore ne lasse jamais.',
      fa: 'اعتبار واقعی است. ورود رقابتی است اما ارزش هر تلاشی را دارد. منظره بسفر هرگز خستهکننده نمیشود.',
      ar: 'المكانة حقيقية. الدخول تنافسي لكنه يستحق كل جهد. منظر البوسفور لا يمل أبداً.',
      tk: 'Abraý hakykatdanam bar. Girmek bäsleşikli ýöne her tagallanyň derejesine degýär. Bosfor görnüşi hiç haçan ýadamaýar.',
      kk: 'Бедел нақты. Кіру бәсекелі, бірақ әр күшке тұрарлық. Босфор көрінісі ешқашан жалықтырмайды.',
      ky: 'Аброй чыныгы. Кирүү атаандаштык, бирок ар бир аракетке татыктуу. Босфор көрүнүшү эч качан жалыктырбайт.',
      zh: '声望是真实的。入学竞争激烈，但值得每一份努力。博斯普鲁斯海峡的景色百看不厌。',
      bg: 'Престижът е реален. Приемът е конкурентен, но си струва всяко усилие. Изгледът към Босфора никога не омръзва.',
      ur: 'عزت حقیقی ہے۔ داخلہ مقابلہ جاتی ہے لیکن ہر کوشش کے قابل ہے۔ باسفورس کا نظارہ کبھی پرانا نہیں ہوتا۔',
      uz: 'Nufuz haqiqiy. Kirish raqobatbardosh, lekin har bir harakatga arziydi. Bosfor manzarasi hech qachon zeriktirmaydi.',
      sw: 'Heshima ni halisi. Kuingia ni ushindani lakini kunastahili kila juhudi. Mtazamo wa Bosphorus hauchoshi kamwe.',
      so: 'Sharafku waa run. Galitaanku waa tartan laakiin waxaa u qalmaan dadaal kasta. Muuqaalka Bosphorus weligii ma daallo.',
      id: 'Prestisenya nyata. Masuknya kompetitif tetapi sepadan dengan setiap usaha. Pemandangan Bosphorus tidak pernah membosankan.',
    },
    verified: true,
    programStudied: { en: 'Business Administration', tr: 'İşletme', az: 'Biznesin İdarəedilməsi', ru: 'Бизнес-администрирование', de: 'Betriebswirtschaftslehre', fr: 'Administration des affaires', fa: 'مدیریت بازرگانی', ar: 'إدارة الأعمال', tk: 'Biznes dolandyryşy', kk: 'Іскерлік әкімшілендіру', ky: 'Бизнес башкаруу', zh: '工商管理', bg: 'Бизнес администрация', ur: 'بزنس ایڈمنسٹریشن', uz: 'Biznes boshqaruvi', sw: 'Usimamizi wa Biashara', so: 'Maamulka Ganacsiga', id: 'Administrasi Bisnis' },
    year: 2024,
  },
  {
    id: 'r-4',
    universityId: 'u-itu',
    authorName: 'Daniyar Soltan',
    authorCountry: '🇹🇲 Turkmenistan',
    authorInitials: 'DS',
    rating: 4,
    text: {
      en: 'Excellent engineering education and history. Some bureaucracy with paperwork, but faculty is world-class.',
      tr: 'Mükemmel mühendislik eğitimi ve tarih. Bazı bürokrasi var ama öğretim kadrosu dünya standartlarında.',
      az: 'Mükəmməl mühəndislik təhsili və tarix. Bəzi bürokratiya var, amma professor-müəllim heyəti dünya səviyyəsindədir.',
      ru: 'Отличное инженерное образование и история. Есть бюрократия, но преподаватели мирового уровня.',
      de: 'Hervorragende Ingenieurausbildung und Geschichte. Etwas Bürokratie bei den Unterlagen, aber die Fakultät ist erstklassig.',
      fr: 'Excellente formation d\'ingénieur et histoire riche. Quelques formalités administratives, mais un corps professoral de classe mondiale.',
      fa: 'آموزش مهندسی عالی و تاریخ غنی. کمی بروکراسی در مدارک، اما اساتید در سطح جهانی هستند.',
      ar: 'تعليم هندسي ممتاز وتاريخ عريق. بعض الروتين في الأوراق، لكن هيئة التدريس عالمية المستوى.',
      tk: 'Ajaýyp inžener okuwy we taryh. Resminamalarda belli bir bürokratiýa bar, ýöne professor-mugallymlar dünýä derejesinde.',
      kk: 'Тамаша инженерлік білім және тарих. Құжаттарда біраз бюрократия бар, бірақ оқытушылар әлемдік деңгейде.',
      ky: 'Мыкты инженердик билим жана тарых. Документтерде кээ бир бюрократия бар, бирок окутуучулар дүйнөлүк деңгээлде.',
      zh: '优秀的工程教育和历史。文书方面有些官僚程序，但师资是世界级的。',
      bg: 'Отлично инженерно образование и история. Има известна бюрокрация с документите, но преподавателите са от световна класа.',
      ur: 'بہترین انجینئرنگ تعلیم اور تاریخ۔ کاغذی کارروائی میں کچھ بیوروکریسی ہے لیکن فیکلٹی عالمی معیار کی ہے۔',
      uz: 'Ajoyib muhandislik ta\'limi va tarix. Hujjatlarda biroz byurokratiya bor, lekin professor-o\'qituvchilar jahon darajasida.',
      sw: 'Elimu bora ya uhandisi na historia. Kuna urasimu kidogo katika karatasi, lakini walimu ni wa kiwango cha kimataifa.',
      so: 'Waxbarasho injineeriyadeed oo aad u wanaagsan iyo taariikh. Waxaa jira birokaratiyada xaashiyada, laakiin macalimiintu waa heer caalami.',
      id: 'Pendidikan teknik yang sangat baik dan sejarah. Ada sedikit birokrasi dalam dokumen, tetapi fakultasnya kelas dunia.',
    },
    verified: true,
    programStudied: { en: 'Mechanical Engineering', tr: 'Makine Mühendisliği', az: 'Mexanika Mühəndisliyi', ru: 'Машиностроение', de: 'Maschinenbau', fr: 'Génie mécanique', fa: 'مهندسی مکانیک', ar: 'الهندسة الميكانيكية', tk: 'Mehaniki inženerlik', kk: 'Машина жасау инженериясы', ky: 'Механикалык инженерия', zh: '机械工程', bg: 'Машинно инженерство', ur: 'مکینیکل انجینئرنگ', uz: 'Mashinasozlik muhandisligi', sw: 'Uhandisi wa Mitambo', so: 'Injineeriyada Makaanikada', id: 'Teknik Mesin' },
    year: 2023,
  },
  {
    id: 'r-5',
    universityId: 'u-izmir-econ',
    authorName: 'Fatima Al-Hassan',
    authorCountry: '🇮🇶 Iraq',
    authorInitials: 'FA',
    rating: 5,
    text: {
      en: 'Izmir is a wonderful city to live in. The business faculty has great industry connections and internships.',
      tr: 'İzmir yaşamak için harika bir şehir. İşletme fakültesinin güçlü sanayi bağlantıları ve stajları var.',
      az: 'İzmir yaşamaq üçün əla şəhərdir. Biznes fakültəsinin güclü sənaye əlaqələri və təcrübələri var.',
      ru: 'Измир — прекрасный город для жизни. У бизнес-факультета отличные связи с индустрией и стажировки.',
      de: 'Izmir ist eine wunderbare Stadt zum Leben. Der Fachbereich Wirtschaft hat hervorragende Branchenkontakte und Praktika.',
      fr: 'Izmir est une ville merveilleuse où vivre. La faculté de commerce a d\'excellents liens avec l\'industrie et des stages.',
      fa: 'ازمیر شهر فوقالعادهای برای زندگی است. دانشکده تجارت ارتباطات صنعتی و کارآموزیهای عالی دارد.',
      ar: 'إزمير مدينة رائعة للعيش. كلية الأعمال لديها علاقات صناعية ممتازة وفرص تدريب.',
      tk: 'Izmir ýaşamak üçin ajaýyp şäher. Biznes fakulteti güýçli senagat aragatnaşyklaryna we praktika hödürleýär.',
      kk: 'Измир — тамаша өмір сүретін қала. Бизнес факультетінің өнеркәсіппен тамаша байланыстары мен практикалары бар.',
      ky: 'Измир жашоо үчүн сонун шаар. Бизнес факультетинин өнөр жай менен мыкты байланыштары жана практикалары бар.',
      zh: '伊兹密尔是一座非常适合居住的城市。商学院拥有出色的行业联系和实习机会。',
      bg: 'Измир е прекрасен град за живеене. Бизнес факултетът има отлични връзки с индустрията и стажове.',
      ur: 'ازمیر رہنے کے لیے ایک شاندار شہر ہے۔ بزنس فیکلٹی کے صنعت سے بہترین تعلقات اور انٹرن شپس ہیں۔',
      uz: 'Izmir yashash uchun ajoyib shahar. Biznes fakulteti sanoat bilan ajoyib aloqalarga va amaliyotlarga ega.',
      sw: 'Izmir ni mji mzuri wa kuishi. Kitivo cha biashara kina uhusiano mzuri na tasnia na mafunzo ya kazi.',
      so: 'Izmir waa magaalo aad u fiican oo la deggan yahay. Kulliyadda ganacsigu waxay leedahay xiriir wanaagsan oo warshadeed iyo tababaro shaqo.',
      id: 'Izmir adalah kota yang indah untuk ditinggali. Fakultas bisnis memiliki koneksi industri dan magang yang hebat.',
    },
    verified: true,
    programStudied: { en: 'Business Administration', tr: 'İşletme', az: 'Biznesin İdarəedilməsi', ru: 'Бизнес-администрирование', de: 'Betriebswirtschaftslehre', fr: 'Administration des affaires', fa: 'مدیریت بازرگانی', ar: 'إدارة الأعمال', tk: 'Biznes dolandyryşy', kk: 'Іскерлік әкімшілендіру', ky: 'Бизнес башкаруу', zh: '工商管理', bg: 'Бизнес администрация', ur: 'بزنس ایڈمنسٹریشن', uz: 'Biznes boshqaruvi', sw: 'Usimamizi wa Biashara', so: 'Maamulka Ganacsiga', id: 'Administrasi Bisnis' },
    year: 2024,
  },
  {
    id: 'r-6',
    universityId: 'u-ankara',
    authorName: 'Hassan Ali',
    authorCountry: '🇵🇰 Pakistan',
    authorInitials: 'HA',
    rating: 4,
    text: {
      en: 'Affordable tuition and a classic university experience. The law faculty is well respected.',
      tr: 'Uygun ücret ve klasik bir üniversite deneyimi. Hukuk fakültesi saygın.',
      az: 'Uyğun qiymət və klassik universitet təcrübəsi. Hüquq fakültəsi hörmətli sayılır.',
      ru: 'Доступная плата и классический университетский опыт. Юридический факультет уважаем.',
      de: 'Erschwingliche Studiengebühren und eine klassische Universitätserfahrung. Die juristische Fakultät ist angesehen.',
      fr: 'Frais abordables et expérience universitaire classique. La faculté de droit est très respectée.',
      fa: 'شهریه مقرونبهصرفه و تجربه دانشگاهی کلاسیک. دانشکده حقوق بسیار معتبر است.',
      ar: 'رسوم ميسورة وتجربة جامعية كلاسيكية. كلية الحقوق محترمة.',
      tk: 'Elýeterli töleg we nusgawy uniwersitet tejribesi. Hukuk fakulteti abraýly.',
      kk: 'Қолжетімді ақы және классикалық университет тәжірибесі. Заң факультеті беделді.',
      ky: 'Жеткиликтүү акы жана классикалык университет тажрыйбасы. Укук факультети кадыр-барктуу.',
      zh: '学费实惠，体验经典的大学氛围。法学院备受尊重。',
      bg: 'Достъпни такси и класическо университетско преживяване. Юридическият факултет е уважаван.',
      ur: 'سستی فیس اور کلاسک یونیورسٹی کا تجربہ۔ قانون فیکلٹی قابل احترام ہے۔',
      uz: 'Qulay narxlardagi to\'lov va klassik universitet tajribasi. Huquq fakulteti hurmatga sazovor.',
      sw: 'Ada nafuu na uzoefu wa kawaida wa chuo kikuu. Kitivo cha sheria kinaheshimiwa.',
      so: 'Lacag la awoodi karo iyo khibrad jaamacadeed oo caadi ah. Kulliyadda sharcigu waa la ixtiraamaa.',
      id: 'Biaya kuliah terjangkau dan pengalaman universitas klasik. Fakultas hukum sangat dihormati.',
    },
    verified: true,
    programStudied: { en: 'Law', tr: 'Hukuk', az: 'Hüquq', ru: 'Право', de: 'Jura', fr: 'Droit', fa: 'حقوق', ar: 'القانون', tk: 'Hukuk', kk: 'Құқық', ky: 'Укук', zh: '法学', bg: 'Право', ur: 'قانون', uz: 'Huquq', sw: 'Sheria', so: 'Sharciga', id: 'Hukum' },
    year: 2022,
  },
  {
    id: 'r-7',
    universityId: 'u-antalya-bilim',
    authorName: 'Saida Yusupova',
    authorCountry: '🇰🇬 Kyrgyzstan',
    authorInitials: 'SY',
    rating: 4,
    text: {
      en: 'Studying in Antalya is like a holiday every weekend. Friendly professors and a growing campus.',
      tr: 'Antalya\'da okumak her hafta sonu tatil gibi. Güler yüzlü hocalar ve büyüyen bir kampüs.',
      az: 'Antalyada oxumaq hər həftə sonu tətil kimidir. Mehriban müəllimlər və inkişaf edən kampus.',
      ru: 'Учиться в Анталье — как отпуск каждые выходные. Дружелюбные преподаватели и растущий кампус.',
      de: 'In Antalya zu studieren ist wie ein Urlaub jedes Wochenende. Freundliche Professoren und ein wachsender Campus.',
      fr: 'Étudier à Antalya, c\'est comme des vacances chaque week-end. Des professeurs sympathiques et un campus en plein essor.',
      fa: 'تحصیل در آنتالیا مثل تعطیلات در هر آخر هفته است. اساتید مهربان و پردیس در حال رشد.',
      ar: 'الدراسة في أنطاليا مثل عطلة كل نهاية أسبوع. أساتذة ودودون وحرم جامعي متنامٍ.',
      tk: 'Antalyada okamak her hepdäniň ahyrynda dynç almak ýaly. Myhmançylykly mugallymlar we ösýän kampus.',
      kk: 'Антальяда оқу — әр демалыста демалыстай. Мейірімді оқытушылар және өсіп келе жатқан кампус.',
      ky: 'Антальяда окуу ар бир дем алышта эс алуу сыяктуу. Мээримдүү окутуучулар жана өсүп жаткан кампус.',
      zh: '在安塔利亚学习就像每个周末都在度假。教授们很友善，校园也在不断壮大。',
      bg: 'Да учиш в Анталия е като почивка всеки уикенд. Приятелски настроени преподаватели и разрастващ се кампус.',
      ur: 'انطالیہ میں پڑھنا ہر ہفتے کے آخر میں چھٹی کی طرح ہے۔ دوستانہ پروفیسرز اور ایک بڑھتا ہوا کیمپس۔',
      uz: 'Antalyada o\'qish har hafta oxirida dam olish kabi. Do\'stona professorlar va o\'sayotgan kampus.',
      sw: 'Kusoma Antalya ni kama likizo kila wikendi. Maprofesa wa kirafiki na kampasi inayokua.',
      so: 'Barashada Antalya waxay lamid tahay fasax fiid kasta. Macallimiin saaxiibtinimo leh iyo kambas sii koraya.',
      id: 'Kuliah di Antalya seperti liburan setiap akhir pekan. Profesor yang ramah dan kampus yang berkembang.',
    },
    verified: false,
    programStudied: { en: 'International Relations', tr: 'Uluslararası İlişkiler', az: 'Beynəlxalq Münasibətlər', ru: 'Международные отношения', de: 'Internationale Beziehungen', fr: 'Relations internationales', fa: 'روابط بینالملل', ar: 'العلاقات الدولية', tk: 'Halkara gatnaşyklar', kk: 'Халықаралық қатынастар', ky: 'Эл аралык мамилелер', zh: '国际关系', bg: 'Международни отношения', ur: 'بین الاقوامی تعلقات', uz: 'Xalqaro munosabatlar', sw: 'Mahusiano ya Kimataifa', so: 'Xiriirka Caalamiga', id: 'Hubungan Internasional' },
    year: 2024,
  },
  {
    id: 'r-8',
    universityId: 'u-ytu',
    authorName: 'Rustam Rahimov',
    authorCountry: '🇹🇲 Turkmenistan',
    authorInitials: 'RR',
    rating: 5,
    text: {
      en: 'The architecture program is intense and rewarding. Great studios and workshops.',
      tr: 'Mimarlık programı yoğun ve ödüllendirici. Harika stüdyolar ve atölyeler.',
      az: 'Memarlıq proqramı intensiv və mükafatlandırıcıdır. Əla studiyalar və emaltıları.',
      ru: 'Архитектурная программа интенсивная и полезная. Отличные студии и мастерские.',
      de: 'Das Architekturprogramm ist intensiv und lohnend. Großartige Studios und Werkstätten.',
      fr: 'Le programme d\'architecture est intense et enrichissant. Excellents studios et ateliers.',
      fa: 'برنامه معماری فشرده و ارزشمند است. استودیوها و کارگاههای عالی.',
      ar: 'برنامج العمارة مكثف ومجزٍ. استوديوهات وورش عمل رائعة.',
      tk: 'Arhitektura programmasy intensiw we peýdaly. Ajaýyp studiýalar we ussahanalar.',
      kk: 'Сәулет бағдарламасы қарқынды және пайдалы. Тамаша студиялар мен шеберханалар.',
      ky: 'Архитектура программасы интенсивдүү жана пайдалуу. Сонун студиялар жана устаканалар.',
      zh: '建筑学课程紧凑且收获满满。工作室和工坊都很棒。',
      bg: 'Архитектурната програма е интензивна и възнаграждаваща. Чудесни студия и работилници.',
      ur: 'آرکیٹیکچر پروگرام شدید اور فائدہ مند ہے۔ شاندار اسٹوڈیوز اور ورکشاپس۔',
      uz: 'Arxitektura dasturi intensiv va foydali. Ajoyib studiyalar va ustaxonalar.',
      sw: 'Programu ya usanifu ni ngumu na inalipa. Studio na warsha bora.',
      so: 'Barnaamijka naqshadayntu waa mid xooggan oo faa\'iido leh. Studiooyin iyo goobo shaqo oo aad u wanaagsan.',
      id: 'Program arsitektur intensif dan bermanfaat. Studio dan bengkel kerja yang hebat.',
    },
    verified: true,
    programStudied: { en: 'Architecture', tr: 'Mimarlık', az: 'Memarlıq', ru: 'Архитектура', de: 'Architektur', fr: 'Architecture', fa: 'معماری', ar: 'العمارة', tk: 'Arhitektura', kk: 'Сәулет', ky: 'Архитектура', zh: '建筑学', bg: 'Архитектура', ur: 'فن تعمیر', uz: 'Arxitektura', sw: 'Usanifu', so: 'Naqshada', id: 'Arsitektur' },
    year: 2023,
  },
];
