import type { Review } from '@/types';

export const seedReviews: Review[] = [
  {
    id: 'r-1',
    universityId: 'u-bahcesehir',
    authorName: 'Leyla Mammadova',
    authorCountry: '🇦🇿 Azerbaijan',
    authorInitials: 'LM',
    rating: 5,
    text: {
      en: 'Great international environment and modern campus in the heart of Istanbul. The application process was smooth with my consultant.',
      tr: 'İstanbul\'un merkezinde harika uluslararası ortam ve modern kampüs. Başvuru süreci danışmanımla çok kolaydı.',
      az: 'İstanbulun mərkəzində əla beynəlxalq mühit və müasir kampus. Müraciət prosesi məsləhətçimlə çox rahat idi.',
      ru: 'Отличная международная среда и современный кампус в центре Стамбула. Процесс подачи заявки прошёл гладко.',
    },
    verified: true,
    programStudied: { en: 'Computer Engineering', tr: 'Bilgisayar Mühendisliği', az: 'Kompüter Mühəndisliyi', ru: 'Компьютерная инженерия' },
    year: 2024,
  },
  {
    id: 'r-2',
    universityId: 'u-metu',
    authorName: 'Bekzod Karimov',
    authorCountry: '🇺🇿 Uzbekistan',
    authorInitials: 'BK',
    rating: 5,
    text: {
      en: 'METU exceeded my expectations. Fully English programs and a huge green campus. Strong career services.',
      tr: 'ODTÜ beklentilerimi aştı. Tamamen İngilizce programlar ve büyük yeşil kampüs. Güçlü kariyer hizmetleri.',
      az: 'ODTÜ gözləntilərimi aşdı. Tamamilə ingilis dilində proqramlar və böyük yaşıl kampus. Güclü karyera xidmətləri.',
      ru: 'ODTÜ превзошёл ожидания. Полностью англоязычные программы и огромный зелёный кампус.',
    },
    verified: true,
    programStudied: { en: 'Electrical Engineering', tr: 'Elektrik Mühendisliği', az: 'Elektrik Mühəndisliyi', ru: 'Электротехника' },
    year: 2023,
  },
  {
    id: 'r-3',
    universityId: 'u-bogazici',
    authorName: 'Aizat Nurlan',
    authorCountry: '🇰🇿 Kazakhstan',
    authorInitials: 'AN',
    rating: 5,
    text: {
      en: 'The prestige is real. Competitive to get in but worth every effort. The Bosphorus view never gets old.',
      tr: 'Prestij gerçek. Girmek rekabetçi ama her çabaya değer. Boğaz manzarası hiç eskimiyo.',
      az: 'Nüfuz gerçəkdir. Daxil olmaq rəqabətlidir, amma hər səyə dəyər. Boğaz mənzərəsi heç vaxt sıxmır.',
      ru: 'Престиж реален. Поступить сложно, но оно того стоит. Вид на Босфор не приедается.',
    },
    verified: true,
    programStudied: { en: 'Business Administration', tr: 'İşletme', az: 'Biznesin İdarəedilməsi', ru: 'Бизнес-администрирование' },
    year: 2024,
  },
  {
    id: 'r-4',
    universityId: 'u-itu',
    authorName: 'Daniyar Soltan',
    authorCountry: '🇹🇲 Turkmenistan',
    authorInitials: 'DS',
    rating: 4,
    text: {
      en: 'Excellent engineering education and history. Some bureaucracy with paperwork, but faculty is world-class.',
      tr: 'Mükemmel mühendislik eğitimi ve tarih. Bazı bürokrasi var ama öğretim kadrosu dünya standartlarında.',
      az: 'Mükəmməl mühəndislik təhsili və tarix. Bəzi bürokratiya var, amma professor-müəllim heyəti dünya səviyyəsindədir.',
      ru: 'Отличное инженерное образование и история. Есть бюрократия, но преподаватели мирового уровня.',
    },
    verified: true,
    programStudied: { en: 'Mechanical Engineering', tr: 'Makine Mühendisliği', az: 'Mexanika Mühəndisliyi', ru: 'Машиностроение' },
    year: 2023,
  },
  {
    id: 'r-5',
    universityId: 'u-izmir-econ',
    authorName: 'Fatima Al-Hassan',
    authorCountry: '🇮🇶 Iraq',
    authorInitials: 'FA',
    rating: 5,
    text: {
      en: 'Izmir is a wonderful city to live in. The business faculty has great industry connections and internships.',
      tr: 'İzmir yaşamak için harika bir şehir. İşletme fakültesinin güçlü sanayi bağlantıları ve stajları var.',
      az: 'İzmir yaşamaq üçün əla şəhərdir. Biznes fakültəsinin güclü sənaye əlaqələri və təcrübələri var.',
      ru: 'Измир — прекрасный город для жизни. У бизнес-факультета отличные связи с индустрией и стажировки.',
    },
    verified: true,
    programStudied: { en: 'Business Administration', tr: 'İşletme', az: 'Biznesin İdarəedilməsi', ru: 'Бизнес-администрирование' },
    year: 2024,
  },
  {
    id: 'r-6',
    universityId: 'u-ankara',
    authorName: 'Hassan Ali',
    authorCountry: '🇵🇰 Pakistan',
    authorInitials: 'HA',
    rating: 4,
    text: {
      en: 'Affordable tuition and a classic university experience. The law faculty is well respected.',
      tr: 'Uygun ücret ve klasik bir üniversite deneyimi. Hukuk fakültesi saygın.',
      az: 'Uyğun qiymət və klassik universitet təcrübəsi. Hüquq fakültəsi hörmətli sayılır.',
      ru: 'Доступная плата и классический университетский опыт. Юридический факультет уважаем.',
    },
    verified: true,
    programStudied: { en: 'Law', tr: 'Hukuk', az: 'Hüquq', ru: 'Право' },
    year: 2022,
  },
  {
    id: 'r-7',
    universityId: 'u-antalya-bilim',
    authorName: 'Saida Yusupova',
    authorCountry: '🇰🇬 Kyrgyzstan',
    authorInitials: 'SY',
    rating: 4,
    text: {
      en: 'Studying in Antalya is like a holiday every weekend. Friendly professors and a growing campus.',
      tr: 'Antalya\'da okumak her hafta sonu tatil gibi. Güler yüzlü hocalar ve büyüyen bir kampüs.',
      az: 'Antalyada oxumaq hər həftə sonu tətil kimidir. Mehriban müəllimlər və inkişaf edən kampus.',
      ru: 'Учиться в Анталье — как отпуск каждые выходные. Дружелюбные преподаватели и растущий кампус.',
    },
    verified: false,
    programStudied: { en: 'International Relations', tr: 'Uluslararası İlişkiler', az: 'Beynəlxalq Münasibətlər', ru: 'Международные отношения' },
    year: 2024,
  },
  {
    id: 'r-8',
    universityId: 'u-ytu',
    authorName: 'Rustam Rahimov',
    authorCountry: '🇹🇲 Turkmenistan',
    authorInitials: 'RR',
    rating: 5,
    text: {
      en: 'The architecture program is intense and rewarding. Great studios and workshops.',
      tr: 'Mimarlık programı yoğun ve ödüllendirici. Harika stüdyolar ve atölyeler.',
      az: 'Memarlıq proqramı intensiv və mükafatlandırıcıdır. Əla studiyalar və emaltıları.',
      ru: 'Архитектурная программа интенсивная и полезная. Отличные студии и мастерские.',
    },
    verified: true,
    programStudied: { en: 'Architecture', tr: 'Mimarlık', az: 'Memarlıq', ru: 'Архитектура' },
    year: 2023,
  },
];
