import type { Scholarship } from '@/types';

export const seedScholarships: Scholarship[] = [
  {
    id: 's-1',
    universityId: 'u-bahcesehir',
    name: {
      en: 'International Merit Scholarship', tr: 'Uluslararası Başarı Bursu', az: 'Beynəlxalq Nailiyyət Təqaüdü', ru: 'Международная стипендия за заслуги',
      de: 'Internationales Leistungsstipendium', fr: 'Bourse internationale au mérite', fa: 'بورسیه بینالمللی شایستگی', ar: 'منحة الاستحقاق الدولية',
      tk: 'Halkara başaryş stipendiýasy', kk: 'Халықаралық жетістік стипендиясы', ky: 'Эл аралык жетишкендик стипендиясы', zh: '国际优秀奖学金',
      bg: 'Международна стипендия за успех', ur: 'بین الاقوامی میرٹ اسکالرشپ', uz: 'Xalqaro merit stipendiyasi', sw: 'Ufadhili wa Kimataifa wa Sifa',
      so: 'Deeqada Caalamiga ah ee Guusha', id: 'Beasiswa Prestasi Internasional',
    },
    percentage: 50,
    requirements: {
      en: 'GPA above 3.5 and a strong motivational letter.',
      tr: '3.5 üzeri not ortalaması ve güçlü bir motivasyon mektubu.',
      az: '3.5-dən yüksək ortalam və güclü motivasiya məktubu.',
      ru: 'Средний балл выше 3,5 и сильное мотивационное письмо.',
      de: 'Notendurchschnitt über 3,5 und ein starkes Motivationsschreiben.',
      fr: 'Moyenne supérieure à 3,5 et une lettre de motivation solide.',
      fa: 'معدل بالای ۳.۵ و نامه انگیزشی قوی.',
      ar: 'معدل أعلى من 3.5 وخطاب تحفيزي قوي.',
      tk: '3,5-den ýokary ortaça we güýçli höwes haty.',
      kk: 'Орташа балл 3,5-тен жоғары және күшті мотивациялық хат.',
      ky: 'Орточо балл 3,5тен жогору жана күчтүү мотивациялык кат.',
      zh: '平均绩点高于3.5且需提交有力的动机信。',
      bg: 'Среден успех над 3,5 и силно мотивационно писмо.',
      ur: '3.5 سے زیادہ GPA اور مضبوط حوصلہ افزائی خط۔',
      uz: 'O\'rtacha ball 3.5 dan yuqori va kuchli motivatsiya xati.',
      sw: 'GPA zaidi ya 3.5 na barua yenye nguvu ya motisha.',
      so: 'GPA ka sarreeya 3.5 iyo warqad dhiirigelin ah oo xooggan.',
      id: 'IPK di atas 3,5 dan surat motivasi yang kuat.',
    },
  },
  {
    id: 's-2',
    universityId: 'u-bahcesehir',
    name: {
      en: 'Early Application Discount', tr: 'Erken Başvuru İndirimi', az: 'Vaxtında Müraciət Endirimi', ru: 'Скидка за раннюю заявку',
      de: 'Frühbewerbungsrabatt', fr: 'Remise pour candidature précoce', fa: 'تخفیف ثبتنام زودهنگام', ar: 'خصم التقديم المبكر',
      tk: 'Ir öýtgeşme giriş endirimi', kk: 'Ерте өтінім жеңілдігі', ky: 'Эрте арыз берүү арзандатуусу', zh: '早申请折扣',
      bg: 'Отстъпка за ранен кандидатстване', ur: 'ابتدائی درخواست ڈسکاؤنٹ', uz: 'Erta ariza chegirmasi', sw: 'Punguzo la Kutuma Maombi Mapema',
      so: 'Qiimo dhimis Codsi Hore', id: 'Diskon Aplikasi Awal',
    },
    percentage: 25,
    requirements: {
      en: 'Apply before the early-bird deadline.',
      tr: 'Erken başvuru tarihinden önce başvurun.',
      az: 'Vaxtında müraciət tarixindən əvvəl müraciət edin.',
      ru: 'Подайте заявку до даты раннего обращения.',
      de: 'Bewerben Sie sich vor der Frühbewerbungsfrist.',
      fr: 'Candidater avant la date limite de pré-inscription.',
      fa: 'قبل از مهلت ثبتنام زودهنگام اقدام کنید.',
      ar: 'قدّم طلبك قبل الموعد النهائي للتقديم المبكر.',
      tk: 'Ir giriş möhletinden öň ýüz tutuň.',
      kk: 'Ерте өтінім мерзімінен бұрын өтінім беріңіз.',
      ky: 'Эрте арыз берүү мөөнөтүнөн мурун арыз бериңиз.',
      zh: '请在早鸟截止日期前申请。',
      bg: 'Кандидатствайте преди ранния срок.',
      ur: 'ابتدائی درخواست کی آخری تاریخ سے پہلے درخواست دیں۔',
      uz: 'Erta ariza muddatidan oldin ariza bering.',
      sw: 'Tuma ombi kabla ya tarehe ya mwisho ya mapema.',
      so: 'Codso ka hor taariikhda dambe ee codsiga hore.',
      id: 'Ajukan sebelum batas waktu pendaftaran awal.',
    },
  },
  {
    id: 's-3',
    universityId: 'u-metu',
    name: {
      en: 'Turkiye Burslari (Government)', tr: 'Türkiye Bursları (Devlet)', az: 'Türkiyə Təqaüdləri (Dövlət)', ru: 'Türkiye Bursları (Государственные)',
      de: 'Türkiye Bursları (Staatlich)', fr: 'Bourses Türkiye (Gouvernement)', fa: 'بورسیههای ترکیه (دولتی)', ar: 'منح تركيا (حكومية)',
      tk: 'Türkiye stipendiýalary (Döwlet)', kk: 'Türkiye стипендиялары (Мемлекеттік)', ky: 'Türkiye стипендиялары (Мамлекеттик)', zh: '土耳其政府奖学金',
      bg: 'Türkiye Bursları (Държавни)', ur: 'ترکی اسکالرشپس (سرکاری)', uz: 'Türkiye stipendiyalari (Davlat)', sw: 'Ufadhili wa Türkiye (Serikali)',
      so: 'Deeqaha Türkiye (Dawladda)', id: 'Beasiswa Türkiye (Pemerintah)',
    },
    percentage: 100,
    requirements: {
      en: 'National government scholarship program with full tuition, accommodation and stipend.',
      tr: 'Tam ücret, konaklama ve burs sağlayan ulusal devlet burs programı.',
      az: 'Tam tədris haqqı, qalma yeri və təqaüd təklif edən milli dövlət təqaüd proqramı.',
      ru: 'Государственная стипендия: полное покрытие обучения, проживание и стипендия.',
      de: 'Staatliches Stipendienprogramm mit voller Studiengebühr, Unterkunft und Stipendium.',
      fr: 'Programme gouvernemental couvrant l\'intégralité des frais, le logement et une allocation.',
      fa: 'برنامه بورسیه دولتی با پوشش کامل شهریه، مسکن و کمک هزینه.',
      ar: 'برنامج منح حكومي يغطي الرسوم والسكن والراتب بالكامل.',
      tk: 'Doly okuw tölegi, ýaşaýyş we stipendiýa berýän döwlet stipendiýa programmasy.',
      kk: 'Оқу ақысын, тұрғын үйді және стипендияны толық қамтитын мемлекеттік бағдарлама.',
      ky: 'Окуу акысын, туракжайды жана стипендияны толук камтыган мамлекеттик программа.',
      zh: '政府奖学金项目，涵盖全额学费、住宿和生活津贴。',
      bg: 'Държавна програма, покриваща пълно обучение, настаняване и стипендия.',
      ur: 'سرکاری اسکالرشپ پروگرام مکمل ٹیوشن، رہائش اور وظیفہ فراہم کرتا ہے۔',
      uz: 'To\'liq o\'qish to\'lovi, yashash va stipendiyani qoplaydigan davlat stipendiya dasturi.',
      sw: 'Mpango wa serikali unaolipa ada kamili, malazi na posho.',
      so: 'Barnaamij dawladeed oo daboolaya lacagta waxbarashada, hoyga iyo deeqda oo dhan.',
      id: 'Program beasiswa pemerintah dengan biaya kuliah, akomodasi, dan tunjangan penuh.',
    },
  },
  {
    id: 's-4',
    universityId: 'u-izmir-econ',
    name: {
      en: 'Design Talent Award', tr: 'Tasarım Yetenek Ödülü', az: 'Dizayn İstedad Mükafatı', ru: 'Премия за талант в дизайне',
      de: 'Design-Talentpreis', fr: 'Prix du talent en design', fa: 'جایزه استعداد طراحی', ar: 'جائزة الموهبة في التصميم',
      tk: 'Dizaýn zehin baýragy', kk: 'Дизайн дарын сыйлығы', ky: 'Дизайн талант сыйлыгы', zh: '设计人才奖',
      bg: 'Награда за дизайнерски талант', ur: 'ڈیزائن ٹیلنٹ ایوارڈ', uz: 'Dizayn iqtidori mukofoti', sw: 'Tuzo la Talanta ya Ubunifu',
      so: 'Abaalmarinta Hibada Naqshadaynta', id: 'Penghargaan Bakat Desain',
    },
    percentage: 40,
    requirements: {
      en: 'Portfolio review for design and architecture applicants.',
      tr: 'Tasarım ve mimarlık başvuru sahipleri için portföy değerlendirmesi.',
      az: 'Dizayn və memarlıq müraciətçiləri üçün portfel qiymətləndirməsi.',
      ru: 'Проверка портфолио для абитуриентов дизайна и архитектуры.',
      de: 'Portfolio-Prüfung für Design- und Architekturbewerber.',
      fr: 'Examen du portfolio pour les candidats en design et architecture.',
      fa: 'بررسی نمونهکار برای متقاضیان طراحی و معماری.',
      ar: 'مراجعة ملف الأعمال لمتقدمي التصميم والعمارة.',
      tk: 'Dizaýn we arhitektura dalaşgärleri üçin portfolio gözden geçirmesi.',
      kk: 'Дизайн және сәулет үміткерлері үшін портфолио тексеру.',
      ky: 'Дизайн жана архитектура талапкерлери үчүн портфолио текшерүү.',
      zh: '对设计和建筑申请者进行作品集审查。',
      bg: 'Преглед на портфолио за кандидати по дизайн и архитектура.',
      ur: 'ڈیزائن اور آرکیٹیکچر درخواست دہندگان کے لیے پورٹ فولیو جائزہ۔',
      uz: 'Dizayn va arxitektura abituriyentlari uchun portfel tekshiruvi.',
      sw: 'Ukaguzi wa portfolio kwa waombaji wa ubunifu na usanifu.',
      so: 'Faahfaahin faylka loogu talagalay codsadayaasha naqshada iyo dhismaha.',
      id: 'Peninjauan portofolio untuk pelamar desain dan arsitektur.',
    },
  },
  {
    id: 's-5',
    universityId: 'u-antalya-bilim',
    name: {
      en: 'Regional Grant', tr: 'Bölge Hibesi', az: 'Regional Qrant', ru: 'Региональный грант',
      de: 'Regionales Stipendium', fr: 'Bourse régionale', fa: 'گرنت منطقهای', ar: 'منحة إقليمية',
      tk: 'Sebit granty', kk: 'Аймақтық грант', ky: 'Аймактык грант', zh: '地区奖学金',
      bg: 'Регионална стипендия', ur: 'علاقائی گرانٹ', uz: 'Mintaqaviy grant', sw: 'Ruzuku ya Kikanda',
      so: 'Deeq Goboleed', id: 'Hibah Regional',
    },
    percentage: 30,
    requirements: {
      en: 'Available for students from selected partner countries.',
      tr: 'Seçili partner ülkelerden gelen öğrenciler içindir.',
      az: 'Seçilmiş tərəfdaş ölkələrdən gələn tələbələr üçündür.',
      ru: 'Для студентов из избранных стран-партнёров.',
      de: 'Für Studierende aus ausgewählten Partnerländern.',
      fr: 'Pour les étudiants de certains pays partenaires.',
      fa: 'برای دانشجویان کشورهای منتخب شریک.',
      ar: 'متاح للطلاب من الدول الشريكة المختارة.',
      tk: 'Saýlanan hyzmatdaş ýurtlardan gelen talyplar üçin.',
      kk: 'Таңдаулы серіктес елдердің студенттері үшін.',
      ky: 'Тандалган өнөктөш өлкөлөрдүн студенттери үчүн.',
      zh: '面向特定合作国家的学生。',
      bg: 'За студенти от избрани партньорски държави.',
      ur: 'منتخب پارٹنر ممالک کے طلباء کے لیے دستیاب۔',
      uz: 'Tanlangan hamkor davlatlar talabalari uchun.',
      sw: 'Inapatikana kwa wanafunzi kutoka nchi shirika zilizochaguliwa.',
      so: 'Waxaa loogu talagalay ardayda ka timaadda dalalka la xulay ee la shaqeeya.',
      id: 'Tersedia untuk mahasiswa dari negara mitra terpilih.',
    },
  },
];
