/**
 * Local university imagery downloaded from StudyLeo's public CDN.
 *
 * StudyLeo's featured images are used as the campus hero for the matching
 * universities (same institution, real building photos instead of generic
 * stock). Files live at:
 *   public/images/universities/{slug}/hero.webp
 *
 * A university whose slug is NOT in this map keeps its stock seedImages hero.
 */
export const universityHeroImages: Record<string, string> = {
  'bahcesehir-university': '/images/universities/bahcesehir-university/hero.webp',
  'izmir-university-of-economics': '/images/universities/izmir-university-of-economics/hero.webp',
  'antalya-bilim-university': '/images/universities/antalya-bilim-university/hero.webp',
  'konya-food-and-agriculture-university': '/images/universities/konya-food-and-agriculture-university/hero.webp',
  'istanbul-medipol-university': '/images/universities/istanbul-medipol-university/hero.webp',
  'istanbul-topkapi-university': '/images/universities/istanbul-topkapi-university/hero.webp',
  'halic-university': '/images/universities/halic-university/hero.webp',
  'istanbul-yeni-yuzyil-university': '/images/universities/istanbul-yeni-yuzyil-university/hero.webp',
  'istanbul-esenyurt-university': '/images/universities/istanbul-esenyurt-university/hero.webp',
  'istanbul-nisantasi-university': '/images/universities/istanbul-nisantasi-university/hero.webp',
  'uskudar-university': '/images/universities/uskudar-university/hero.webp',
  'biruni-university': '/images/universities/biruni-university/hero.webp',
  'altinbas-university': '/images/universities/altinbas-university/hero.webp',
  'istinye-university': '/images/universities/istinye-university/hero.webp',
  'istanbul-gelisim-university': '/images/universities/istanbul-gelisim-university/hero.webp',
  'istanbul-aydin-university': '/images/universities/istanbul-aydin-university/hero.webp',
  'istanbul-gedik-university': '/images/universities/istanbul-gedik-university/hero.webp',
  'sabanci-university': '/images/universities/sabanci-university/hero.webp',
  'koc-university': '/images/universities/koc-university/hero.webp',
  'atasehir-adiguzel-vocational-school': '/images/universities/atasehir-adiguzel-vocational-school/hero.webp',
  'mef-university': '/images/universities/mef-university/hero.webp',
  'istanbul-health-and-technology-university': '/images/universities/istanbul-health-and-technology-university/hero.webp',
  'istanbul-29-mayis-university': '/images/universities/istanbul-29-mayis-university/hero.webp',
  'istanbul-sisli-vocational-school': '/images/universities/istanbul-sisli-vocational-school/hero.webp',
  'istanbul-vocational-school-of-health-and-social-sciences': '/images/universities/istanbul-vocational-school-of-health-and-social-sciences/hero.webp',
  'demiroglu-bilim-university': '/images/universities/demiroglu-bilim-university/hero.webp',
  'maltepe-university': '/images/universities/maltepe-university/hero.webp',
  'istanbul-galata-university': '/images/universities/istanbul-galata-university/hero.webp',
  'ibn-haldun-university': '/images/universities/ibn-haldun-university/hero.webp',
  'kadir-has-university': '/images/universities/kadir-has-university/hero.webp',
  'istanbul-okan-university': '/images/universities/istanbul-okan-university/hero.webp',
  'isik-university': '/images/universities/isik-university/hero.webp',
  'yeditepe-university': '/images/universities/yeditepe-university/hero.webp',
  'fatih-sultan-mehmet-university': '/images/universities/fatih-sultan-mehmet-university/hero.webp',
  'istanbul-arel-university': '/images/universities/istanbul-arel-university/hero.webp',
  'istanbul-atlas-university': '/images/universities/istanbul-atlas-university/hero.webp',
  'istanbul-sabahattin-zaim-university': '/images/universities/istanbul-sabahattin-zaim-university/hero.webp',
  'bezmi-alem-university': '/images/universities/bezmi-alem-university/hero.webp',
  'istanbul-beykent-university': '/images/universities/istanbul-beykent-university/hero.webp',
  'istanbul-kultur-university': '/images/universities/istanbul-kultur-university/hero.webp',
  'istanbul-commerce-university': '/images/universities/istanbul-commerce-university/hero.webp',
  'beykoz-university': '/images/universities/beykoz-university/hero.webp',
  'ozyegin-university': '/images/universities/ozyegin-university/hero.webp',
  'dogus-university': '/images/universities/dogus-university/hero.webp',
  'istanbul-rumeli-university': '/images/universities/istanbul-rumeli-university/hero.webp',
  'istanbul-kent-university': '/images/universities/istanbul-kent-university/hero.webp',
  'fenerbahce-university': '/images/universities/fenerbahce-university/hero.webp',
  'acibadem-mehmet-ali-aydinlar-university': '/images/universities/acibadem-mehmet-ali-aydinlar-university/hero.webp',
  'piri-reis-university': '/images/universities/piri-reis-university/hero.webp',
  'ankara-medipol-university': '/images/universities/ankara-medipol-university/hero.webp',
  'turkish-aeronautical-association-university': '/images/universities/turkish-aeronautical-association-university/hero.webp',
  'ufuk-university': '/images/universities/ufuk-university/hero.webp',
  'cankaya-university': '/images/universities/cankaya-university/hero.webp',
  'yuksek-ihtisas-university': '/images/universities/yuksek-ihtisas-university/hero.webp',
  'lokman-hekim-university': '/images/universities/lokman-hekim-university/hero.webp',
  'tobb-university-of-economics-and-technology': '/images/universities/tobb-university-of-economics-and-technology/hero.webp',
  'bilkent-university': '/images/universities/bilkent-university/hero.webp',
  'ostim-technical-university': '/images/universities/ostim-technical-university/hero.webp',
  'ted-university': '/images/universities/ted-university/hero.webp',
  'baskent-university': '/images/universities/baskent-university/hero.webp',
  'atilim-university': '/images/universities/atilim-university/hero.webp',
  'ankara-bilim-university': '/images/universities/ankara-bilim-university/hero.webp',
  'izmir-tinaztepe-university': '/images/universities/izmir-tinaztepe-university/hero.webp',
  'izmir-kavram-vocational-school': '/images/universities/izmir-kavram-vocational-school/hero.webp',
  'yasar-university': '/images/universities/yasar-university/hero.webp',
  'antalya-belek-university': '/images/universities/antalya-belek-university/hero.webp',
  'alanya-university': '/images/universities/alanya-university/hero.webp',
  'kto-karatay-university': '/images/universities/kto-karatay-university/hero.webp',
  'avrasya-university': '/images/universities/avrasya-university/hero.webp',
  'toros-university': '/images/universities/toros-university/hero.webp',
  'cag-university': '/images/universities/cag-university/hero.webp',
  'sanko-university': '/images/universities/sanko-university/hero.webp',
  'hasan-kalyoncu-university': '/images/universities/hasan-kalyoncu-university/hero.webp',
  'nuh-naci-yazgan-university': '/images/universities/nuh-naci-yazgan-university/hero.webp',
  'cappadocia-university': '/images/universities/cappadocia-university/hero.webp',
  'kocaeli-university-of-health-and-technology': '/images/universities/kocaeli-university-of-health-and-technology/hero.webp',
};
