import type { University } from '@/types';
import { seedImages } from './images';

export const seedUniversities: University[] = [
  {
    id: 'u-bahcesehir',
    name: 'Bahçeşehir University',
    slug: 'bahcesehir-university',
    cityId: 'c-istanbul',
    foundedYear: 1998,
    studentCount: 30000,
    ranking: 45,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'BAU',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.campusLibrary, seedImages.students],
    languages: ['en', 'tr'],
    featured: true,
    tagline: {
      en: 'A global university in the heart of Istanbul',
      tr: "İstanbul'un merkezinde küresel bir üniversite",
      az: 'İstanbulun mərkəzində qlobal universitet',
      ru: 'Глобальный университет в центре Стамбула',
    },
    description: {
      en: 'Bahçeşehir University is a leading private university with a strong international focus, offering English-taught programs and partnerships across the globe.',
      tr: 'Bahçeşehir Üniversitesi, güçlü uluslararası odaklı, İngilizce eğitim veren ve dünya çapında ortaklıklara sahip önde gelen bir vakıf üniversitesidir.',
      az: 'Bahçeşehir Universiteti güclü beynəlxalq yönümlü, ingilis dilində təhsil verən və dünya üzrə tərəfdaşlıqlara malik aparıcı özəl universitetdir.',
      ru: 'Бахчешеширский университет — ведущий частный университет с сильной международной направленностью, обучающий на английском языке и имеющий партнёров по всему миру.',
    },
  },
  {
    id: 'u-itu',
    name: 'Istanbul Technical University',
    slug: 'istanbul-technical-university',
    cityId: 'c-istanbul',
    foundedYear: 1773,
    studentCount: 42000,
    ranking: 8,
    accreditation: 'YÖK Accredited',
    isState: true,
    logoText: 'İTÜ',
    heroImage: seedImages.engineering,
    gallery: [seedImages.campusAerial, seedImages.engineering, seedImages.computer],
    languages: ['en', 'tr'],
    featured: true,
    tagline: {
      en: 'Engineering excellence since 1773',
      tr: '1773\'ten beri mühendislik mükemmelliği',
      az: '1773-cü ildən mühəndislik mükəmməlliyi',
      ru: 'Инженерное совершенство с 1773 года',
    },
    description: {
      en: 'One of the world\'s oldest technical universities, İTÜ is renowned for engineering, architecture and science programs taught in English and Turkish.',
      tr: 'Dünyanın en eski teknik üniversitelerinden biri olan İTÜ, İngilizce ve Türkçe eğitim veren mühendislik, mimarlık ve fen programlarıyla tanınır.',
      az: 'Dünyanın ən qədim texniki universitetlərindən biri olan İTÜ ingilis və türk dilində tədris olunan mühəndislik, memarlıq və elm proqramları ilə tanınır.',
      ru: 'Один из старейших технических университетов мира, ИТЮ славится инженерными, архитектурными и научными программами на английском и турецком языках.',
    },
  },
  {
    id: 'u-bogazici',
    name: 'Boğaziçi University',
    slug: 'bogazici-university',
    cityId: 'c-istanbul',
    foundedYear: 1863,
    studentCount: 16000,
    ranking: 3,
    accreditation: 'YÖK Accredited',
    isState: true,
    logoText: 'BU',
    heroImage: seedImages.campusLibrary,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: true,
    tagline: {
      en: 'Turkey\'s most prestigious English-medium university',
      tr: 'Türkiye\'nin en prestijli İngilizce eğitim üniversitesi',
      az: 'Türkiyənin ən nüfuzlu ingilis dilində təhsil universiteti',
      ru: 'Самый престижный англоязычный университет Турции',
    },
    description: {
      en: 'Boğaziçi University is a top-ranked public university overlooking the Bosphorus, offering fully English-taught programs across sciences and humanities.',
      tr: 'Boğaziçi Üniversitesi, Boğaz manzaralı, fen ve sosyal bilimlerde tamamen İngilizce eğitim veren en üst düzey devlet üniversitesidir.',
      az: 'Boğaziçi Universiteti Boğaz mənzərəli, elm və humanitar sahələrdə tamamilə ingilis dilində təhsil verən ən yüksək dəvlət universitetidir.',
      ru: 'Богазичи университет — ведущий государственный университет с видом на Босфор, обучающий полностью на английском языке.',
    },
  },
  {
    id: 'u-metu',
    name: 'Middle East Technical University',
    slug: 'middle-east-technical-university',
    cityId: 'c-ankara',
    foundedYear: 1956,
    studentCount: 28000,
    ranking: 5,
    accreditation: 'YÖK Accredited',
    isState: true,
    logoText: 'ODTÜ',
    heroImage: seedImages.campusAerial,
    gallery: [seedImages.engineering, seedImages.computer, seedImages.students],
    languages: ['en'],
    featured: true,
    tagline: {
      en: 'English-medium excellence in the capital',
      tr: 'Başkentte İngilizce eğitim mükemmelliği',
      az: 'Paytaxtda ingilis dilində təhsil mükəmməlliyi',
      ru: 'Англоязычное совершенство в столице',
    },
    description: {
      en: 'METU (ODTÜ) is a flagship public university in Ankara, fully English-medium, famous for engineering and natural sciences and its vast forested campus.',
      tr: 'ODTÜ, Ankara\'da tamamen İngilizce eğitim veren, mühendislik ve fen bilimleriyle ünlü geniş ormanlık kampüsüyle öne çıkan bir devlet üniversitesidir.',
      az: 'ODTÜ Ankarada tamamilə ingilis dilində təhsil verən, mühəndislik və təbiət elmləri ilə məşhur geniş meşəlik kampusu ilə seçilən dövlət universitetidir.',
      ru: 'ODTÜ — ведущий государственный университет в Анкаре, полностью англоязычный, известный инженерными и естественными науками и огромным лесистым кампусом.',
    },
  },
  {
    id: 'u-ankara',
    name: 'Ankara University',
    slug: 'ankara-university',
    cityId: 'c-ankara',
    foundedYear: 1946,
    studentCount: 70000,
    ranking: 12,
    accreditation: 'YÖK Accredited',
    isState: true,
    logoText: 'AU',
    heroImage: seedImages.law,
    gallery: [seedImages.campusBuilding, seedImages.law, seedImages.business],
    languages: ['tr', 'en'],
    tagline: {
      en: 'The first university of the Republic',
      tr: 'Cumhuriyetin ilk üniversitesi',
      az: 'Respublikanın ilk universiteti',
      ru: 'Первый университет Республики',
    },
    description: {
      en: 'Ankara University is a historic public university offering a broad range of programs from law and medicine to social sciences.',
      tr: 'Ankara Üniversitesi, hukuk ve tıptan sosyal bilimlere kadar geniş program yelpazesi sunan tarihi bir devlet üniversitesidir.',
      az: 'Ankara Universiteti hüquq və tibbdən sosial elmlərə qədər geniş proqram çeşidi təklif edən tarixi dövlət universitetidir.',
      ru: 'Анкарский университет — исторический государственный университет с широким спектром программ от права и медицины до социальных наук.',
    },
  },
  {
    id: 'u-izmir-econ',
    name: 'Izmir University of Economics',
    slug: 'izmir-university-of-economics',
    cityId: 'c-izmir',
    foundedYear: 2001,
    studentCount: 9000,
    ranking: 60,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'İUE',
    heroImage: seedImages.business,
    gallery: [seedImages.business, seedImages.campusLibrary, seedImages.izmir],
    languages: ['en', 'tr'],
    tagline: {
      en: 'Coastal city, global mindset',
      tr: 'Sahil şehri, küresel vizyon',
      az: 'Sahil şəhəri, qlobal baxış',
      ru: 'Прибрежный город, глобальное мышление',
    },
    description: {
      en: 'A private university in Izmir focused on economics, business and design, with many English-taught programs and international exchange options.',
      tr: "İzmir'de ekonomi, işletme ve tasarım odaklı, birçok İngilizce program ve uluslararası değişim seçeneği sunan bir vakıf üniversitesidir.",
      az: 'İzmirdə iqtisadiyyat, biznes və dizayn yönümlü, bir çox ingilis dilində proqram və beynəlxalq mübadilə seçimi təklif edən özəl universitetdir.',
      ru: 'Частный университет в Измире с фокусом на экономику, бизнес и дизайн, множеством англоязычных программ и международным обменом.',
    },
  },
  {
    id: 'u-btu',
    name: 'Bursa Technical University',
    slug: 'bursa-technical-university',
    cityId: 'c-bursa',
    foundedYear: 2010,
    studentCount: 8000,
    ranking: 80,
    accreditation: 'YÖK Accredited',
    isState: true,
    logoText: 'BTÜ',
    heroImage: seedImages.engineering,
    gallery: [seedImages.campusAerial, seedImages.engineering, seedImages.bursa],
    languages: ['tr', 'en'],
    tagline: {
      en: 'Modern engineering in an industrial hub',
      tr: 'Sanayi merkezinde modern mühendislik',
      az: 'Sənaye mərkəzində müasir mühəndislik',
      ru: 'Современная инженерия в промышленном центре',
    },
    description: {
      en: 'A young public university in Bursa with strong ties to industry, focused on engineering, natural sciences and technology.',
      tr: 'Sanayi ile güçlü bağları olan, mühendislik, fen ve teknolojiye odaklanan genç bir Bursa devlet üniversitesidir.',
      az: 'Sənaye ilə güclü əlaqələri olan, mühəndislik, təbiət elmləri və texnologiyaya yönəlmiş gənc Bursa dövlət universitetidir.',
      ru: 'Молодой государственный университет в Бурсе с сильными связями с промышленностью, ориентированный на инженерию и технологии.',
    },
  },
  {
    id: 'u-antalya-bilim',
    name: 'Antalya Bilim University',
    slug: 'antalya-bilim-university',
    cityId: 'c-antalya',
    foundedYear: 2010,
    studentCount: 7000,
    ranking: 90,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'ABU',
    heroImage: seedImages.antalya,
    gallery: [seedImages.business, seedImages.arts, seedImages.antalya],
    languages: ['en', 'tr'],
    tagline: {
      en: 'Study where the world vacations',
      tr: 'Dünyanın tatil yaptığı yerde eğitim',
      az: 'Dünyanın tətil etdiyi yerdə təhsil',
      ru: 'Учиться там, где отдыхает мир',
    },
    description: {
      en: 'A private university in the Mediterranean city of Antalya, offering tourism, business and engineering programs with an international focus.',
      tr: 'Akdeniz şehri Antalya\'da turizm, işletme ve mühendislik programları sunan uluslararası odaklı bir vakıf üniversitesidir.',
      az: 'Axaravana şəhəri Antalyada turizm, biznes və mühəndislik proqramları təklif edən beynəlxalq yönümlü özəl universitetdir.',
      ru: 'Частный университет в средиземноморской Анталье с программами по туризму, бизнесу и инженерии и международной направленностью.',
    },
  },
  {
    id: 'u-konya',
    name: 'Konya Food and Agriculture University',
    slug: 'konya-food-and-agriculture-university',
    cityId: 'c-konya',
    foundedYear: 2013,
    studentCount: 5000,
    ranking: 110,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'KTAÜ',
    heroImage: seedImages.konya,
    gallery: [seedImages.campusBuilding, seedImages.arts, seedImages.konya],
    languages: ['tr', 'en'],
    tagline: {
      en: 'Specialised in food, agriculture and bioscience',
      tr: 'Gıda, tarım ve biyobilimde uzman',
      az: 'Qida, kənd təsərrüfatı və biotexnologiyada ixtisaslaşmış',
      ru: 'Специализация на пищевых технологиях, сельском хозяйстве и бионауках',
    },
    description: {
      en: 'A niche private university in Konya dedicated to food science, agriculture and bioscience, with industry-aligned research.',
      tr: 'Konya\'da gıda bilimi, tarım ve biyobilime adanmış, sanayi odaklı araştırma yapan niş bir vakıf üniversitesidir.',
      az: 'Konyada qida elmi, kənd təsərrüfatı və biotexnologiyaya həsr olunmuş, sənaye yönümlü tədqiqatlar aparan xüsusi özəl universitetdir.',
      ru: 'Нишевый частный университет в Конье, посвящённый пищевым наукам, сельскому хозяйству и бионауке с исследованиями, ориентированными на промышленность.',
    },
  },
  {
    id: 'u-ytu',
    name: 'Yıldız Technical University',
    slug: 'yildiz-technical-university',
    cityId: 'c-istanbul',
    foundedYear: 1911,
    studentCount: 36000,
    ranking: 20,
    accreditation: 'YÖK Accredited',
    isState: true,
    logoText: 'YTÜ',
    heroImage: seedImages.architecture,
    gallery: [seedImages.architecture, seedImages.engineering, seedImages.istanbul],
    languages: ['tr', 'en'],
    tagline: {
      en: 'Design and engineering on the European shore',
      tr: 'Avrupa yakasında tasarım ve mühendislik',
      az: 'Avropa sahilində dizayn və mühəndislik',
      ru: 'Дизайн и инженерия на европейском берегу',
    },
    description: {
      en: 'A prominent public technical university in Istanbul, strong in architecture, design, engineering and the sciences.',
      tr: "İstanbul'da mimarlık, tasarım, mühendislik ve fen alanlarında güçlü öne çıkan bir devlet teknik üniversitesidir.",
      az: 'İstanbulda memarlıq, dizayn, mühəndislik və elm sahələrində güclü tanınmış dövlət texniki universitetidir.',
      ru: 'Известный государственный технический университет в Стамбуле, сильный в архитектуре, дизайне, инженерии и науках.',
    },
  },

  {
    id: 'u-istanbul-medipol',
    name: 'Istanbul Medipol University',
    slug: 'istanbul-medipol-university',
    cityId: 'c-istanbul',
    foundedYear: 2009,
    studentCount: 46488,
    ranking: 55,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'IMU',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Medipol University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Medipol University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Medipol University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Medipol University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-topkapi',
    name: 'Istanbul Topkapi University',
    slug: 'istanbul-topkapi-university',
    cityId: 'c-istanbul',
    foundedYear: 2009,
    studentCount: 20000,
    ranking: 70,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'TOP',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Topkapi University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Topkapi University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Topkapi University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Topkapi University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-halic',
    name: 'Haliç University',
    slug: 'halic-university',
    cityId: 'c-istanbul',
    foundedYear: 1998,
    studentCount: 17000,
    ranking: 95,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'HÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Haliç University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Haliç University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Haliç University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Haliç University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-yeni-yuzyil',
    name: 'Istanbul Yeni Yuzyil University',
    slug: 'istanbul-yeni-yuzyil-university',
    cityId: 'c-istanbul',
    foundedYear: 2009,
    studentCount: 18347,
    ranking: 100,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'YYÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Yeni Yuzyil University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Yeni Yuzyil University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Yeni Yuzyil University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Yeni Yuzyil University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-esenyurt',
    name: 'Istanbul Esenyurt University',
    slug: 'istanbul-esenyurt-university',
    cityId: 'c-istanbul',
    foundedYear: 2013,
    studentCount: 15500,
    ranking: 120,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'IEÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Esenyurt University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Esenyurt University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Esenyurt University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Esenyurt University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-nisantasi',
    name: 'Istanbul Nisantasi University',
    slug: 'istanbul-nisantasi-university',
    cityId: 'c-istanbul',
    foundedYear: 2010,
    studentCount: 15000,
    ranking: 110,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'NÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Nisantasi University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Nisantasi University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Nisantasi University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Nisantasi University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-uskudar',
    name: 'Uskudar University',
    slug: 'uskudar-university',
    cityId: 'c-istanbul',
    foundedYear: 2011,
    studentCount: 24000,
    ranking: 90,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'ÜÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Uskudar University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Uskudar University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Uskudar University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Uskudar University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-biruni',
    name: 'Biruni University',
    slug: 'biruni-university',
    cityId: 'c-istanbul',
    foundedYear: 2014,
    studentCount: 12562,
    ranking: 85,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'BÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Biruni University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Biruni University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Biruni University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Biruni University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-altinbas',
    name: 'Altinbas University',
    slug: 'altinbas-university',
    cityId: 'c-istanbul',
    foundedYear: 2008,
    studentCount: 13800,
    ranking: 80,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'AÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Altinbas University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Altinbas University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Altinbas University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Altinbas University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istinye',
    name: 'Istinye University',
    slug: 'istinye-university',
    cityId: 'c-istanbul',
    foundedYear: 2015,
    studentCount: 14744,
    ranking: 88,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'İÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istinye University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istinye University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istinye University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istinye University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-gelisim',
    name: 'Istanbul Gelisim University',
    slug: 'istanbul-gelisim-university',
    cityId: 'c-istanbul',
    foundedYear: 2008,
    studentCount: 39052,
    ranking: 75,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'IGÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Gelisim University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Gelisim University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Gelisim University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Gelisim University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-aydin',
    name: 'Istanbul Aydin University',
    slug: 'istanbul-aydin-university',
    cityId: 'c-istanbul',
    foundedYear: 2007,
    studentCount: 50000,
    ranking: 78,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'İAÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Aydin University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Aydin University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Aydin University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Aydin University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-gedik',
    name: 'Istanbul Gedik University',
    slug: 'istanbul-gedik-university',
    cityId: 'c-istanbul',
    foundedYear: 2010,
    studentCount: 6254,
    ranking: 130,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'GÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Gedik University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Gedik University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Gedik University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Gedik University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-sabanci',
    name: 'Sabancı University',
    slug: 'sabanci-university',
    cityId: 'c-istanbul',
    foundedYear: 1994,
    studentCount: 5168,
    ranking: 35,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'SU',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Sabancı University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Sabancı University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Sabancı University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Sabancı University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-koc',
    name: 'Koç University',
    slug: 'koc-university',
    cityId: 'c-istanbul',
    foundedYear: 1993,
    studentCount: 9419,
    ranking: 32,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'KU',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Koç University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Koç University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Koç University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Koç University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-atasehir-adiguzel-vocational-school',
    name: 'Atasehir Adiguzel Vocational School',
    slug: 'atasehir-adiguzel-vocational-school',
    cityId: 'c-istanbul',
    foundedYear: 2013,
    studentCount: 940,
    ranking: 160,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'AAS',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Atasehir Adiguzel Vocational School is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Atasehir Adiguzel Vocational School, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Atasehir Adiguzel Vocational School İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Atasehir Adiguzel Vocational School — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-mef',
    name: 'MEF University',
    slug: 'mef-university',
    cityId: 'c-istanbul',
    foundedYear: 2012,
    studentCount: 4050,
    ranking: 105,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'MEF',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'MEF University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'MEF University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'MEF University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'MEF University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-health-and-technology',
    name: 'Istanbul Health and Technology University',
    slug: 'istanbul-health-and-technology-university',
    cityId: 'c-istanbul',
    foundedYear: 2018,
    studentCount: 2293,
    ranking: 140,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'SHT',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Health and Technology University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Health and Technology University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Health and Technology University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Health and Technology University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-29-mayis',
    name: 'Istanbul 29 Mayis University',
    slug: 'istanbul-29-mayis-university',
    cityId: 'c-istanbul',
    foundedYear: 2010,
    studentCount: 4405,
    ranking: 150,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'YMÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul 29 Mayis University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul 29 Mayis University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul 29 Mayis University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul 29 Mayis University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-sisli-vocational-school',
    name: 'Istanbul Şişli Vocational School',
    slug: 'istanbul-sisli-vocational-school',
    cityId: 'c-istanbul',
    foundedYear: 2012,
    studentCount: 12000,
    ranking: 165,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'ŞVS',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Şişli Vocational School is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Şişli Vocational School, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Şişli Vocational School İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Şişli Vocational School — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-vocational-school-of-health-and-social-sciences',
    name: 'Istanbul Vocational School of Health and Social Sciences',
    slug: 'istanbul-vocational-school-of-health-and-social-sciences',
    cityId: 'c-istanbul',
    foundedYear: 2010,
    studentCount: 1126,
    ranking: 170,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'VSS',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Vocational School of Health and Social Sciences is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Vocational School of Health and Social Sciences, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Vocational School of Health and Social Sciences İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Vocational School of Health and Social Sciences — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-demiroglu-bilim',
    name: 'Demiroğlu Bilim University',
    slug: 'demiroglu-bilim-university',
    cityId: 'c-istanbul',
    foundedYear: 2006,
    studentCount: 2700,
    ranking: 145,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'DBÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Demiroğlu Bilim University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Demiroğlu Bilim University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Demiroğlu Bilim University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Demiroğlu Bilim University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-maltepe',
    name: 'Maltepe University',
    slug: 'maltepe-university',
    cityId: 'c-istanbul',
    foundedYear: 1997,
    studentCount: 11452,
    ranking: 115,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'MÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Maltepe University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Maltepe University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Maltepe University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Maltepe University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-galata',
    name: 'Istanbul Galata University',
    slug: 'istanbul-galata-university',
    cityId: 'c-istanbul',
    foundedYear: 2019,
    studentCount: 2500,
    ranking: 155,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'GAL',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Galata University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Galata University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Galata University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Galata University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-ibn-haldun',
    name: 'Ibn Haldun University',
    slug: 'ibn-haldun-university',
    cityId: 'c-istanbul',
    foundedYear: 2015,
    studentCount: 1668,
    ranking: 135,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'İHÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Ibn Haldun University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Ibn Haldun University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Ibn Haldun University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Ibn Haldun University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-kadir-has',
    name: 'Kadir Has University',
    slug: 'kadir-has-university',
    cityId: 'c-istanbul',
    foundedYear: 1997,
    studentCount: 5000,
    ranking: 96,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'KHAS',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Kadir Has University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Kadir Has University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Kadir Has University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Kadir Has University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-okan',
    name: 'Istanbul Okan University',
    slug: 'istanbul-okan-university',
    cityId: 'c-istanbul',
    foundedYear: 1999,
    studentCount: 17000,
    ranking: 102,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'OÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Okan University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Okan University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Okan University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Okan University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-isik',
    name: 'Işık University',
    slug: 'isik-university',
    cityId: 'c-istanbul',
    foundedYear: 1996,
    studentCount: 7000,
    ranking: 125,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'IŞ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Işık University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Işık University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Işık University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Işık University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-yeditepe',
    name: 'Yeditepe University',
    slug: 'yeditepe-university',
    cityId: 'c-istanbul',
    foundedYear: 1996,
    studentCount: 17879,
    ranking: 92,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'YED',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Yeditepe University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Yeditepe University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Yeditepe University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Yeditepe University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-fatih-sultan-mehmet',
    name: 'Fatih Sultan Mehmet University',
    slug: 'fatih-sultan-mehmet-university',
    cityId: 'c-istanbul',
    foundedYear: 2010,
    studentCount: 7000,
    ranking: 108,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'FSM',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Fatih Sultan Mehmet University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Fatih Sultan Mehmet University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Fatih Sultan Mehmet University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Fatih Sultan Mehmet University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-arel',
    name: 'Istanbul Arel University',
    slug: 'istanbul-arel-university',
    cityId: 'c-istanbul',
    foundedYear: 2007,
    studentCount: 15000,
    ranking: 118,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'ARL',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Arel University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Arel University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Arel University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Arel University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-atlas',
    name: 'Istanbul Atlas University',
    slug: 'istanbul-atlas-university',
    cityId: 'c-istanbul',
    foundedYear: 2018,
    studentCount: 8524,
    ranking: 128,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'ATL',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Atlas University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Atlas University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Atlas University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Atlas University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-sabahattin-zaim',
    name: 'Istanbul Sabahattin Zaim University',
    slug: 'istanbul-sabahattin-zaim-university',
    cityId: 'c-istanbul',
    foundedYear: 2010,
    studentCount: 8690,
    ranking: 138,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'SAZ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Sabahattin Zaim University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Sabahattin Zaim University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Sabahattin Zaim University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Sabahattin Zaim University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-bezmi-alem',
    name: 'Bezm-i Âlem University',
    slug: 'bezmi-alem-university',
    cityId: 'c-istanbul',
    foundedYear: 2010,
    studentCount: 3486,
    ranking: 122,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'BAÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Bezm-i Âlem University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Bezm-i Âlem University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Bezm-i Âlem University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Bezm-i Âlem University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-beykent',
    name: 'Istanbul Beykent University',
    slug: 'istanbul-beykent-university',
    cityId: 'c-istanbul',
    foundedYear: 1997,
    studentCount: 30000,
    ranking: 112,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'BKÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Beykent University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Beykent University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Beykent University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Beykent University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-kultur',
    name: 'Istanbul Kultur University',
    slug: 'istanbul-kultur-university',
    cityId: 'c-istanbul',
    foundedYear: 1997,
    studentCount: 15116,
    ranking: 107,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'IKÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Kultur University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Kultur University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Kultur University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Kultur University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-commerce',
    name: 'Istanbul Commerce University',
    slug: 'istanbul-commerce-university',
    cityId: 'c-istanbul',
    foundedYear: 2001,
    studentCount: 9600,
    ranking: 132,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'TİC',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Commerce University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Commerce University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Commerce University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Commerce University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-beykoz',
    name: 'Beykoz University',
    slug: 'beykoz-university',
    cityId: 'c-istanbul',
    foundedYear: 2016,
    studentCount: 5865,
    ranking: 148,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'BZÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Beykoz University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Beykoz University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Beykoz University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Beykoz University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-ozyegin',
    name: 'Özyeğin University',
    slug: 'ozyegin-university',
    cityId: 'c-istanbul',
    foundedYear: 2007,
    studentCount: 7967,
    ranking: 60,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'ÖÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Özyeğin University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Özyeğin University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Özyeğin University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Özyeğin University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-dogus',
    name: 'Dogus University',
    slug: 'dogus-university',
    cityId: 'c-istanbul',
    foundedYear: 1997,
    studentCount: 11800,
    ranking: 142,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'DÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Dogus University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Dogus University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Dogus University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Dogus University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-rumeli',
    name: 'Istanbul Rumeli University',
    slug: 'istanbul-rumeli-university',
    cityId: 'c-istanbul',
    foundedYear: 2015,
    studentCount: 6700,
    ranking: 158,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'RUM',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Rumeli University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Rumeli University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Rumeli University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Rumeli University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-istanbul-kent',
    name: 'Istanbul Kent University',
    slug: 'istanbul-kent-university',
    cityId: 'c-istanbul',
    foundedYear: 2016,
    studentCount: 6443,
    ranking: 152,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'KÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Istanbul Kent University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Istanbul Kent University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Istanbul Kent University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Istanbul Kent University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-fenerbahce',
    name: 'Fenerbahçe University',
    slug: 'fenerbahce-university',
    cityId: 'c-istanbul',
    foundedYear: 2016,
    studentCount: 8000,
    ranking: 162,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'FBÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Fenerbahçe University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Fenerbahçe University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Fenerbahçe University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Fenerbahçe University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-acibadem-mehmet-ali-aydinlar',
    name: 'Acıbadem Mehmet Ali Aydınlar University',
    slug: 'acibadem-mehmet-ali-aydinlar-university',
    cityId: 'c-istanbul',
    foundedYear: 2007,
    studentCount: 5134,
    ranking: 99,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'ACB',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Acıbadem Mehmet Ali Aydınlar University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Acıbadem Mehmet Ali Aydınlar University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Acıbadem Mehmet Ali Aydınlar University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Acıbadem Mehmet Ali Aydınlar University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-piri-reis',
    name: 'Piri Reis University',
    slug: 'piri-reis-university',
    cityId: 'c-istanbul',
    foundedYear: 2008,
    studentCount: 6827,
    ranking: 168,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'PRÜ',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Istanbul',
      tr: 'İstanbul\'da özel üniversite',
      az: 'İstanbulda özəl universitet',
      ru: 'Частный университет в Стамбуле',
    },
    description: {
      en: 'Piri Reis University is a private university in Istanbul, Turkey, offering programs in various fields.',
      tr: 'Piri Reis University, İstanbul\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Piri Reis University İstanbulda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Piri Reis University — частный университет в Стамбуле, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-ankara-medipol',
    name: 'Ankara Medipol University',
    slug: 'ankara-medipol-university',
    cityId: 'c-ankara',
    foundedYear: 2018,
    studentCount: 12000,
    ranking: 113,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'AMÜ',
    heroImage: seedImages.ankara,
    gallery: [seedImages.campusBuilding, seedImages.business, seedImages.ankara],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Ankara',
      tr: 'Ankara\'da özel üniversite',
      az: 'Ankarada özəl universitet',
      ru: 'Частный университет в Анкаре',
    },
    description: {
      en: 'Ankara Medipol University is a private university in Ankara, Turkey, offering programs in various fields.',
      tr: 'Ankara Medipol University, Ankara\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Ankara Medipol University Ankarada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Ankara Medipol University — частный университет в Анкаре, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-turkish-aeronautical-association',
    name: 'Turkish Aeronautical Association University',
    slug: 'turkish-aeronautical-association-university',
    cityId: 'c-ankara',
    foundedYear: 2011,
    studentCount: 3379,
    ranking: 126,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'THK',
    heroImage: seedImages.ankara,
    gallery: [seedImages.campusBuilding, seedImages.business, seedImages.ankara],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Ankara',
      tr: 'Ankara\'da özel üniversite',
      az: 'Ankarada özəl universitet',
      ru: 'Частный университет в Анкаре',
    },
    description: {
      en: 'Turkish Aeronautical Association University is a private university in Ankara, Turkey, offering programs in various fields.',
      tr: 'Turkish Aeronautical Association University, Ankara\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Turkish Aeronautical Association University Ankarada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Turkish Aeronautical Association University — частный университет в Анкаре, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-ufuk',
    name: 'Ufuk University',
    slug: 'ufuk-university',
    cityId: 'c-ankara',
    foundedYear: 1999,
    studentCount: 4500,
    ranking: 136,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'UÜ',
    heroImage: seedImages.ankara,
    gallery: [seedImages.campusBuilding, seedImages.business, seedImages.ankara],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Ankara',
      tr: 'Ankara\'da özel üniversite',
      az: 'Ankarada özəl universitet',
      ru: 'Частный университет в Анкаре',
    },
    description: {
      en: 'Ufuk University is a private university in Ankara, Turkey, offering programs in various fields.',
      tr: 'Ufuk University, Ankara\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Ufuk University Ankarada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Ufuk University — частный университет в Анкаре, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-cankaya',
    name: 'Çankaya University',
    slug: 'cankaya-university',
    cityId: 'c-ankara',
    foundedYear: 1997,
    studentCount: 7786,
    ranking: 98,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'ÇÜ',
    heroImage: seedImages.ankara,
    gallery: [seedImages.campusBuilding, seedImages.business, seedImages.ankara],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Ankara',
      tr: 'Ankara\'da özel üniversite',
      az: 'Ankarada özəl universitet',
      ru: 'Частный университет в Анкаре',
    },
    description: {
      en: 'Çankaya University is a private university in Ankara, Turkey, offering programs in various fields.',
      tr: 'Çankaya University, Ankara\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Çankaya University Ankarada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Çankaya University — частный университет в Анкаре, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-yuksek-ihtisas',
    name: 'Yuksek Ihtisas University',
    slug: 'yuksek-ihtisas-university',
    cityId: 'c-ankara',
    foundedYear: 2013,
    studentCount: 2317,
    ranking: 156,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'YİÜ',
    heroImage: seedImages.ankara,
    gallery: [seedImages.campusBuilding, seedImages.business, seedImages.ankara],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Ankara',
      tr: 'Ankara\'da özel üniversite',
      az: 'Ankarada özəl universitet',
      ru: 'Частный университет в Анкаре',
    },
    description: {
      en: 'Yuksek Ihtisas University is a private university in Ankara, Turkey, offering programs in various fields.',
      tr: 'Yuksek Ihtisas University, Ankara\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Yuksek Ihtisas University Ankarada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Yuksek Ihtisas University — частный университет в Анкаре, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-lokman-hekim',
    name: 'Lokman Hekim University',
    slug: 'lokman-hekim-university',
    cityId: 'c-ankara',
    foundedYear: 2017,
    studentCount: 4698,
    ranking: 149,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'LHÜ',
    heroImage: seedImages.ankara,
    gallery: [seedImages.campusBuilding, seedImages.business, seedImages.ankara],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Ankara',
      tr: 'Ankara\'da özel üniversite',
      az: 'Ankarada özəl universitet',
      ru: 'Частный университет в Анкаре',
    },
    description: {
      en: 'Lokman Hekim University is a private university in Ankara, Turkey, offering programs in various fields.',
      tr: 'Lokman Hekim University, Ankara\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Lokman Hekim University Ankarada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Lokman Hekim University — частный университет в Анкаре, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-tobb-university-of-economics-and-technology',
    name: 'TOBB University of Economics and Technology',
    slug: 'tobb-university-of-economics-and-technology',
    cityId: 'c-ankara',
    foundedYear: 2003,
    studentCount: 6000,
    ranking: 58,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'TOBB',
    heroImage: seedImages.ankara,
    gallery: [seedImages.campusBuilding, seedImages.business, seedImages.ankara],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Ankara',
      tr: 'Ankara\'da özel üniversite',
      az: 'Ankarada özəl universitet',
      ru: 'Частный университет в Анкаре',
    },
    description: {
      en: 'TOBB University of Economics and Technology is a private university in Ankara, Turkey, offering programs in various fields.',
      tr: 'TOBB University of Economics and Technology, Ankara\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'TOBB University of Economics and Technology Ankarada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'TOBB University of Economics and Technology — частный университет в Анкаре, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-bilkent',
    name: 'Bilkent University',
    slug: 'bilkent-university',
    cityId: 'c-ankara',
    foundedYear: 1986,
    studentCount: 13000,
    ranking: 36,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'BLK',
    heroImage: seedImages.ankara,
    gallery: [seedImages.campusBuilding, seedImages.business, seedImages.ankara],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Ankara',
      tr: 'Ankara\'da özel üniversite',
      az: 'Ankarada özəl universitet',
      ru: 'Частный университет в Анкаре',
    },
    description: {
      en: 'Bilkent University is a private university in Ankara, Turkey, offering programs in various fields.',
      tr: 'Bilkent University, Ankara\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Bilkent University Ankarada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Bilkent University — частный университет в Анкаре, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-ostim-technical',
    name: 'OSTIM Technical University',
    slug: 'ostim-technical-university',
    cityId: 'c-ankara',
    foundedYear: 2017,
    studentCount: 8270,
    ranking: 164,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'OTÜ',
    heroImage: seedImages.ankara,
    gallery: [seedImages.campusBuilding, seedImages.business, seedImages.ankara],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Ankara',
      tr: 'Ankara\'da özel üniversite',
      az: 'Ankarada özəl universitet',
      ru: 'Частный университет в Анкаре',
    },
    description: {
      en: 'OSTIM Technical University is a private university in Ankara, Turkey, offering programs in various fields.',
      tr: 'OSTIM Technical University, Ankara\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'OSTIM Technical University Ankarada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'OSTIM Technical University — частный университет в Анкаре, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-ted',
    name: 'TED University',
    slug: 'ted-university',
    cityId: 'c-ankara',
    foundedYear: 2009,
    studentCount: 5367,
    ranking: 119,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'TED',
    heroImage: seedImages.ankara,
    gallery: [seedImages.campusBuilding, seedImages.business, seedImages.ankara],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Ankara',
      tr: 'Ankara\'da özel üniversite',
      az: 'Ankarada özəl universitet',
      ru: 'Частный университет в Анкаре',
    },
    description: {
      en: 'TED University is a private university in Ankara, Turkey, offering programs in various fields.',
      tr: 'TED University, Ankara\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'TED University Ankarada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'TED University — частный университет в Анкаре, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-baskent',
    name: 'Baskent University',
    slug: 'baskent-university',
    cityId: 'c-ankara',
    foundedYear: 1994,
    studentCount: 19500,
    ranking: 93,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'BAŞ',
    heroImage: seedImages.ankara,
    gallery: [seedImages.campusBuilding, seedImages.business, seedImages.ankara],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Ankara',
      tr: 'Ankara\'da özel üniversite',
      az: 'Ankarada özəl universitet',
      ru: 'Частный университет в Анкаре',
    },
    description: {
      en: 'Baskent University is a private university in Ankara, Turkey, offering programs in various fields.',
      tr: 'Baskent University, Ankara\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Baskent University Ankarada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Baskent University — частный университет в Анкаре, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-atilim',
    name: 'Atilim University',
    slug: 'atilim-university',
    cityId: 'c-ankara',
    foundedYear: 1996,
    studentCount: 10000,
    ranking: 127,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'ATÜ',
    heroImage: seedImages.ankara,
    gallery: [seedImages.campusBuilding, seedImages.business, seedImages.ankara],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Ankara',
      tr: 'Ankara\'da özel üniversite',
      az: 'Ankarada özəl universitet',
      ru: 'Частный университет в Анкаре',
    },
    description: {
      en: 'Atilim University is a private university in Ankara, Turkey, offering programs in various fields.',
      tr: 'Atilim University, Ankara\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Atilim University Ankarada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Atilim University — частный университет в Анкаре, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-ankara-bilim',
    name: 'Ankara Bilim University',
    slug: 'ankara-bilim-university',
    cityId: 'c-ankara',
    foundedYear: 2016,
    studentCount: 1364,
    ranking: 166,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'ANKB',
    heroImage: seedImages.ankara,
    gallery: [seedImages.campusBuilding, seedImages.business, seedImages.ankara],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Ankara',
      tr: 'Ankara\'da özel üniversite',
      az: 'Ankarada özəl universitet',
      ru: 'Частный университет в Анкаре',
    },
    description: {
      en: 'Ankara Bilim University is a private university in Ankara, Turkey, offering programs in various fields.',
      tr: 'Ankara Bilim University, Ankara\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Ankara Bilim University Ankarada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Ankara Bilim University — частный университет в Анкаре, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-izmir-tinaztepe',
    name: 'Izmir Tınaztepe University',
    slug: 'izmir-tinaztepe-university',
    cityId: 'c-izmir',
    foundedYear: 2018,
    studentCount: 3103,
    ranking: 137,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'TZÜ',
    heroImage: seedImages.izmir,
    gallery: [seedImages.business, seedImages.campusLibrary, seedImages.izmir],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Izmir',
      tr: 'İzmir\'de özel üniversite',
      az: 'İzmirde özəl universitet',
      ru: 'Частный университет в Измире',
    },
    description: {
      en: 'Izmir Tınaztepe University is a private university in Izmir, Turkey, offering programs in various fields.',
      tr: 'Izmir Tınaztepe University, İzmir\'de çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Izmir Tınaztepe University İzmirde müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Izmir Tınaztepe University — частный университет в Измире, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-izmir-kavram-vocational-school',
    name: 'İzmir Kavram Vocational School',
    slug: 'izmir-kavram-vocational-school',
    cityId: 'c-izmir',
    foundedYear: 2008,
    studentCount: 3300,
    ranking: 169,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'KVS',
    heroImage: seedImages.izmir,
    gallery: [seedImages.business, seedImages.campusLibrary, seedImages.izmir],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Izmir',
      tr: 'İzmir\'de özel üniversite',
      az: 'İzmirde özəl universitet',
      ru: 'Частный университет в Измире',
    },
    description: {
      en: 'İzmir Kavram Vocational School is a private university in Izmir, Turkey, offering programs in various fields.',
      tr: 'İzmir Kavram Vocational School, İzmir\'de çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'İzmir Kavram Vocational School İzmirde müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'İzmir Kavram Vocational School — частный университет в Измире, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-yasar',
    name: 'Yaşar University',
    slug: 'yasar-university',
    cityId: 'c-izmir',
    foundedYear: 2001,
    studentCount: 9765,
    ranking: 72,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'YÜ',
    heroImage: seedImages.izmir,
    gallery: [seedImages.business, seedImages.campusLibrary, seedImages.izmir],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Izmir',
      tr: 'İzmir\'de özel üniversite',
      az: 'İzmirde özəl universitet',
      ru: 'Частный университет в Измире',
    },
    description: {
      en: 'Yaşar University is a private university in Izmir, Turkey, offering programs in various fields.',
      tr: 'Yaşar University, İzmir\'de çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Yaşar University İzmirde müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Yaşar University — частный университет в Измире, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-antalya-belek',
    name: 'Antalya Belek University',
    slug: 'antalya-belek-university',
    cityId: 'c-antalya',
    foundedYear: 2015,
    studentCount: 1700,
    ranking: 151,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'ABL',
    heroImage: seedImages.antalya,
    gallery: [seedImages.business, seedImages.arts, seedImages.antalya],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Antalya',
      tr: 'Antalya\'da özel üniversite',
      az: 'Antalyada özəl universitet',
      ru: 'Частный университет в Анталье',
    },
    description: {
      en: 'Antalya Belek University is a private university in Antalya, Turkey, offering programs in various fields.',
      tr: 'Antalya Belek University, Antalya\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Antalya Belek University Antalyada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Antalya Belek University — частный университет в Анталье, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-alanya',
    name: 'Alanya University',
    slug: 'alanya-university',
    cityId: 'c-alanya',
    foundedYear: 2015,
    studentCount: 14135,
    ranking: 124,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'AU',
    heroImage: seedImages.antalya,
    gallery: [seedImages.arts, seedImages.antalya, seedImages.students],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Alanya',
      tr: 'Alanya\'da özel üniversite',
      az: 'Alanyada özəl universitet',
      ru: 'Частный университет в Аланье',
    },
    description: {
      en: 'Alanya University is a private university in Alanya, Turkey, offering programs in various fields.',
      tr: 'Alanya University, Alanya\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Alanya University Alanyada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Alanya University — частный университет в Аланье, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-kto-karatay',
    name: 'KTO Karatay University',
    slug: 'kto-karatay-university',
    cityId: 'c-konya',
    foundedYear: 2009,
    studentCount: 9115,
    ranking: 134,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'KTO',
    heroImage: seedImages.konya,
    gallery: [seedImages.campusBuilding, seedImages.arts, seedImages.konya],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Konya',
      tr: 'Konya\'da özel üniversite',
      az: 'Konyada özəl universitet',
      ru: 'Частный университет в Конье',
    },
    description: {
      en: 'KTO Karatay University is a private university in Konya, Turkey, offering programs in various fields.',
      tr: 'KTO Karatay University, Konya\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'KTO Karatay University Konyada müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'KTO Karatay University — частный университет в Конье, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-avrasya',
    name: 'Avrasya University',
    slug: 'avrasya-university',
    cityId: 'c-trabzon',
    foundedYear: 2010,
    studentCount: 6435,
    ranking: 159,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'AVR',
    heroImage: seedImages.campusBuilding,
    gallery: [seedImages.campusBuilding, seedImages.engineering, seedImages.students],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Trabzon',
      tr: 'Trabzon\'da özel üniversite',
      az: 'Trabzonda özəl universitet',
      ru: 'Частный университет в Трабзоне',
    },
    description: {
      en: 'Avrasya University is a private university in Trabzon, Turkey, offering programs in various fields.',
      tr: 'Avrasya University, Trabzon\'da çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Avrasya University Trabzonda müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Avrasya University — частный университет в Трабзоне, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-toros',
    name: 'Toros University',
    slug: 'toros-university',
    cityId: 'c-mersin',
    foundedYear: 2009,
    studentCount: 4000,
    ranking: 167,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'TÜ',
    heroImage: seedImages.campusBuilding,
    gallery: [seedImages.business, seedImages.campusBuilding, seedImages.students],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Mersin',
      tr: 'Mersin\'de özel üniversite',
      az: 'Mersində özəl universitet',
      ru: 'Частный университет в Мерсине',
    },
    description: {
      en: 'Toros University is a private university in Mersin, Turkey, offering programs in various fields.',
      tr: 'Toros University, Mersin\'de çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Toros University Mersində müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Toros University — частный университет в Мерсине, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-cag',
    name: 'Çağ University',
    slug: 'cag-university',
    cityId: 'c-mersin',
    foundedYear: 1997,
    studentCount: 7000,
    ranking: 171,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'ÇAĞ',
    heroImage: seedImages.campusBuilding,
    gallery: [seedImages.business, seedImages.campusBuilding, seedImages.students],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Mersin',
      tr: 'Mersin\'de özel üniversite',
      az: 'Mersində özəl universitet',
      ru: 'Частный университет в Мерсине',
    },
    description: {
      en: 'Çağ University is a private university in Mersin, Turkey, offering programs in various fields.',
      tr: 'Çağ University, Mersin\'de çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Çağ University Mersində müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Çağ University — частный университет в Мерсине, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-sanko',
    name: 'Sanko University',
    slug: 'sanko-university',
    cityId: 'c-gaziantep',
    foundedYear: 2013,
    studentCount: 1611,
    ranking: 161,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'SÜ',
    heroImage: seedImages.campusBuilding,
    gallery: [seedImages.engineering, seedImages.campusBuilding, seedImages.students],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Gaziantep',
      tr: 'Gaziantep\'te özel üniversite',
      az: 'Gaziantepdə özəl universitet',
      ru: 'Частный университет в Газиантепе',
    },
    description: {
      en: 'Sanko University is a private university in Gaziantep, Turkey, offering programs in various fields.',
      tr: 'Sanko University, Gaziantep\'te çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Sanko University Gaziantepdə müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Sanko University — частный университет в Газиантепе, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-hasan-kalyoncu',
    name: 'Hasan Kalyoncu University',
    slug: 'hasan-kalyoncu-university',
    cityId: 'c-gaziantep',
    foundedYear: 2008,
    studentCount: 7400,
    ranking: 147,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'HKÜ',
    heroImage: seedImages.campusBuilding,
    gallery: [seedImages.engineering, seedImages.campusBuilding, seedImages.students],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Gaziantep',
      tr: 'Gaziantep\'te özel üniversite',
      az: 'Gaziantepdə özəl universitet',
      ru: 'Частный университет в Газиантепе',
    },
    description: {
      en: 'Hasan Kalyoncu University is a private university in Gaziantep, Turkey, offering programs in various fields.',
      tr: 'Hasan Kalyoncu University, Gaziantep\'te çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Hasan Kalyoncu University Gaziantepdə müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Hasan Kalyoncu University — частный университет в Газиантепе, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-nuh-naci-yazgan',
    name: 'Nuh Naci Yazgan University',
    slug: 'nuh-naci-yazgan-university',
    cityId: 'c-kayseri',
    foundedYear: 2009,
    studentCount: 2844,
    ranking: 163,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'NNY',
    heroImage: seedImages.campusBuilding,
    gallery: [seedImages.business, seedImages.campusBuilding, seedImages.students],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Kayseri',
      tr: 'Kayseri\'de özel üniversite',
      az: 'Kayseridə özəl universitet',
      ru: 'Частный университет в Кайсери',
    },
    description: {
      en: 'Nuh Naci Yazgan University is a private university in Kayseri, Turkey, offering programs in various fields.',
      tr: 'Nuh Naci Yazgan University, Kayseri\'de çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Nuh Naci Yazgan University Kayseridə müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Nuh Naci Yazgan University — частный университет в Кайсери, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-cappadocia',
    name: 'Cappadocia University',
    slug: 'cappadocia-university',
    cityId: 'c-nevsehir',
    foundedYear: 2005,
    studentCount: 4400,
    ranking: 172,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'CAP',
    heroImage: seedImages.campusBuilding,
    gallery: [seedImages.arts, seedImages.campusBuilding, seedImages.students],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Nevsehir',
      tr: 'Nevşehir\'de özel üniversite',
      az: 'Nevşəhərdə özəl universitet',
      ru: 'Частный университет в Невшехире',
    },
    description: {
      en: 'Cappadocia University is a private university in Nevsehir, Turkey, offering programs in various fields.',
      tr: 'Cappadocia University, Nevşehir\'de çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Cappadocia University Nevşəhərdə müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Cappadocia University — частный университет в Невшехире, предлагающий программы в различных областях.',
    },
  },
  {
    id: 'u-kocaeli-university-of-health-and-technology',
    name: 'Kocaeli University of Health and Technology',
    slug: 'kocaeli-university-of-health-and-technology',
    cityId: 'c-kocaeli',
    foundedYear: 2020,
    studentCount: 4900,
    ranking: 173,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'KHT',
    heroImage: seedImages.campusBuilding,
    gallery: [seedImages.engineering, seedImages.campusBuilding, seedImages.students],
    languages: ['en', 'tr'],
    featured: false,
    tagline: {
      en: 'Private university in Kocaeli',
      tr: 'Kocaeli\'de özel üniversite',
      az: 'Kocaelidə özəl universitet',
      ru: 'Частный университет в Коджаэли',
    },
    description: {
      en: 'Kocaeli University of Health and Technology is a private university in Kocaeli, Turkey, offering programs in various fields.',
      tr: 'Kocaeli University of Health and Technology, Kocaeli\'de çeşitli alanlarda programlar sunan özel bir üniversitedir.',
      az: 'Kocaeli University of Health and Technology Kocaelidə müxtəlif sahələrdə proqramlar təklif edən özəl universitetdir.',
      ru: 'Kocaeli University of Health and Technology — частный университет в Коджаэли, предлагающий программы в различных областях.',
    },
  },
];
