import type { UniversityProgram } from "@/types";

/**
 * Links universities to programs with tuition fees.
 * Tuition in USD/year for comparability; TRY available for state programs.
 * Private-university figures reflect official 2025-2026 international tuition.
 */
export const seedUniversityPrograms: UniversityProgram[] = [
  // ─── Koç University (private, Istanbul) — intl.ku.edu.tr 2025/2026 ───
  {
    id: "up-koc-med",
    universityId: "u-koc",
    programId: "p-med-bach",
    language: "en",
    tuitionFee: 59000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-koc-cs",
    universityId: "u-koc",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 38000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-koc-bus",
    universityId: "u-koc",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 38000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-koc-econ",
    universityId: "u-koc",
    programId: "p-bus-economics",
    language: "en",
    tuitionFee: 38000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-koc-law",
    universityId: "u-koc",
    programId: "p-law-bach",
    language: "en",
    tuitionFee: 38000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-koc-nurs",
    universityId: "u-koc",
    programId: "p-health-nursing",
    language: "en",
    tuitionFee: 38000,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ─── Sabancı University (private, Istanbul) — uniform rate ───
  {
    id: "up-sabanci-cs",
    universityId: "u-sabanci",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 36500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-sabanci-bus",
    universityId: "u-sabanci",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 36500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-sabanci-econ",
    universityId: "u-sabanci",
    programId: "p-bus-economics",
    language: "en",
    tuitionFee: 36500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-sabanci-ind",
    universityId: "u-sabanci",
    programId: "p-eng-industrial",
    language: "en",
    tuitionFee: 36500,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ─── Bahçeşehir University (private, Istanbul) — int.bau.edu.tr ───
  {
    id: "up-1",
    universityId: "u-bahcesehir",
    programId: "p-med-bach",
    language: "en",
    tuitionFee: 28000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bau-dent",
    universityId: "u-bahcesehir",
    programId: "p-dent-bach",
    language: "en",
    tuitionFee: 24000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bau-pharm",
    universityId: "u-bahcesehir",
    programId: "p-health-pharmacy",
    language: "en",
    tuitionFee: 15000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-2",
    universityId: "u-bahcesehir",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 9000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-5",
    universityId: "u-bahcesehir",
    programId: "p-ai-master",
    language: "en",
    tuitionFee: 12000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bau-law",
    universityId: "u-bahcesehir",
    programId: "p-law-bach",
    language: "en",
    tuitionFee: 10000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-3",
    universityId: "u-bahcesehir",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 8500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-4",
    universityId: "u-bahcesehir",
    programId: "p-arch-bach",
    language: "en",
    tuitionFee: 8500,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ─── Yeditepe University (private, Istanbul) — yeditepe.edu.tr ───
  {
    id: "up-yeditepe-med",
    universityId: "u-yeditepe",
    programId: "p-med-bach",
    language: "en",
    tuitionFee: 45000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-yeditepe-dent",
    universityId: "u-yeditepe",
    programId: "p-dent-bach",
    language: "en",
    tuitionFee: 73000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-yeditepe-pharm",
    universityId: "u-yeditepe",
    programId: "p-health-pharmacy",
    language: "en",
    tuitionFee: 24000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-yeditepe-cs",
    universityId: "u-yeditepe",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 30000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-yeditepe-mech",
    universityId: "u-yeditepe",
    programId: "p-eng-mech",
    language: "en",
    tuitionFee: 20000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-yeditepe-arch",
    universityId: "u-yeditepe",
    programId: "p-arch-bach",
    language: "en",
    tuitionFee: 20000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-yeditepe-law",
    universityId: "u-yeditepe",
    programId: "p-law-bach",
    language: "en",
    tuitionFee: 20000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-yeditepe-nurs",
    universityId: "u-yeditepe",
    programId: "p-health-nursing",
    language: "en",
    tuitionFee: 20000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-yeditepe-bus",
    universityId: "u-yeditepe",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 18000,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ─── Özyeğin University (private, Istanbul) — uniform rate ───
  {
    id: "up-ozyegin-cs",
    universityId: "u-ozyegin",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 22000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ozyegin-bus",
    universityId: "u-ozyegin",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 22000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ozyegin-law",
    universityId: "u-ozyegin",
    programId: "p-law-bach",
    language: "en",
    tuitionFee: 22000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ozyegin-arch",
    universityId: "u-ozyegin",
    programId: "p-arch-bach",
    language: "en",
    tuitionFee: 22000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ozyegin-gastro",
    universityId: "u-ozyegin",
    programId: "p-tour-gastronomy",
    language: "en",
    tuitionFee: 22000,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ─── Kadir Has University (private, Istanbul) — uniform rate ───
  {
    id: "up-khas-cs",
    universityId: "u-kadir-has",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 20000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-khas-bus",
    universityId: "u-kadir-has",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 20000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-khas-law",
    universityId: "u-kadir-has",
    programId: "p-law-bach",
    language: "en",
    tuitionFee: 20000,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ─── Bilkent University (private, Ankara) — flat rate 2025/2026 ───
  {
    id: "up-bilkent-cs",
    universityId: "u-bilkent",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 17600,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bilkent-bus",
    universityId: "u-bilkent",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 17600,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bilkent-arch",
    universityId: "u-bilkent",
    programId: "p-arch-bach",
    language: "en",
    tuitionFee: 17600,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bilkent-law",
    universityId: "u-bilkent",
    programId: "p-law-bach",
    language: "en",
    tuitionFee: 17600,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-bilkent-econ",
    universityId: "u-bilkent",
    programId: "p-bus-economics",
    language: "en",
    tuitionFee: 17600,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ─── Izmir University of Economics (private, Izmir) — 2025/2026 ───
  {
    id: "up-21",
    universityId: "u-izmir-econ",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 12500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-22",
    universityId: "u-izmir-econ",
    programId: "p-arts-bach",
    language: "en",
    tuitionFee: 12500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-23",
    universityId: "u-izmir-econ",
    programId: "p-bus-mba",
    language: "en",
    tuitionFee: 12500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-izmir-med",
    universityId: "u-izmir-econ",
    programId: "p-med-bach",
    language: "en",
    tuitionFee: 23000,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ─── Antalya Bilim University (private, Antalya) — 2026 table ───
  {
    id: "up-27",
    universityId: "u-antalya-bilim",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 8300,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-28",
    universityId: "u-antalya-bilim",
    programId: "p-bus-irm",
    language: "en",
    tuitionFee: 8300,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-29",
    universityId: "u-antalya-bilim",
    programId: "p-arts-bach",
    language: "en",
    tuitionFee: 8300,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-antalya-dent",
    universityId: "u-antalya-bilim",
    programId: "p-dent-bach",
    language: "tr",
    tuitionFee: 14000,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ─── TOBB ETÜ (private, Ankara) — 2025/2026 ───
  {
    id: "up-tobb-bus",
    universityId: "u-tobb-university-of-economics-and-technology",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 16500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-tobb-cs",
    universityId: "u-tobb-university-of-economics-and-technology",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 16500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-tobb-arch",
    universityId: "u-tobb-university-of-economics-and-technology",
    programId: "p-arch-bach",
    language: "en",
    tuitionFee: 16500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-tobb-med",
    universityId: "u-tobb-university-of-economics-and-technology",
    programId: "p-med-bach",
    language: "en",
    tuitionFee: 23100,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ─── TED University (private, Ankara) — 2025/2026 ───
  {
    id: "up-ted-cs",
    universityId: "u-ted",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 9000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ted-bus",
    universityId: "u-ted",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 9000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-ted-arch",
    universityId: "u-ted",
    programId: "p-arch-bach",
    language: "en",
    tuitionFee: 9000,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ─── Başkent University (private, Ankara) — 2026/2027 official table ───
  {
    id: "up-baskent-med",
    universityId: "u-baskent",
    programId: "p-med-bach",
    language: "en",
    tuitionFee: 27000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-baskent-dent",
    universityId: "u-baskent",
    programId: "p-dent-bach",
    language: "en",
    tuitionFee: 23000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-baskent-pharm",
    universityId: "u-baskent",
    programId: "p-health-pharmacy",
    language: "en",
    tuitionFee: 16000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-baskent-cs",
    universityId: "u-baskent",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 10000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-baskent-arch",
    universityId: "u-baskent",
    programId: "p-arch-bach",
    language: "en",
    tuitionFee: 10000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-baskent-bus",
    universityId: "u-baskent",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 8000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-baskent-law",
    universityId: "u-baskent",
    programId: "p-law-bach",
    language: "en",
    tuitionFee: 9000,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ─── Atılım University (private, Ankara) — 2026/2027 official table ───
  {
    id: "up-atilim-cs",
    universityId: "u-atilim",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 14500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-atilim-bus",
    universityId: "u-atilim",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 14500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-atilim-arch",
    universityId: "u-atilim",
    programId: "p-arch-bach",
    language: "en",
    tuitionFee: 14500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-atilim-med",
    universityId: "u-atilim",
    programId: "p-med-bach",
    language: "en",
    tuitionFee: 27000,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ─── Yaşar University (private, Izmir) — flat rate ───
  {
    id: "up-yasar-bus",
    universityId: "u-yasar",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 8000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-yasar-cs",
    universityId: "u-yasar",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 8000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-yasar-arch",
    universityId: "u-yasar",
    programId: "p-arch-bach",
    language: "en",
    tuitionFee: 8000,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // ─── State universities (unchanged reference figures) ───
  // İTÜ (state, Istanbul)
  {
    id: "up-6",
    universityId: "u-itu",
    programId: "p-eng-mech",
    language: "tr",
    tuitionFee: 1200,
    currency: "USD",
    scholarshipAvailable: false,
  },
  {
    id: "up-7",
    universityId: "u-itu",
    programId: "p-eng-elec",
    language: "en",
    tuitionFee: 1400,
    currency: "USD",
    scholarshipAvailable: false,
  },
  {
    id: "up-8",
    universityId: "u-itu",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 1500,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-9",
    universityId: "u-itu",
    programId: "p-arch-bach",
    language: "tr",
    tuitionFee: 1200,
    currency: "USD",
    scholarshipAvailable: false,
  },

  // Boğaziçi (state, Istanbul, English)
  {
    id: "up-10",
    universityId: "u-bogazici",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: false,
  },
  {
    id: "up-11",
    universityId: "u-bogazici",
    programId: "p-bus-bach",
    language: "en",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: false,
  },
  {
    id: "up-12",
    universityId: "u-bogazici",
    programId: "p-bus-irm",
    language: "en",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: false,
  },
  {
    id: "up-13",
    universityId: "u-bogazici",
    programId: "p-cs-master",
    language: "en",
    tuitionFee: 1500,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // METU (state, Ankara, English)
  {
    id: "up-14",
    universityId: "u-metu",
    programId: "p-eng-elec",
    language: "en",
    tuitionFee: 1300,
    currency: "USD",
    scholarshipAvailable: false,
  },
  {
    id: "up-15",
    universityId: "u-metu",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 1300,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-16",
    universityId: "u-metu",
    programId: "p-arch-bach",
    language: "en",
    tuitionFee: 1300,
    currency: "USD",
    scholarshipAvailable: false,
  },
  {
    id: "up-17",
    universityId: "u-metu",
    programId: "p-ai-master",
    language: "en",
    tuitionFee: 1600,
    currency: "USD",
    scholarshipAvailable: true,
  },

  // Ankara University (state, Ankara)
  {
    id: "up-18",
    universityId: "u-ankara",
    programId: "p-law-bach",
    language: "tr",
    tuitionFee: 900,
    currency: "USD",
    scholarshipAvailable: false,
  },
  {
    id: "up-19",
    universityId: "u-ankara",
    programId: "p-med-bach",
    language: "tr",
    tuitionFee: 1100,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-20",
    universityId: "u-ankara",
    programId: "p-bus-irm",
    language: "en",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: false,
  },

  // Bursa Technical (state, Bursa)
  {
    id: "up-24",
    universityId: "u-btu",
    programId: "p-eng-civil",
    language: "tr",
    tuitionFee: 1100,
    currency: "USD",
    scholarshipAvailable: false,
  },
  {
    id: "up-25",
    universityId: "u-btu",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 1200,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-26",
    universityId: "u-btu",
    programId: "p-eng-elec",
    language: "tr",
    tuitionFee: 1100,
    currency: "USD",
    scholarshipAvailable: false,
  },

  // Yıldız Technical (state, Istanbul)
  {
    id: "up-32",
    universityId: "u-ytu",
    programId: "p-arch-bach",
    language: "tr",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: false,
  },
  {
    id: "up-33",
    universityId: "u-ytu",
    programId: "p-eng-mech",
    language: "tr",
    tuitionFee: 1000,
    currency: "USD",
    scholarshipAvailable: true,
  },
  {
    id: "up-34",
    universityId: "u-ytu",
    programId: "p-cs-bach",
    language: "en",
    tuitionFee: 1100,
    currency: "USD",
    scholarshipAvailable: false,
  },
];
