import type { University } from '@/types';
import { seedImages } from './images';

export const seedUniversities: University[] = [
  {
    id: 'u-bahcesehir',
    name: 'Bahçeşehir University',
    slug: 'bahcesehir-university',
    cityId: 'c-istanbul',
    foundedYear: 1998,
    studentCount: 30000,
    ranking: 45,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'BAU',
    heroImage: seedImages.istanbul,
    gallery: [seedImages.campusBuilding, seedImages.campusLibrary, seedImages.students],
    languages: ['en', 'tr'],
    featured: true,
    tagline: {
      en: 'A global university in the heart of Istanbul',
      tr: "İstanbul'un merkezinde küresel bir üniversite",
      az: 'İstanbulun mərkəzində qlobal universitet',
      ru: 'Глобальный университет в центре Стамбула',
    },
    description: {
      en: 'Bahçeşehir University is a leading private university with a strong international focus, offering English-taught programs and partnerships across the globe.',
      tr: 'Bahçeşehir Üniversitesi, güçlü uluslararası odaklı, İngilizce eğitim veren ve dünya çapında ortaklıklara sahip önde gelen bir vakıf üniversitesidir.',
      az: 'Bahçeşehir Universiteti güclü beynəlxalq yönümlü, ingilis dilində təhsil verən və dünya üzrə tərəfdaşlıqlara malik aparıcı özəl universitetdir.',
      ru: 'Бахчешеширский университет — ведущий частный университет с сильной международной направленностью, обучающий на английском языке и имеющий партнёров по всему миру.',
    },
  },
  {
    id: 'u-itu',
    name: 'Istanbul Technical University',
    slug: 'istanbul-technical-university',
    cityId: 'c-istanbul',
    foundedYear: 1773,
    studentCount: 42000,
    ranking: 8,
    accreditation: 'YÖK Accredited',
    isState: true,
    logoText: 'İTÜ',
    heroImage: seedImages.engineering,
    gallery: [seedImages.campusAerial, seedImages.engineering, seedImages.computer],
    languages: ['en', 'tr'],
    featured: true,
    tagline: {
      en: 'Engineering excellence since 1773',
      tr: '1773\'ten beri mühendislik mükemmelliği',
      az: '1773-cü ildən mühəndislik mükəmməlliyi',
      ru: 'Инженерное совершенство с 1773 года',
    },
    description: {
      en: 'One of the world\'s oldest technical universities, İTÜ is renowned for engineering, architecture and science programs taught in English and Turkish.',
      tr: 'Dünyanın en eski teknik üniversitelerinden biri olan İTÜ, İngilizce ve Türkçe eğitim veren mühendislik, mimarlık ve fen programlarıyla tanınır.',
      az: 'Dünyanın ən qədim texniki universitetlərindən biri olan İTÜ ingilis və türk dilində tədris olunan mühəndislik, memarlıq və elm proqramları ilə tanınır.',
      ru: 'Один из старейших технических университетов мира, ИТЮ славится инженерными, архитектурными и научными программами на английском и турецком языках.',
    },
  },
  {
    id: 'u-bogazici',
    name: 'Boğaziçi University',
    slug: 'bogazici-university',
    cityId: 'c-istanbul',
    foundedYear: 1863,
    studentCount: 16000,
    ranking: 3,
    accreditation: 'YÖK Accredited',
    isState: true,
    logoText: 'BU',
    heroImage: seedImages.campusLibrary,
    gallery: [seedImages.campusBuilding, seedImages.students, seedImages.istanbul],
    languages: ['en', 'tr'],
    featured: true,
    tagline: {
      en: 'Turkey\'s most prestigious English-medium university',
      tr: 'Türkiye\'nin en prestijli İngilizce eğitim üniversitesi',
      az: 'Türkiyənin ən nüfuzlu ingilis dilində təhsil universiteti',
      ru: 'Самый престижный англоязычный университет Турции',
    },
    description: {
      en: 'Boğaziçi University is a top-ranked public university overlooking the Bosphorus, offering fully English-taught programs across sciences and humanities.',
      tr: 'Boğaziçi Üniversitesi, Boğaz manzaralı, fen ve sosyal bilimlerde tamamen İngilizce eğitim veren en üst düzey devlet üniversitesidir.',
      az: 'Boğaziçi Universiteti Boğaz mənzərəli, elm və humanitar sahələrdə tamamilə ingilis dilində təhsil verən ən yüksək dəvlət universitetidir.',
      ru: 'Богазичи университет — ведущий государственный университет с видом на Босфор, обучающий полностью на английском языке.',
    },
  },
  {
    id: 'u-metu',
    name: 'Middle East Technical University',
    slug: 'middle-east-technical-university',
    cityId: 'c-ankara',
    foundedYear: 1956,
    studentCount: 28000,
    ranking: 5,
    accreditation: 'YÖK Accredited',
    isState: true,
    logoText: 'ODTÜ',
    heroImage: seedImages.campusAerial,
    gallery: [seedImages.engineering, seedImages.computer, seedImages.students],
    languages: ['en'],
    featured: true,
    tagline: {
      en: 'English-medium excellence in the capital',
      tr: 'Başkentte İngilizce eğitim mükemmelliği',
      az: 'Paytaxtda ingilis dilində təhsil mükəmməlliyi',
      ru: 'Англоязычное совершенство в столице',
    },
    description: {
      en: 'METU (ODTÜ) is a flagship public university in Ankara, fully English-medium, famous for engineering and natural sciences and its vast forested campus.',
      tr: 'ODTÜ, Ankara\'da tamamen İngilizce eğitim veren, mühendislik ve fen bilimleriyle ünlü geniş ormanlık kampüsüyle öne çıkan bir devlet üniversitesidir.',
      az: 'ODTÜ Ankarada tamamilə ingilis dilində təhsil verən, mühəndislik və təbiət elmləri ilə məşhur geniş meşəlik kampusu ilə seçilən dövlət universitetidir.',
      ru: 'ODTÜ — ведущий государственный университет в Анкаре, полностью англоязычный, известный инженерными и естественными науками и огромным лесистым кампусом.',
    },
  },
  {
    id: 'u-ankara',
    name: 'Ankara University',
    slug: 'ankara-university',
    cityId: 'c-ankara',
    foundedYear: 1946,
    studentCount: 70000,
    ranking: 12,
    accreditation: 'YÖK Accredited',
    isState: true,
    logoText: 'AU',
    heroImage: seedImages.law,
    gallery: [seedImages.campusBuilding, seedImages.law, seedImages.business],
    languages: ['tr', 'en'],
    tagline: {
      en: 'The first university of the Republic',
      tr: 'Cumhuriyetin ilk üniversitesi',
      az: 'Respublikanın ilk universiteti',
      ru: 'Первый университет Республики',
    },
    description: {
      en: 'Ankara University is a historic public university offering a broad range of programs from law and medicine to social sciences.',
      tr: 'Ankara Üniversitesi, hukuk ve tıptan sosyal bilimlere kadar geniş program yelpazesi sunan tarihi bir devlet üniversitesidir.',
      az: 'Ankara Universiteti hüquq və tibbdən sosial elmlərə qədər geniş proqram çeşidi təklif edən tarixi dövlət universitetidir.',
      ru: 'Анкарский университет — исторический государственный университет с широким спектром программ от права и медицины до социальных наук.',
    },
  },
  {
    id: 'u-izmir-econ',
    name: 'Izmir University of Economics',
    slug: 'izmir-university-of-economics',
    cityId: 'c-izmir',
    foundedYear: 2001,
    studentCount: 9000,
    ranking: 60,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'İUE',
    heroImage: seedImages.business,
    gallery: [seedImages.business, seedImages.campusLibrary, seedImages.izmir],
    languages: ['en', 'tr'],
    tagline: {
      en: 'Coastal city, global mindset',
      tr: 'Sahil şehri, küresel vizyon',
      az: 'Sahil şəhəri, qlobal baxış',
      ru: 'Прибрежный город, глобальное мышление',
    },
    description: {
      en: 'A private university in Izmir focused on economics, business and design, with many English-taught programs and international exchange options.',
      tr: "İzmir'de ekonomi, işletme ve tasarım odaklı, birçok İngilizce program ve uluslararası değişim seçeneği sunan bir vakıf üniversitesidir.",
      az: 'İzmirdə iqtisadiyyat, biznes və dizayn yönümlü, bir çox ingilis dilində proqram və beynəlxalq mübadilə seçimi təklif edən özəl universitetdir.',
      ru: 'Частный университет в Измире с фокусом на экономику, бизнес и дизайн, множеством англоязычных программ и международным обменом.',
    },
  },
  {
    id: 'u-btu',
    name: 'Bursa Technical University',
    slug: 'bursa-technical-university',
    cityId: 'c-bursa',
    foundedYear: 2010,
    studentCount: 8000,
    ranking: 80,
    accreditation: 'YÖK Accredited',
    isState: true,
    logoText: 'BTÜ',
    heroImage: seedImages.engineering,
    gallery: [seedImages.campusAerial, seedImages.engineering, seedImages.bursa],
    languages: ['tr', 'en'],
    tagline: {
      en: 'Modern engineering in an industrial hub',
      tr: 'Sanayi merkezinde modern mühendislik',
      az: 'Sənaye mərkəzində müasir mühəndislik',
      ru: 'Современная инженерия в промышленном центре',
    },
    description: {
      en: 'A young public university in Bursa with strong ties to industry, focused on engineering, natural sciences and technology.',
      tr: 'Sanayi ile güçlü bağları olan, mühendislik, fen ve teknolojiye odaklanan genç bir Bursa devlet üniversitesidir.',
      az: 'Sənaye ilə güclü əlaqələri olan, mühəndislik, təbiət elmləri və texnologiyaya yönəlmiş gənc Bursa dövlət universitetidir.',
      ru: 'Молодой государственный университет в Бурсе с сильными связями с промышленностью, ориентированный на инженерию и технологии.',
    },
  },
  {
    id: 'u-antalya-bilim',
    name: 'Antalya Bilim University',
    slug: 'antalya-bilim-university',
    cityId: 'c-antalya',
    foundedYear: 2010,
    studentCount: 7000,
    ranking: 90,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'ABU',
    heroImage: seedImages.antalya,
    gallery: [seedImages.business, seedImages.arts, seedImages.antalya],
    languages: ['en', 'tr'],
    tagline: {
      en: 'Study where the world vacations',
      tr: 'Dünyanın tatil yaptığı yerde eğitim',
      az: 'Dünyanın tətil etdiyi yerdə təhsil',
      ru: 'Учиться там, где отдыхает мир',
    },
    description: {
      en: 'A private university in the Mediterranean city of Antalya, offering tourism, business and engineering programs with an international focus.',
      tr: 'Akdeniz şehri Antalya\'da turizm, işletme ve mühendislik programları sunan uluslararası odaklı bir vakıf üniversitesidir.',
      az: 'Axaravana şəhəri Antalyada turizm, biznes və mühəndislik proqramları təklif edən beynəlxalq yönümlü özəl universitetdir.',
      ru: 'Частный университет в средиземноморской Анталье с программами по туризму, бизнесу и инженерии и международной направленностью.',
    },
  },
  {
    id: 'u-konya',
    name: 'Konya Food and Agriculture University',
    slug: 'konya-food-and-agriculture-university',
    cityId: 'c-konya',
    foundedYear: 2013,
    studentCount: 5000,
    ranking: 110,
    accreditation: 'YÖK Accredited',
    isState: false,
    logoText: 'KTAÜ',
    heroImage: seedImages.konya,
    gallery: [seedImages.campusBuilding, seedImages.arts, seedImages.konya],
    languages: ['tr', 'en'],
    tagline: {
      en: 'Specialised in food, agriculture and bioscience',
      tr: 'Gıda, tarım ve biyobilimde uzman',
      az: 'Qida, kənd təsərrüfatı və biotexnologiyada ixtisaslaşmış',
      ru: 'Специализация на пищевых технологиях, сельском хозяйстве и бионауках',
    },
    description: {
      en: 'A niche private university in Konya dedicated to food science, agriculture and bioscience, with industry-aligned research.',
      tr: 'Konya\'da gıda bilimi, tarım ve biyobilime adanmış, sanayi odaklı araştırma yapan niş bir vakıf üniversitesidir.',
      az: 'Konyada qida elmi, kənd təsərrüfatı və biotexnologiyaya həsr olunmuş, sənaye yönümlü tədqiqatlar aparan xüsusi özəl universitetdir.',
      ru: 'Нишевый частный университет в Конье, посвящённый пищевым наукам, сельскому хозяйству и бионауке с исследованиями, ориентированными на промышленность.',
    },
  },
  {
    id: 'u-ytu',
    name: 'Yıldız Technical University',
    slug: 'yildiz-technical-university',
    cityId: 'c-istanbul',
    foundedYear: 1911,
    studentCount: 36000,
    ranking: 20,
    accreditation: 'YÖK Accredited',
    isState: true,
    logoText: 'YTÜ',
    heroImage: seedImages.architecture,
    gallery: [seedImages.architecture, seedImages.engineering, seedImages.istanbul],
    languages: ['tr', 'en'],
    tagline: {
      en: 'Design and engineering on the European shore',
      tr: 'Avrupa yakasında tasarım ve mühendislik',
      az: 'Avropa sahilində dizayn və mühəndislik',
      ru: 'Дизайн и инженерия на европейском берегу',
    },
    description: {
      en: 'A prominent public technical university in Istanbul, strong in architecture, design, engineering and the sciences.',
      tr: "İstanbul'da mimarlık, tasarım, mühendislik ve fen alanlarında güçlü öne çıkan bir devlet teknik üniversitesidir.",
      az: 'İstanbulda memarlıq, dizayn, mühəndislik və elm sahələrində güclü tanınmış dövlət texniki universitetidir.',
      ru: 'Известный государственный технический университет в Стамбуле, сильный в архитектуре, дизайне, инженерии и науках.',
    },
  },
];
